# Mục lục {- #muc-luc}

**Tập 1**  

1. [Vô sư trí vô tôn](#vo-su-tri-vo-ton)  
2. [Tam huệ học - Tam vô lậu học](#tam-hue-hoc-tam-vo-lau-hoc)  
3. [Người biết tu Phật thì rất nhẹ nhàng, thảnh thơi](#nguoi-tu-phat-nhe-nhang-thanh-thoi)  
4. [Chánh tín và mê tín](#chanh-tin-va-me-tin)  
5. [Lục tặc và lục thông](#luc-tac-va-luc-thong)  
6. [Nghiệp từ đâu mà ra](#nghiep-tu-dau-ma-ra)  
7. [Ba điều căn bản của người tu Phật](#ba-dieu-can-ban-cua-nguoi-tu-phat)  
8. [Đức tự tín của người Phật tử](#duc-tu-tin)  

**Tập 2**  

1. [Đức từ bi và nhẫn nhục](#tu-bi-va-nhan-nhuc)  
2. [Cương yếu để tu](#cuong-yeu-de-tu)  
3. [Bỏ tất cả là được tất cả](#bo-tat-ca-duoc-tat-ca)  
4. [Người khéo tu Phật sẽ được bình an hạnh phúc](#kheo-tu-se-binh-an-hanh-phuc)  
5. [Phật pháp trị tận gốc tâm bệnh](#tri-tam-benh)  
6. [Tánh không và chân không](#tanh-khong-va-chan-khong)  
7. [Phản quan tự kỷ bổn phận sự bất tùng tha đắc](#phan-quan-tu-ky-bo-phan-su-bat-tung-tha-dac)  
8. [Nói chuyện về Thiền tông tại Đại học Khoa học xã hội và nhân văn Tp. HCM](#noi-chuyen-ve-thien-tong)  

**Tập 3**  

1. [Đường lối tu thiền Thiền tông Việt Nam](#duong-loi-tu-thien-thien-tong-viet-nam)  
2. [Tu là chuyển nghiệp, là dẹp bỏ tham sân si](#chuyen-nghiep-dep-bo-tham-san-si)  
3. [Những trở ngại là chướng duyên hay thắng duyên?](#tro-ngai-la-chuong-duyen-hay-thang-duyen)  
4. [Đạo Phật là đạo như thật](#dao-phat-la-dao-nhu-that)  
5. [Cho người già bệnh](#cho-nguoi-gia-benh)  
6. [Đức Phật là bậc vô thượng y vương](#duc-phat-la-bac-vo-thuong-y-vuong)  
7. [Vô minh](#vo-minh)  
8. [Tu là dừng, chuyển và sạch nghiệp](#tu-la-dung-chuyen-va-sach-nghiep)  
9. [Tu là nguồn hạnh phúc](#tu-la-nguon-hanh-phuc)  
10. [Chữ Không trong bài kinh Bát Nhã](#chu-khong-trong-kinh-bat-nha)  

**Tập 4**  

1. [Đạo Phật là đạo giác ngộ](#dao-phat-la-dao-giac-ngo)  
2. [Tùy duyên nhi bất biến](#tuy-duyen-nhi-bat-bien)  
3. [Phăng tìm cội gốc của đạo Phật](#coi-goc-cua-dao-phat)  
4. [Đạo Phật là đạo diệt khổ](#dao-phat-la-dao-diet-kho)  
5. [Đãi cát tìm vàng](#dai-cat-tim-vang)  
6. [Tại sao chúng ta phải ngồi thiền?](#tai-sao-ngoi-thien)  
7. [Đạo Phật nói thẳng lẽ thật](#dao-phat-noi-le-that)  
8. [Pháp tu căn bản của hệ Nam tông và pháp tu căn bản của hệ Bắc tông](#nam-tong-va-bac-tong)  
9. [Thiền tông là cội gốc của đạo Phật](#thien-tong-la-coi-goc-cua-dao-phat)  
10. [Tánh không và chân không](#tanh-khong-va-chan-khong-2)  

**Tập 5**  

1. [Thế gian chú tâm vào việc nhỏ, bỏ việc lớn](#viec-nho-bo-viec-lon)  
2. [Đạo Phật là đạo bình đẳng tự do tuyệt đối](#dao-phat-binh-dang-tu-do)  
3. [Nguồn gốc tu hành của Phật](#nguon-goc-tu-hanh-cua-phat)  
4. [Đạo Phật là đạo yêu đời](#dao-phat-la-dao-yeu-doi)  
5. [Hồi đầu thị ngạn](#hoi-dau-thi-ngan)  
6. [Đường lối tu Thiền](#duong-loi-tu-thien)  
7. [Ý nghĩa chữ Huệ Quang](#y-nghia-chu-hue-quang)  
8. [Thiền tông là cội gốc của đạo Phật](#thien-tong-la-coi-goc-cua-dao-phat-2)  
9. [Lễ giỗ tổ cố Hòa thượng Thích Thiện Hoa lần thứ 28](#gio-to-hoa-thuong-thich-thien-hoa-lan-28)  
10. [Ý nghĩa xuất gia - Tam huệ - Tam vô lậu học](#y-nghia-xuat-gia-tam-hue-tam-vo-lau-hoc)  

**Tập 6**  

1. [Nghiệp duyên](#nghiep-duyen)  
2. [Mục đích tu thiền](#muc-dich-tu-thien)  
3. [Người mê, kẻ tỉnh thương mình khác nhau ở chỗ nào?](#nguoi-me-ke-tinh-thuong-minh-khac-nhau-cho-nao)  
4. [Thần thông bất năng địch nghiệp](#than-thong-bat-nang-dich-nghiep)  
5. [Hoa hay là rác?](#hoa-hay-la-rac)  
6. [Khéo chọn con đường tốt](#kheo-chon-con-duong-tot)  
7. [Phật hóa hữu duyên nhân](#phat-hoa-huu-duyen-nhan)  
8. [Vui nào tạm bợ, vui nào chân thật](#vui-tam-bo-vui-chan-that)  
9. [Ý nghĩa chữ tu](#y-nghia-chu-tu)  
10. [Ai thực tế hơn ai?](#ai-thuc-te-hon-ai)  

**Tập 7**  

1. [Chỗ đồng khác giữa Phật học và Khoa học](#phat-hoc-va-khoa-hoc)  
2. [Khuyên gắng tu hành](#khuyen-gang-tu-hanh)  
3. [Tài sản không bao giờ mất](#tai-san-khong-bao-gio-mat)  
4. [Tu ba nghiệp](#tu-ba-nghiep)  
5. [Tu thiền](#tu-thien)  
6. [Lợi ích của tu thiền](#loi-ich-cua-tu-thien)  
7. [Một ngọn núi ba con đường](#mot-ngon-nui-ba-con-duong)  
8. [Giải thoát là cốt lõi của đạo Phật](#giai-thoat-la-cot-loi-cua-dao-phat)  
9. [Giáo lý tối thượng](#giao-ly-toi-thuong)  
10. [Thiền tông và kinh điển không hai](#thien-tong-va-kinh-dien-khong-hai)  

**Tập 8**  

1. [Con người bất tử](#con-nguoi-bat-tu)  
2. [Người leo núi](#nguoi-leo-nui)  
3. [Cội gốc sanh tử và Niết-bàn](#coi-goc-sanh-tu-va-niet-ban)  
4. [Thuyết luân hồi](#thuyet-luan-hoi)  
5. [Phật giáo Thiền tông thực tế đến không ngờ](#phat-giao-thien-tong-thuc-te)  
6. [Tập nghiệp](#tap-nghiep)  
7. [Thân người khó được](#than-nguoi-kho-duoc)  
8. [Nhân thừa và Bồ-tát thừa](#nhan-thua-va-bo-tat-thua)  
9. [Tinh thần xuất trần của đạo Phật](#tinh-than-xuat-tran-cua-dao-phat)  
10. [Trí thức và trí tuệ](#tri-thuc-va-tri-tue)  

**Tập 9**  

1. [Bản chất đạo Phật bi quan hay lạc quan?](#dao-phat-bi-quan-hay-lac-quan)  
2. [Lục hòa](#luc-hoa)  
3. [Ông Phật hay ông Bụt](#ong-phat-hay-ong-but)  
4. [Lòng tin của người con Phật](#long-tin-cua-nguoi-con-phat)  
5. [Tại sao người Phật tử phải tụng kinh, niệm Phật, trì chú và tọa thiền?](#tai-sao-phai-tung-kinh-niem-phat-tri-chu-toa-thien)  
6. [Những điều cần thiết trong sự tu hành](#nhung-dieu-can-thiet-trong-tu-hanh)  
7. [Tinh thần tự do trong đạo Phật](#tinh-than-tu-do-trong-dao-phat)  
8. [Hồi quang phản chiếu, phản quan tự kỷ](#hoi-quang-phan-chieu-phan-quan-tu-ky)  
9. [Phật giáo Thiền tông Việt Nam](#phat-giao-thien-tong-viet-nam)  
10. [Bồi dưỡng cho lớp giảng sư](#boi-duong-cho-lop-giang-su)  

**Tập 10**  

1. [Đạo Phật thực tế không huyễn hoặc](#dao-phat-thuc-te-khong-huyen-hoac)  
2. [Ông thiện ông ác](#ong-thien-ong-ac)  
3. [Mê và giác](#me-va-giac)  
4. [Đường lối tu theo đạo Phật](#duong-loi-tu-theo-dao-phat)  
5. [Nguồn an vui lâu dài](#nguon-an-vui-lau-dai)  
6. [Tu hành phải tinh tấn](#tu-hanh-phai-tinh-tan)  
7. [Phương pháp tu Tịnh độ tông và Thiền tông](#phuong-phap-tu-tinh-do-tong-va-thien-tong)  
8. [Nghiệp thức và tánh giác](#nghiep-thuc-va-tanh-giac)  
9. [Tứ ân trong ý chí hiếu tu](#tu-an-trong-y-chi-hieu-tu)  
10. [Tổ sư Thiền](#to-su-thien)  
