# (PART\*) Tập 1 {-}
# Vô sư trí vô tôn {- #vo-su-tri-vo-ton}

Vừa rồi chùa Cổ Pháp ở Hà Nội có nhờ tôi đặt cho một đôi liễn và một bảng hoành phi. Trong bảng hoành phi năm chữ tôi đặt như thế này: *"Vô sư trí vi tôn"*. Đây là câu mà tôi rất tâm đắc. Tôi tin chắc rằng quý Phật tử tu rồi cũng tâm đắc như tôi.

Vô sư trí vi tôn nghĩa là trí vô sư tôn quý nhất. Tại sao tôi nói như vậy? Bởi vì chúng ta tu cốt là được giác ngộ, cốt được thành Phật nhưng mà giác ngộ cái gì? Đó là một vấn đề mà người Phật tử chúng ta cần phải hiểu. Nói đến đây tôi nhắc lại cho quý vị nhớ, thuở xưa đức Phật Thích Ca đi tu, qua những lần học hỏi với các vị tiên nhân nhưng chưa đạt được mục đích, cuối cùng Ngài từ giã hết để tu khổ hạnh. Sau khi tu khổ hạnh không có hiệu quả, Ngài sống trở lại bình thường và đến dưới cội bồ đề tọa thiền bốn mươi chín ngày đêm, Ngài được giác ngộ. Sau khi giác ngộ Ngài tuyên bố một câu như thế này:  

> "Ta đã hàng phục tất cả, rõ biết tất cả. Ta không nhiễm một pháp nào. Ta xa lìa hết thảy, diệt dục mà giải thoát và tự mình chứng ngộ thì còn ai là thầy của ta?"
> 
> <div class="align-right">*(Kinh Pháp Cú)*</div>

Ngay câu nói đó chúng ta tự kiểm nghiệm xem: Ngài hàng phục được tất cả, Ngài không nhiễm tất cả, Ngài lìa hết thảy, Ngài diệt dục được giải thoát và tự mình chứng ngộ thì còn ai làm thầy? Như vậy cái chứng ngộ của đức Phật không do ai dạy Ngài hết. Nếu có người dạy tức là có thầy nhưng ngược lại không có ai dạy nên không có ai là thầy của Phật. Không thầy tại sao được giác ngộ? Điều đó chắc quý Phật tử cũng nhớ, như Phật đã tuyên bố do Ngài hàng phục tất cả, biết được tất cả, không nhiễm một pháp nào, xa lìa hết thảy, diệt dục mà giải thoát. Nghĩa là đức Phật tự hàng phục được nội tâm, tự biết rõ được tất cả các pháp thiện ác, nhiễm tịnh v.v... và Ngài không nhiễm các pháp ác, không kẹt các pháp thiện, do đó mà diệt dục được giải thoát là do tự chứng ngộ chớ không có ai là thầy cả.

Hiện giờ tất cả quý Phật tử đang tu tập tọa Thiền, vậy tọa Thiền để làm gì? Để hàng phục mình phải không? Hàng phục từ thân đến tâm của chính mình. Trong khi ngồi thiền, nếu ngồi quen nửa giờ mà thêm chừng mười phút nữa thì sao? Chắc là mười phút cay đắng. Như vậy nếu chúng ta cố gắng ngồi được một giờ hay hơn một giờ v.v... đó là chúng ta đã hàng phục được sự nhọc nhằn của thân. Kế đó đến nội tâm, tức là ý niệm của chúng ta như một dòng nước chảy xiết vậy, hết niệm này tới niệm kia liên tục không ngừng. Thế nên chúng ta tọa thiền để thắng hết tất cả những thứ niệm đó, không cho nó khởi liên tục, từ từ chúng lặng dần cho đến lúc không còn dấy động nữa. Như vậy hàng phục được tất cả niệm lăng xăng của mình. Đó là chúng ta đã tự chiến thắng, đã vào được thiền định. Vì định tức là nội tâm yên tịnh không còn lăng xăng nữa. Được như vậy rồi thì tất cả các pháp nhiễm, tất cả các pháp ác đều xa lìa. Từ đó mọi ham muốn được tháo gỡ. Nhờ vậy trong khi tu tâm chúng ta được trong lặng sáng suốt, dứt hết các nhiễm ô rồi thì tự giác ngộ. Mà tự giác ngộ thì ai là thầy của chúng ta? Tự giác ngộ là trí vô sư sẵn có của mình.

Chúng ta nhớ đức Phật tọa thiền dưới cội Bồ đề bốn mươi chín ngày đêm, tâm yên tĩnh trong lặng, cho đến khi Ngài hướng tâm về quá khứ liền nhớ vô số kiếp về trước đã từng làm gì, ở đâu và tất cả sự việc xảy ra như thế nào. Ngài nhớ như là chuyện xảy ra hôm qua rõ ràng không thiếu sót, đó gọi là chứng Túc mạng minh. Khi Ngài hướng tâm về vị lai thấy chúng sinh sau khi chết sẽ đi về đâu? Cái gì lôi dẫn đi? Ngài thấy rõ chúng sinh do nghiệp dẫn đi trong các đường, đó là chứng được Thiên nhãn minh. Như vậy chứng Túc mạng minh, chứng Thiên nhãn minh v.v... tất cả cái chứng đó đều do vô sư trí mà ra, chớ không phải ở đâu, không do ai dạy hết.

Chúng ta tu Thiền là cốt cho tâm được thanh tịnh trong lặng. Từ tâm thanh tịnh trong lặng đó hiện ra trí vô sư. Trí vô sư hiện ra rồi thì chúng ta thấy biết những gì trước kia ta chưa hề thấy biết, điều đó rất rõ ràng. Tôi dẫn một việc nhỏ này cho quý Phật tử nghiệm xem, có những Phật tử tu được chút chút, lúc tọa thiền yên lặng, bất chợt nhớ lại câu kinh hôm nào mình học không hiểu, khi nhớ lại bỗng dưng hiểu ra. Cái hiểu này do ai dạy? Lúc đó không có thầy giảng, không có người nói, tại sao nhớ lại rồi bỗng dưng hiểu, hiểu một cách rõ ràng sáng suốt. Thử hỏi ai dạy? Đó là hiện tượng của trí vô sư, điều nhỏ thì sáng nhỏ, điều lớn thì sáng lớn.

Như vậy chúng ta tu hành cần đạt được trí vô sư thì mới có thể được giác ngộ thành Phật. Như vậy Phật ở đâu? Phật sẵn ở nơi mình. Muốn thấy Phật, chịu khó dẹp hết mây phiền não, mây nghiệp chướng, nếu nó trong sạch hết thì ông Phật mình hiện ra, chớ không có ở đâu cả. Lâu nay chúng ta cứ nghĩ Phật ở đâu trên non, trên núi nên phải trèo đèo lội suối, phải đi thật xa tìm Phật, nhưng thực tình Phật ở ngay nơi mình. Vì vậy, người học đạo không nên có tâm tìm kiếm bên ngoài mà chỉ dồn hết sức mình phá dẹp phiền não, dừng lặng dòng tư tưởng lăng xăng. Những thứ đó tan rồi, lặng rồi thì ông Phật hiện tiền.

Vậy quý Phật tử tu Thiền là lối tu gần hay xa, khó làm hay dễ làm, thực tế hay mơ hồ? Việc làm đó là thực của mình, vì mình dẹp được phiền não thì mình hết khổ, dừng được tâm lăng xăng thì tâm được an định. Tâm hết phiền não, được an định thì trí tuệ bừng sáng, ngay nơi mình chớ không có ở đâu xa hết. Cho nên người Phật tử tu Thiền lúc nào cũng phải dụng công tu hành cho chiến thắng được mình, chớ không được cầu xin ai khác. Lâu nay Phật tử mình đã quen cầu xin, bây giờ phải ngồi lại thấy khổ quá chừng. Hồi đó quen lạy Phật cầu xin cho con cái này cho con cái kia, bây giờ bắt xoay lại mình để quán sát đâu là thực đâu là hư, đâu là xấu đâu là tốt, nhận định rồi tự mình phá dẹp. Thấy việc đó nhọc nhằn không quen nhưng đó mới thực là chỗ tu hành chân chính. Đức Phật ngày xưa đã như vậy, bây giờ chúng ta cũng làm như vậy thì mới đúng là đi theo Phật, còn mình làm khác đi thì không biết mình theo Phật hay theo ai? Tôi chủ trương tu theo Phật thì phải sử dụng phương pháp Phật sử dụng ngày xưa, ứng dụng vào sự tu của mình sẽ có kết quả không nghi.

Tôi xin dẫn câu chuyện sau đây để quý Phật tử nghiệm xem. Thiền sư Nham Đầu và Thiền sư Tuyết Phong Nghĩa Tồn đi đến Ngao Sơn gặp trời trở tuyết, nên hai huynh đệ vào trong cái miếu nhỏ ở tạm. Mỗi hôm ngài Tuyết Phong đều ngồi thiền, còn ngài Nham Đầu thì không ngồi. Ngài Nham Đầu mới quở ngài Tuyết Phong sao ngồi thiền mãi như vậy. Ngài Tuyết Phong nói:

\- Tôi thật còn chưa ổn.

Ngài Nham Đầu bảo:

\- Nếu ông thật như thế, cứ chỗ thấy của ông mỗi mỗi thông qua, chỗ phải tôi sẽ chứng minh cho ông, chỗ chẳng phải tôi sẽ vì ông đuổi dẹp.

Ngài Tuyết Phong kể lại:

\- Khi xưa tôi mới đến chỗ Thiền sư Diêm Quan thấy Ngài thượng đường nói về nghĩa sắc không, ngay nơi đó tôi liền được vào cửa.

Ngài Nham Đầu bảo:

\- Từ đây đến 30 năm sau rất kỵ không được nói đến.

Ngộ được lý sắc không mà Ngài Nham Đầu nói chưa được, 30 năm sau rất kỵ nói đến cái đó. Như vậy chúng ta mới thấy trong thời gian tu thiền có nhiều chặng. Bước đầu mới vào cửa thiền đa số chúng ta đều học Bát-nhã. Học Bát-nhã là để nhận được lý sắc không *(sắc tức thị không, không tức thị sắc)*. Bước vào cửa không đã là một bước tiến trên đường tu rồi, nhưng chưa phải là chỗ cứu kính. Nên ngài Nham Đầu mới bảo: *"Từ đây đến 30 năm sau rất kỵ không được nói đến"*. Ngài Tuyết Phong kể tiếp:

\- Tôi thấy bài kệ của ngài Động Sơn khi qua cầu ngộ đạo *(Ngài Động Sơn qua cầu, nhìn dưới dòng suối thấy bóng của mình, ngay đó Ngài ngộ đạo)* liền làm bài kệ:  
  
<div class="align-center">
> Thiết kỵ tùng tha mích  
> Điều điều dữ ngã sơ  
> Cừ kim chánh thị ngã  
> Ngã kim bất thị cừ  
</div>

*"Thiết kỵ tùng tha mích"* nghĩa là rất tối kỵ, chẳng nên tìm nơi khác mà được. Vì nếu tìm nơi khác thì đã cách xa, không phải là mình. *"Cừ kim chánh thị ngã"*, nghĩa là nó chính là mình. *"Ngã kim bất thị cừ"* nhưng mình thì không phải là nó. Bởi vì ngài Động Sơn đi trên cầu, nhìn dưới suối thấy bóng của mình, cái bóng thì đâu phải là mình nhưng nó có rời mình không? Vì vậy nên nói nó cũng chính là mình *"Cừ kim chánh thị ngã"*. Nhưng mình không phải là nó, tức mình không phải là bóng, ngài Động Sơn do nhận thấy bóng của mình mà ngộ đạo, ngài Tuyết Phong nhân nghe được câu này cũng có tỉnh. Bởi tỉnh nên trình với ngài Nham Đầu nhưng ngài Nham Đầu lại bảo rằng: *"Nếu chừng ấy tự cứu cũng chưa xong"*. Đó là chặng thứ hai.

Chặng thứ nhất là thấu suốt được lẽ sắc không, chặng thứ hai là biết nơi mình, bên cạnh cái giả cócái thật. Bóng là giả nhưng cái giả đó không rời cái thật. Biết được lý ấy rồi cũng vẫn chưa tới nơi, nên ngài Nham Đầu nói: *"Chừng ấy tự cứu cũng chưa xong"*. Ngài Tuyết Phong kể thêm: *"Một hôm tôi hỏi ngài Đức Sơn việc tông thừa con có phần chăng, ngài Đức Sơn đánh một gậy hỏi tôi nói cái gì? Tôi khi ấy như thùng lủng đáy"*. Như thùng lủng đáy nghĩa là rỗng và sạch hết, vậy mà ngài Nham Đầu nạt: *"Ông chẳng nghe nói từ cửa vào chẳng phải của báu trong nhà"*.

Cái gì từ cửa vào thì không phải là của báu trong nhà. Câu này để giản trạch cho chúng ta hiểu người tu phải nhận được cái chân thật của mình. Cái chân thật của mình luôn có sẵn đây, chớ còn nhờ bên ngoài thì chưa được. Chúng ta ngồi thiền lặng lẽ, tỉnh giác, chợt phút giây nào bừng sáng lên thì đó mới thật là của mình. Còn đi hỏi người này, đi học người kia, thì sự hiểu biết ấy không phải là của mình, mà là của người ta.

Sau này ngài Tuyết Phong hỏi thêm:

\- Về sau làm thế nào mới phải?

Ngài Nham Đầu bảo:

\- Về sau, muốn xiển dương đại giáo mỗi mỗi từ trong hông ngực lưu xuất, sau này cùng ta che trời che đất đi.

Ngài Tuyết Phong ngay câu này liền bừng ngộ, nên gọi là ngộ đạo ở Ngao Sơn *(tức là ở núi Ngao)*. Như vậy chỗ cuối cùng là từ hông ngực mà phát ra, chớ không phải ở bên ngoài. Nếu còn ở ngoài thì chưa phải tột. Chúng ta tu từ nội tâm phát sáng, từ nội tâm giác ngộ, đó mới là chân thật, là trí vô sư hiện. Trí này là thật của chúng ta, nó trùm khắp không chỉ giới hạn trong thân tứ đại thôi.

Qua những chặng tôi nêu quý Phật tử nên hiểu, mình tu Thiền không phải chỉ một lần ngộ. Khi chúng ta bước vào sự tu, nghe kinh Bát-nhã hoặc đọc kinh Kim Cương, chúng ta thấy lóe được nghĩa Sắc Không cũng đã đáng mừng rồi. Từ chỗ ngày xưa mình thấy Sắc riêng Không riêng, bây giờ thấy Sắc tức là Không, Không tức là Sắc. Đây là bước đầu có tỉnh, có ngộ nhưng chỉ là tiểu ngộ thôi, chớ chưa phải đại ngộ. Đến như đọc một bài kệ, một câu thơ của các Thiền sư, mình nhận ra và lãnh hội được ý nghĩa câu đó đúng như điều mình đang hiểu, đang tu thì xem như bừng sáng một chặng nữa. Đây cũng là một chặng đường thôi. Hoặc giả trong khi tu, đem những lời đạo lý bàn luận với huynh đệ, thưa hỏi với thầy, được thầy nói cho một câu liền bừng sáng, nhẹ người lên. Lúc đó thấy như thùng lũng đáy, như vậy đó mà cũng vẫn chưa rồi. Cho đến bao giờ tự mình phát sáng ra, nhận thấy tất cả thực thể muôn pháp trong thế gian này thì chừng đó mới thật là đại ngộ. Thế nên ở trong nhà Thiền nói tiểu ngộ thì vô số, còn đại ngộ cũng đôi ba lần, chớ không phải một lần. Tôi từ khi tu cho đến bây giờ, hướng dẫn Tăng, Ni cũng như Phật tử tu, thấy tiểu ngộ khá nhiều, còn cũng có vài người gần như được đại ngộ. Đây là điều đáng mừng.

Lúc trước tôi có mặc cảm mình dạy người ta tu Thiền, nhất là giai đoạn đầu ra Chân Không, tôi mở khóa thứ nhất có mười người thôi, không dám nhận đông. Tại sao vậy? Bởi vì tôi nghe nhiều người nói: *"Coi chừng! Tu Thiền điên"*, nên tôi thí nghiệm mười vị này xem có điên không. Dù biết tôi tu không điên, nhưng chưa rõ những người tu theo tôi thì sao? Qua ba năm không thấy ai điên hết nên khóa thứ hai tôi tăng lên ba, bốn chục vị. Rồi bây giờ đến mấy trăm người cũng không thấy ai điên. Do đó tôi hết mặc cảm lời người ta nói. Nếu bảo rằng tu Thiền điên là điều hết sức tai hại cho người tu Phật.

Chúng ta đã biết đức Phật Thích Ca do ngồi thiền ngộ đạo, bây giờ sao đệ tử Ngài ngồi thiền lại điên? Nói như vậy là một cái họa cho người tu Phật, nhất là tu Thiền. Còn một điều nữa, có người nói tu Thiền chỉ dành cho hàng thượng căn thượng trí mới tu được thôi, thời này mình tiểu căn tiểu trí tu không được.Ngày xưa tôi cũng mặc cảm vì câu nói đó nhưng sau này tôi lại nghĩ khác. Chúng ta có bệnh cứ nghĩ người xưa mới thông minh, người xưa mới có căn trí bén nhạy, còn chúng ta bây giờ đần độn, ngu tối. Thật ra nếu xét kỹ có phải vậy không? Hồi xưa có người thông minh nhưng cũng có người đần độn. Ngày nay cũng thế, có nhiều người thông minh lắm chứ. Biết bao điều người xưa chưa biết, bây giờ nhờ khoa học và văn minh chúng ta được biết. Có những việc người xưa không làm được mà bây giờ ta làm được, tại sao lại nói ta đần độn? Như vậy bây giờ phải khôn hơn hồi xưa chứ! Nếu dại hơn thì hồi xưa chỉ biết đi bộ, sao bây giờ biết đi máy bay. Hồi xưa cái gì cũng thô sơ sao bây giờ cái gì cũng tinh vi? Người đời khôn hơn thời xưa, chẳng lẽ người tu dại hơn người xưa? Sao tệ vậy! Cho nên tôi không chịu. Tôi nói người xưa làm được thì ngày nay chúng ta làm cũng được, chỉ có điều chúng ta làm có đúng như người xưa không. Người xưa do đủ điều kiện mà thành công thì chúng ta nếu đủ điều kiện chắc chắn cũng sẽ thành công. Cứ cho rằng người xưa thông minh, thượng căn thượng trí và nghĩ mình là đần độn, như vậy là tự khi mình; mà khi mình thì tiến không được.

Trong nhà Thiền có câu: *"Đệ tử bằng thầy là đã thua thầy nửa đức, đệ tử hơn thầy mới kham gìn giữ sự nghiệp của thầy"*. Tại sao trong nhà Thiền nói như vậy? Thí dụ như tôi tu năm mươi năm, bây giờ có người đệ tử ngộ bằng tôi, nhưng tu mới mười năm thì đã thua tôi phân nửa rồi. Vì ngộ thì bằng nhưng công đức tu chưa bằng, nên nói thua thầy. Khi nào thầy ngộ mười mà đệ tử ngộ được hai mươi mới kịp với thầy. Vậy ông thầy trông cho đệ tử giỏi hơn, chớ không muốn đệ tử thua mình. Không nên nói: *"Ta trước căn cơ bậc thượng, còn người sau căn cơ bậc hạ, tu không được"*. Người sau vẫn có khả năng như người trước, chỉ có điều nếu người sau không làm đúng nguyên tắc người trước đã làm thì người sau tu sai trật; sai trật thì tu không có kết quả.

Gần đây tôi thấy Tăng, Ni tu có tiến, thỉnh thoảng một vài Phật tử tu cũng có tiến. Như vậy tôi rất mừng, vì việc làm của chúng ta không phải phí công vô ích, mà có kết quả thật sự. Người nào ham tu thì giảm phiền não, một trăm phần cũng giảm được vài chục phần. Như vậy có tu thì có tiến. Tu ít thì kết quả ít, tu nhiều thì kết quả nhiều. Tất cả kết quả đó đều do công phu soi sáng lại chính mình để nhận ra cái chân thật của mình. Khi đã nhận ra rồi thì tự mình sẽ vượt qua hết những khó khăn, những đau khổ ở đời. Đến đây tôi kể thêm một chuyện nữa để làm sáng tỏ thâm ý trên. Câu chuyện này được trích từ tác phẩm *"Góp nhặt cát đá"* của Nhật Bản. Có một chú mù lâu ngày nhớ bạn, nên hôm đó chú chống gậy đi tìm thăm bạn. Gặp lại bạn cũ chú mừng quá nên ở chơi, nói chuyện đến khuya vẫn chưa chịu về. Thấy vậy, người bạn nhắc chú: *"Đã khuya quá rồi anh nên về"*, chú mới chịu về. Người bạn thấy bên ngoài trời tối mà bạn mình lại mù, sợ nguy hiểm nên nói:

\- Để tôi đốt cho anh cây đèn, anh cầm đi về.

Chú mù cười:

\- Tôi thì ngày như đêm, đêm như ngày; bây giờ anh đốt đèn, tôi cũng đâu thấy cái gì.

Anh bạn nói:

\- Biết vậy. Nhưng nhờ anh cầm cây đèn, người khác thấy được sẽ không đụng anh.

Nghe có lý nên chú mù cầm đèn đi về. Được nửa đường bỗng có người đầu kia đi lại đụng phải, chú la lên:

\- Bộ anh không thấy tôi sao?

Người kia nói:

\- Dạ thưa ông, tôi không thấy.

\- Tôi cầm cây đèn đây mà anh không thấy à?

\- Cây đèn của ông đã tắt từ bao giờ rồi!

Qua câu chuyện đó quý vị hiểu thế nào? Nếu mình không tự sáng, dù cho người khác đem ánh sáng đến trao tay cho mình cũng không cứu được mình. Đèn bên ngoài đưa lại, đó là hữu sư trí. Trí do người khác cho mình thì cứu mình không được, chỉ con mắt mình sáng mới cứu được mình thôi. Mắt mình sáng đó là vô sư trí, không ai dạy mà tự sáng. Bởi vậy nên người học Phật hay tu Phật phải khai thác trí sẵn có của mình là quý hơn hết.

Kế nữa là câu chuyện của Ngài Đức Sơn. Một hôm Ngài đứng hầu thầy là Thiền sư Sùng Tín. Thấy khuya quá ngài Sùng Tín bảo:

\- Ông đi nghỉ đi.

Ngài Đức Sơn vâng lời xá thầy, vén rèm bước ra. Thấy bên ngoài tối quá nên Ngài quay trở lại, ngài Sùng Tín hỏi:

\- Sao ông trở lại?

Ngài Đức Sơn thưa:

\- Bạch Hòa thượng, bên ngoài trời tối đen.

Nghe nói vậy, ngài Sùng Tín bèn đốt cây đèn cầm đưa cho Đức Sơn. Đức Sơn vừa đưa tay nhận cây đèn thì ngài Sùng Tín vụt thổi tắt. Ngài Đức Sơn liền ngộ. Như vậy ngài Đức Sơn ngộ cái gì? Nếu mình thấy tối phải nhờ đèn, nhưng nếu đèn do người khác trao thì chưa làm mình sáng được. Ngài Đức Sơn vừa cầm đèn thì ngài Sùng Tín liền thổi tắt. Ngay đó Đức Sơn tự bừng ngộ, cho nên *"cái đó"* phải tự mình sáng ra, chớ người khác trao cho không được.

Như vậy tôi giảng Thiền, dạy Thiền cũng chỉ là hướng dẫn cho quý vị thực hành thôi, sáng hay tối là do quý vị chớ không phải tôi. Bởi tôi không có khả năng làm cho quý vị sáng mà chỉ hướng dẫn thế này, thế nọ... rồi tự quý vị theo đó tự khai thác, tự ngộ. Chừng nào ngộ, báo tin cho tôi mừng thôi. Tôi không làm gì cho quý vị cả. Lẽ thực trong đạo là vậy.

Qua những câu chuyện trên, chúng ta thấy người tu Thiền là người đang đào bới thửa đất tâm của mình để tìm cho ra hòn ngọc trong đó. Đến khi nào chúng ta phát hiện và nắm hòn ngọc được rồi là điều quý nhất, đáng mừng nhất của người tu. Được *"cái đó"* mới gọi là chân thật, còn tất cả những gì chúng ta hiểu, chúng ta nghe ai nói chỉ là phụ thôi. Đó là ý nghĩa vô sư trí mà mỗi người chúng ta phải tự thấy, tự biết.

Nếu không nhờ vô sư trí thì có lẽ các nhà khoa học sẽ không có các phát minh. Bởi vì phát minh là thấy biết, phát hiện ra những điều từ trước đến giờ chưa ai biết; mà điều chưa ai biết thì ai dạy mình? Chỉ người có chí dồn hết tâm lực vào một việc, rồi ngày nào tự bừng sáng lên, gọi là phát minh. Người thế gian lo giúp cho đời nên phát minh vật chất, còn chúng ta tu hành thì lo phát minh cái sẵn có của mình. *"Cái đó"* bị chôn vùi, bây giờ chúng ta phải làm cho nó sáng ra, hiển bày ra. Khi được sáng, được hiển bày rồi thì lúc đó chúng ta phải làm gì nữa, chui vô non vô núi ở cho đến chết luôn phải không? Khi mình nhận được hòn ngọc thật và biết mọi người cũng đều có hòn ngọc đó nhưng họ quên, thì chúng ta khởi lòng từ bi thương tất cả, muốn chỉ anh có, tôi có, người khác có. Chỉ ra hòn ngọc của mỗi người sẵn có là cái chỉ bình đẳng, không thiên vị. Dù kẻ đó là quan nhưng ông quên, mình cũng thương như người khác, còn kẻ cùng đinh mà quên thì mình cũng thương như ông quan. Bởi vì chúng ta chỉ thương cái mê, cái quên của họ thôi. Nếu nói thấy ai nghèo mình thương, còn người giàu không thương, như vậy là mất bình đẳng. Thương cái mê, cái quên vì họ có của báu mà không nhớ, nên người nào quên chúng ta cũng thương, như vậy lòng thương đó mới bình đẳng. Chính vì ai cũng có của báu, có hòn ngọc quý, nên dù nam hay nữ cũng tu thành Phật được hết. Chỉ quên thì không có, còn nhớ và ráng tu là được. Thế nên tinh thần Thiền tông hết sức bình đẳng, nam nữ như nhau, ai cũng có hòn ngọc quý nên ai cũng có quyền thành Phật cả.

Trong kinh Pháp Hoa, phẩm Đề Bà Đạt Đa, có Long Nữ được ngài Văn Thù giáo hóa. Ngài Văn Thù nói với ngài Xá Lợi Phất: *"Long Nữ này sẽ thành Phật"*, ngài Xá Lợi Phất không tin vì người nữ và hơn nữa là súc sanh thì làm gì thành Phật được. Long Nữ nghe nói như vậy liền đem viên ngọc minh châu dâng lên cúng dường Phật. Phật nhận, Long Nữ hỏi ngài Xá Lợi Phất:

\- Tôi dâng ngọc, đức Thế Tôn nhận có mau không?

Ngài Xá Lợi Phất nói:

\- Mau.

\- Tôi thành Phật cũng mau như vậy đó.

Liền khi đó Long nữ ẩn mình qua nước khác thành Phật. Như vậy là sao? Văn Thù Sư Lợi trong kinh Pháp Hoa là tiêu biểu cho vô sư trí. Đã có vô sư trí thì nam nữ gì cũng thành Phật chớ không phân biệt phái nào.

Người nữ đứng về mặt nghiệp tướng thì khác, nhưng về mặt vô sư trí thì bình đẳng với người nam. Vì vậy Thiền tông luôn khai thác trí vô sư đó. Dưới con mắt nhà Thiền thấy nam nữ bình đẳng như nhau, ai cũng có khả năng thành Phật. Tăng Ni, Phật tử nam hay Phật tử nữ, cho đến cả người thế gian chưa từng biết đạo cũng có hòn ngọc quý, cho nên không ai là kẻ bần cùng, chỉ người quên mới bần cùng thôi.

Nếu chúng ta ứng dụng tu cho đến nơi, đến chốn thì quyền thành Phật là quyền của mình, chớ không phải Phật cho mình thành Phật. Phần nhiều chúng ta mong muốn được Phật thọ ký, nhưng chúng ta có làm được thì Phật mới thọ ký, còn không làm được thì Phật làm sao thọ ký? Chúng ta có quyền làmPhật và chúng ta cũng có quyền làm ngạ quỷ, súc sanh. Chính vì chúng ta có quyền đó nên chúng ta phải nỗ lực tinh tấn tu hành, để đi lên chớ đừng đi xuống. Không ai phạt chúng ta cả, trời không phạt, Phật không phạt mà chỉ vì mình chọn đường đi. Chọn đường đi xuống thì đi xuống, chọn đường đi lên thì đi lên, tất cả đều do mình chọn.

Có người nói Thiền tông nói gì cũng hướng về mình hết, không nhờ bên ngoài; như vậy không nhờ Phật sao? Thật ra chúng ta phải hiểu như vầy: Phật chỉ cho chúng ta đường lối tu, căn bản các pháp tu là đã gia hộ cho chúng ta rồi. Cũng như quý vị không biết gì hết, tôi chỉ cho quý vị biết chút chút rằng, quý vị có hòn ngọc quý báu, có cái sáng suốt, nhưng quý vị phải tự tìm lấy. Đó là tôi đã gia hộ cho quý vị, chớ đâu phải đợi gặp tai nạn rồi ban cho điều này, điều kia mới gọi là gia hộ. Hướng dẫn một lối đi, chúng ta theo đó tự sáng lên tránh khỏi mọi khổ đau. Đó gọi là gia hộ. Lại, nói về thầm gia hộ thì như đứa học trò siêng năng cần mẫn, thông minh, thầy cô giáo dạy đâu đều học, đều hiểu và đều thực hành được hết. Làm bài nó có xin thầy giáo cho con điểm cao và thầy cô có chiều nó không? Nếu nó thông minh, học giỏi, làm bài hay thì nhất định thầy cô phải cho điểm cao. Cho điểm cao là thầy cô thương nó hay là tại cái gì? Tại nó cố gắng học.

Cũng vậy, người tu của chúng ta, nếu tu chân chánh, cần mẫn thì sau này có kết quả tốt. Còn nói rằng Phật thọ ký hay Bồ tát hướng dẫn cho mình, thật ra đó là do công phu nỗ lực của mình, cố gắng thực hành theo lời dạy bảo của các Ngài, nên việc tu mới có kết quả. Nhờ sự nỗ lực, cố gắng đó mà được điểm tốt. Thầm gia hộ là như vậy. Phật thương chúng ta, muốn chúng ta tu tiến từ chính sự cố gắng nỗ lực của chúng ta. Được thế, Phật mừng và khen ngợi; khen ngợi đó là thầm gia hộ rồi.

Hôm nay tôi đến thăm Đạo tràng Thái Tuệ, vừa để biết chỗ nơi tu hành của quý Phật tử, vừa trực tiếp nhắc nhở sách tấn quý vị tu tập. Tôi nghĩ quý Phật tử cũng từng nghe giảng, nghe tôi nói nhiều rồi, mong rằng từ đây về sau tất cả quý Phật tử trong Đạo tràng và những Phật tử xung quanh biết mình có của báu quý giá rồi, phải ráng nỗ lực khai thác tìm ra cho được mà dùng, đừng làm cùng tử lang thang nữa. Đó là sự mong mỏi của tôi.
