# (PART\*) Tập 2 {-}
# Đức từ bi và nhẫn nhục {- #tu-bi-va-nhan-nhuc}

Hôm nay nhân quý thầy chùa Bửu Thọ mời chúng tôi về dự lễ an vị đức Bồ-tát Quán Thế Âm và khai đại hồng chung của chùa, nên tôi sẽ giảng về đề tài Đức từ bi và nhẫn nhục. Bởi vì tôn tượng Bồ-tát Quán Thế Âm tượng trưng cho hạnh từ bi trong đạo Phật.

Từ bi và nhẫn nhục là hai pháp tu tối thiết yếu của người Phật tử cũng như người xuất gia. Từ bi là ban vui, cứu khổ. Người có lòng từ bi là người thương tất cả chúng sanh bình đẳng như nhau. Vì thương mọi người nên đem hết cả tâm tư sức lực của mình làm cho mọi người được vui, hết khổ, nên gọi là ban vui, cứu khổ.

Ở đời ai không có khổ, hoặc nhiều hoặc ít thôi. Chư Phật và Bồ-tát thương muốn cho chúng ta hết khổ nên các Ngài dạy chúng ta tu. Vì vậy từ bi là hạnh thiết yếu trong đạo Phật. Kế đến là nhẫn nhục. Bởi có từ bi mà thiếu nhẫn nhục thì không bao giờ thực hiện được hạnh từ bi. Nhẫn nhục lúc nào cũng ở bên cạnh từ bi, không thể riêng rẽ được, nên tôi giảng chung từ bi và nhẫn nhục.

Trong kinh Pháp Hoa Phật có dạy, muốn vào nhà Như Lai tức phải có lòng từ bi, muốn mặc áo Như Lai tức phải nhẫn nhục. Tóm lại, muốn vào nhà Phật, mặc áo Phật phải tu hạnh từ bi và nhẫn nhục. Nếu không có từ bi, không có nhẫn nhục thì không thể vào nhà Phật, mặc áo Phật được. Nên người Phật tử thiếu từ bi thì chưa phải Phật tử. Đây là vấn đề mà quý Phật tử cần phải hiểu.

Nói từ bi theo nghĩa cứu khổ ban vui, quý Phật tử cảm thấy khó hiểu. Để gần gũi và dễ hiểu hơn, tôi có thể nói từ bi là tình thương vì mọi người chớ không phải vì mình. Chúng ta ai cũng có tình thương, nhưng tình thương vì mình nhiều hơn vì mọi người. Ví dụ ta đi đâu trễ xe hoặc trễ đò, có một người tử tế mời vào nhà uống nước, ăn cơm để chờ tới chuyến đò, chuyến xe sau. Họ xử sự rất tốt nên ta nói người đó dễ thương quá. Tại vì họ tốt với mình nên mình nói dễ thương. Nếu người ấy xấu với mình thì mình không thương. Như vậy để thấy tình thương của chúng ta đi đôi với bản ngã. Tình thương đó không gọi là từ bi. Đến bao giờ chúng ta thấy người lem luốc, xấu xí, không lễ độ, đói khổ mà ta vẫn thương. Chúng ta cho chén cơm, ổ bánh mì, dù họ không cám ơn nhưng chúng ta vẫn thấy vui. Đó là tình thương của lòng từ bi, thấy người khổ mình thương, mình giúp mà không cần đền đáp.

Là người Phật tử biết học Phật, tu Phật thì nên tập mở rộng tình thương. Ai khổ, ai đói thì chúng ta thương, không vì bản ngã, không đợi người giúp mình, mình mới thương lại. Đó là tình thương của lòng từ bi. Còn vì mình thì chưa phải từ bi. Nên hiểu cho tường tận, chớ thương người này, thương người kia rồi cho đó là từ bi thì không thể được. Bởi từ bi hệ trọng như vậy nên người Phật tử bước chân vào đạo phải tập mở rộng lòng thương mọi người. Đó là tập tâm từ bi. Có tâm từ bi rồi thì chúng ta tu mới có thể tiến được. Còn chưa có từ bi thì không thể nào chúng ta tiến được trên đường tu.

Tại sao từ bi phải đi đôi với nhẫn nhục? Như ở thế gian có người con hiếu thảo, thương cha mẹ nhưng gia cảnh nghèo làm không đủ ăn. Bấy giờ Giám đốc một xí nghiệp nhận vào làm, trong xí nghiệp anh ta bị rầy, bị quở nhiều thứ, xúc chạm tới tự ái. Nhưng vì thương cha mẹ thiếu thốn nên vẫn chịu đựng, nhịn nhục làm có tiền để nuôi cha mẹ. Do đó phải ẩn nhẫn, cực khổ, nhục nhã chớ không dám bỏ việc.

Như vậy tình thương giúp cho chúng ta có sức chịu đựng, sức nhẫn nại. Đó gọi là nhẫn nhục. Nếu chúng ta không thương cha mẹ thì khi gặp cảnh bị rầy la, khinh bạc liền bỏ quách, cần gì phải làm, chỗ này không được kiếm chỗ khác. Nhưng vì thương cha mẹ cho nên nhẫn chịu mọi sự phiền hà, xúc phạm. Đó là vì tình thương mà phải nhẫn nhục.

Một ví dụ nữa, như người phụ nữ gặp ông chồng bạo hành, nhưng đã có với nhau hai, ba mặt con. Người chồng bạo hành chịu hết nổi thì lẽ ra phải ly dị nhưng vì thương con, sợ con bơ vơ không còn đủ cha mẹ, việc học hành sa sút … Thương con mà nhẫn nhịn sự bạo hành của chồng. Như vậy cũng vì tình thương mà phải chịu đựng. Trường hợp trước là người con hiếu, vì thương cha mẹ mà nhận chịu những khó khăn, khinh bỉ. Trường hợp sau vì thương con mà không bỏ được người bạn từng hành hạ mình, chịu đựng mọi điều … Nên biết, nhờ tình thương mà người ta có thể nhẫn chịu những cái khó nhẫn. Nếu không có tình thương thì chắc rằng con người sẽ không đủ sức để vượt qua những cảnh khó khổ.

Sống trong đời chúng ta muốn làm điều lành, điều tốt nhưng chắc gì được mọi người tán thán. Cho nên muốn làm điều lành điều tốt để giúp mọi người, thì trước chúng ta phải tập có lòng thương mạnh mẽ đối với mọi người. Đó là từ bi. Kế phải có sức nhẫn nại, chịu đựng những khó khăn.

Chúng ta không nên hiểu lầm nhẫn nhục là điều xấu, theo quan niệm của nhiều người, nhẫn là phải chịu nhục. Theo tôi thì không phải vậy. Nhẫn nhục là một sức mạnh chớ không phải yếu đuối. Thế gian thường cho rằng người làm việc gì bị la rầy, quở mắng nhưng vẫn ráng chịu đựng là người yếu đuối, nhu nhược, vì không dám chống cự lại, đôi khi còn bảo là ngu. Nhưng trong đạo Phật không phải vậy. Đạo Phật dạy nhẫn nhục là một sức mạnh. Nếu chúng ta để ý sẽ thấy ở những ngôi chùa xưa thường viết câu Đại Hùng Bửu Điện, tức là điện báu thờ đấng Đại Hùng. Đức Phật là đấng Đại Hùng, nhưng Ngài có đánh dẹp ai đâu mà tôn vinh là Đại Hùng?

Trong kinh Pháp Cú, Phật có dạy thế này:
  
> Thắng một vạn quân không bằng thắng mình. Thắng mình mới là chiến công oanh liệt nhất.  

Nghĩa là người nào thắng được mình mới gọi là người hùng. Thắng giặc bên ngoài chưa phải là hùng. Như vậy nhẫn nhục là việc dễ hay khó? Bị người sỉ nhục, mắng nhiếc ta, ta sỉ nhục, mắng nhiếc lại là dễ hay nhịn nhục là dễ? Mắng lại là dễ chớ bỏ qua khó lắm. Đừng nói chi người lớn, trẻ con khi bị ức hiếp nó tức giận la lối dễ hay làm thinh dễ? Như vậy khi trái ý, nổi giận la lối con nít làm cũng được, còn nhẫn nhịn, người lớn đôi khi làm chưa nổi nữa. Qua đó thì biết cái nào khó! Khó mà làm được nên gọi là Đại Hùng. Đức Phật được gọi là Đại Hùng vì Ngài nhẫn được những điều khó nhẫn.

Trong kinh kể lại, có lần đức Phật trên đường du hóa, một thầy Bà-la-môn lẽo đẽo theo sau chửi nhưng Phật cứ thong thả đi. Ông tức quá chận lại hỏi:

\- Ngài Cồ Đàm! Ngài có điếc không?

Phật đáp:

\- Không.

\- Không điếc sao ông nghe tôi mắng chửi mà không có phản ứng?

\- Ta không điếc. Việc mắng chửi của ông có liên hệ gì với ta đâu.

Phật liền nói ví dụ:

\- Như nhà ông có giỗ mời bà con quyến thuộc tới dự. Khi họ sắp về, ông gói quà bánh tặng. Những người ấy không nhận thì quà đó về ai?

Ông Bà-la-môn đáp:

\- Nếu họ không nhận thì quà đó về tôi chớ về ai.

Phật bảo:

\- Cũng vậy, ông chửi ta mà ta chẳng nhận thì những lời mắng chửi đó xin gửi lại cho ông.

Người ta cứ nghĩ rằng nhịn là thua, nhưng trường hợp vừa kể, đức Phật có thua không? Chửi Ngài mà Ngài không chống cự lại thì hậu quả tự trở về người chửi. Chúng ta thử tập khi bị mắng chửi mà chúng ta cứ lặng lẽ làm thinh không nói gì hết thì rốt cuộc người nào tức hơn. Người bị chửi tức hay người chửi tức? Cho nên tưởng rằng tranh hơn thua là hay, không ngờ càng tranh là càng lún sâu vào phiền não. Chẳng khác nào như lửa cháy mà cứ chế thêm dầu hoài. Còn một bên nóng giận, một bên im lặng, không có lời thách đố nhau thì làm gì có chuyện đấu tranh để dẫn đến những việc tai hại lớn lao. Rõ ràng nhẫn nhịn là điều hết sức quan trọng, không phải việc thường. Người biết nhẫn nhịn là người làm được việc lớn, còn người không nhẫõn nhịn được thì không làm được việc gì hết. Cho nên chúng ta muốn làm được điều hay điều tốt thì phải có đức nhẫn nhịn mạnh mẽ, như vậy việc làm mới thành công.

Chúng ta ai cũng biết câu chuyện Quan Âm Thị Kính. Tôi lược kể điểm hay đặc biệt của bà Quan Âm Thị Kính. Theo sử sách Trung Quốc thì bà thuộc gia đình khá giả, có danh giá, chồng bà là một nho sinh hiếu học. Gia đình hai bên cũng môn đăng hộ đối. Một hôm nhân chồng học hành mệt mỏi nên nằm ngủ trưa. Bà nhìn thấy có sợi râu mọc ngược lên trên khó coi, nên lấy kéo định hớt giùm sợi râu. Nhưng vừa đưa kéo đụng vào thì ông giật mình chụp tay la: *"Ám sát tôi"*. Ông la lên như vậy thì cả nhà đều tin theo, nói bà định dùng kéo ám sát ông chồng.

Việc đó có oan không? Vì ông ngủ mơ màng không tỉnh táo nên bị đụng vào da liền giật mình hoảng hốt, thấy bà đang cầm kéo thì la lên nói vợ ám sát mình. Dù bà có nói gì cũng không ai tin hết. Cuối cùng gia đình bên chồng giao trả bà về cha mẹ của bà, vì là nàng dâu hư. Cha mẹ bà cũng không biết nói sao hơn nên đành đem con về. Về nhà mình rồi, bà nghĩ sự tủi nhục vì là con nhà thế phiệt mà bây giờ mang tiếng giết chồng, nhưng không biết làm sao minh oan được. Vì vậy bà định đi tu để khỏi mang tai tiếng cho cha mẹ.

Hồi xưa ở Trung Hoa chưa có phái nữ đi tu, chỉ có phái nam thôi. Nên muốn đi tu bà phải giả trai. Khi vào chùa được Hòa thượng nhận cho ở, nhưng vì có nhan sắc nên giả trai bà cũng đẹp. Do đó động lòng Thị Mầu, con một nhà giàu thường lui tới viếng chùa. Thị Mầu có tâm không tốt nên sau này gần gũi với người nô bộc của gia đình, cô mang thai rồi đổ oan cho ông đạo Kỉnh Tâm, tức pháp danh của bà. Sự việc Thị Mầu khai trước làng xã đòi bà đến công đường tra hỏi. Bà trả lời không có gì hết nhưng chẳng ai tin. Dù bị tra khảo đánh đập đi không nổi nhưng bà vẫn chịu đựng, không tiết lộ mình là người nữ để minh oan. Cuối cùng làng mời Hòa thượng đến trả bà về chùa nuôi dạy lại. Như vậy mới thấy sức chịu đựng phi thường của bà.

Khi về chùa, Hòa thượng không biết sự việc thế nào nên xử sự với bà khác lúc trước. Bà không được ở trong chùa mà phải ở hành lang. Thời gian sau Thị Mầu sanh đứa con trai, cô bồng đứa bé đến chùa giao cho bà nói rằng: *"Con của ông nay tôi giao trả cho ông"*.

Chúng ta thấy rõ ràng sự việc không có gì dính dáng mà bây giờ xảy ra đến mức độ như vậy. Bà can đảm nhận nuôi đứa bé, bởi bà nghĩ người tu dù cho công phu nhiều mà không có lòng từ bi thì cũng không xứng đáng. Vì chúng sanh, vì cứu một mạng người nên bà chấp nhận hết mọi nhục nhã, mọi hình phạt. Cho nên trong một đoạn thơ truyện Quan Âm Thị Kính có câu này:
  
<div class="align-center">
> Dù xây chín bậc phù đồ  
> Không bằng làm phước cứu cho một người  
</div>
  
Phù đồ tức là cái tháp, ý câu này nói dù xây tháp chín tầng, không bằng cứu một sinh mạng con người. Nghĩ vậy nên bà đành ôm đứa nhỏ nuôi. Sự việc này càng làm cho Hòa thượng nghi ngờ, nếu không phải con của bà thì sao nhận lãnh nuôi. Sống trong hoàn cảnh ấy bà vẫn âm thầm chịu đựng. Mỗi ngày ẵm đứa bé đi khắp xóm làng xin sữa bú, chịu đựng mọi khinh bỉ, chê bai của thiên hạ. Bà kiên nhẫn nuôi cho đứa bé lớn lên. Thời gian chịu nhục nhã không biết là bao nhiêu. Một đứa trẻ không có liên hệ máu mủ gì hết mà vì lòng từ bi muốn cứu một mạng sống, không để cho nó chết nên bà phải chịu nhục nhã, đủ thứ xấu xa. Tới khi đứa bé lớn rồi, từ đó bà mới được tu hành yên ổn, và đến lúc lâm chung mọi người phát hiện bà là người nữ thì bà đã đắc quả vị Bồ-tát. Người đời sau thường gọi là Quan Âm Thị Kính.

Đó là tôi kể tổng quát, bây giờ tôi nhấn mạnh thêm tinh thần nhẫn nhục của bà để chúng ta noi theo tu tập.

Thứ nhất, bà nhẫn khi bị chồng vu oan. Việc ngẫu nhiên thôi mà bị hàm oan như thế. Nếu người không có can đảm, bị oan ức đó có thể tự tử. Thường người ta cho rằng tự tử là gan, nhưng tôi thì nói ngược lại, tự tử là không can đảm. Bởi vì xấu hổ chịu đựng không nổi, không đủ sức nhẫn nên mới tự tử, nếu đủ sức nhẫn thì đâu có tự tử. Bà không tự tử mà sống và tu. Đó là một đức nhẫn nhục lớn.

Thứ hai, khi đi tu bị người ta vu oan là quan hệ với Thị Mầu có thai. Điều đó hết sức vô lý vì bà là người nữ. Nếu muốn minh oan rất dễ, chỉ cần nói tôi là người nữ thì mọi việc đều êm xuôi hết. Nhưng vì muốn được tiếp tục tu hành, bà không muốn lộ tông tích mình là người nữ, nên phải nhận lãnh sự hành hạ, đánh đập, khảo tra.

Trường hợp trước nhẫn để được sống và tu. Trường hợp thứ hai, vì sự tu nên cam chịu khổ nhọc. Và đến giai đoạn cuối cùng là lòng từ bi thương đứa bé ra đời không có cha mẹ nuôi dưỡng. Sợ nó chết tội nên nhận nuôi, chịu nhục nhã, không phải một ngày mà cả mấy chục năm trời. Chính vì lòng từ bi nên bà đã có sức kiên nhẫn phi thường như vậy. Khi đã vượt qua sức chịu đựng đó bà liền thành tựu Bồ-tát. Chúng ta thấy lòng từ bi, sức nhẫn nhục vượt hơn tất cả người thường tình. Do đó thành tựu được Bồ-tát hạnh. Bây giờ chúng ta tôn vinh bà là Phật Bà Quan Âm.

Như vậy, người chịu đựng được là người mạnh mẽ, có một sức nhẫn phi thường. Cho nên tu muốn đến nơi đến chốn đòi hỏi chúng ta phải có đủ hai mặt, vừa có lòng từ bi vừa có đức nhẫn nhục. Từ bi nhẫn nhục đủ thì chúng ta mới tu tiến, mới thành công. Còn chỉ có từ bi mà thiếu nhẫn nhục thì khó thành công. Ví dụ như chúng ta thấy người nghèo khổ muốn giúp đỡ nhưng họ không biết mang ơn. Vậy là chúng ta không muốn giúp nữa. Đó là chúng ta làm việc lành, việc tốt mà chưa có đức nhẫn nhục nên dễ lùi lắm.

Đó là tôi nói Bồ-tát Quán Thế Âm ở trong truyện thơ Quan Âm Thị Kính. Bây giờ tôi nói Bồ-tát Quán Thế Âm trên hình tượng mà quý vị đang thờ. Chúng ta đến chùa lễ Bồ-tát Quán Thế Âm thường thấy Ngài dưới hình thức người nữ, nhưng thật ra Bồ-tát không có nam nữ. Trong kinh Phổ Môn có nói rõ, Bồ-tát Quán Thế Âm khi cần độ đồng nam thì hiện thân đồng nam. Khi cần độ đồng nữ thì hiện thân đồng nữ, cần độ Tể Quan thì hiện thân Tể Quan. Như vậy Ngài không có thân nhất định là nam hay nữ, mà tùy theo căn cơ chúng sanh thích thân gì thì hiện ra thân ấy. Song vì người nữ giàu tình thương, Ngài thường hiện thân nữ.

Vì vậy khi nói về tình thương, người ta hay nói như mẹ hiền thương con. Cha cũng thương nhưng có khi phải răn, phải đánh. Còn mẹ thương thường vuốt ve mà ít đánh. Do đó mà nói mẹ hiền, ít nói cha hiền. Cha nghiêm nên hay gọi nghiêm phụ, mẹ hiền nên hay gọi từ mẫu. Do đó lòng từ thường được tượng trưng qua người nữ. Ngài Quán Thế Âm tu hạnh từ bi nên Ngài hiện thân người nữ để thể hiện hạnh nguyện của mình.

Kế đó chúng ta thấy trên tay trái Ngài cầm tịnh bình, tay phải cầm cành dương. Như vậy ý nghĩa như thế nào? Bình là để chứa nước cam lồ. Tôi xin đọc lại một đoạn nguyên văn chữ Hán trong Từ bi Thủy sám:  

> Thùy dương liễu nhi biến sái cam lồ. Trừ nhiệt não ĩ giai đắc thanh lương. Tầm thinh cứu khổ ư tứ sanh. Thuyết pháp độ thoát ư lục đạo.

Như vậy là Ngài cầm cành dương rưới nước cam lồ từ trong tịnh bình. Nước cam lồ và cành dương tượng trưng cho cái gì? Chữ cam là ngọt, lộ là sương. Mù sương đọng trên lá cây, nước đó trong sạch và ngọt gọi là cam lồ. Nước cam lồ là tượng trưng cho tâm từ bi. Tâm ấy trong sạch, dịu ngọt như cam lồ. Vì vậy từ bi tới đâu thì lửa nhiệt não tắt ngụm tới đó. Ngọn lửa phiền não của chúng ta cháy hừng hực nên chỉ có nước từ bi mới dập tắt được. Phiền não nóng giận là sân. Muốn cho hết sân, qua được cơn nóng giận phải có lòng từ bi. Nên nước cam lồ tượng trưng cho lòng từ bi. Khi ta gặp khổ đau, người có lòng từ bi khuyên dạy ta sẽ giảm. Những chúng sanh đang trong cảnh đói thiếu, đủ thứ tai nạn, gặp được những người có lòng từ bi thì họ sẽ được cứu giúp. Cho nên khổ đau chỉ có lòng từ bi mới đưa đến sự bình an.

Nước cam lồ đem rưới cho mọi người được mát mẻ thì phải nhờ cành dương. Có người lấy cành trúc hay cành tre thay thế cành dương để rưới nước cam lồ. Nhưng sự thật ý nghĩa nước cam lồ chỉ rưới được qua cành dương. Tại sao vậy? Vì cành dương nhỏ, mảnh, khi gặp gió thì nó uyển chuyển nhưng mà không gãy. Như vậy để nói lên ý nghĩa người có đức nhẫn nhục, gặp cảnh khó khăn luôn tùy thuận, nhẫn nại, không chống đối. Mới nhìn như yếu, lại dẻo dai chịu đựng, không bị gãy, bị thua. Như vậy hình ảnh cành dương nói lên đức nhẫn nhục. Vì nhẫn nhục mới có thể đem nước cam lồ hay lòng từ bi chan rải cho mọi người được. Nếu không có nhẫn nhục thì không bao giờ chan rải được lòng từ bi.

Rõ ràng từ bi và nhẫn nhục nương nhau thì làm việc gì cũng thành tựu. Có từ bi mà thiếu nhẫn nhục hay ngược lại, có nhẫn nhục mà thiếu từ bi cũng không được. Cho nên trong kinh nói cầm cành dương Ngài rưới nước cam lồ lên khắp cả. Trừ nhiệt não, Ngài làm cho mọi người đều được tắm trong dòng suối thanh lương. Nghe tiếng kêu mà cứu khổ cho tứ sanh. Ngài thuyết pháp độ khắp cả lục đạo.

Qua đó chúng ta thấy hình tượng Ngài cầm cành dương rải nước cam lồ lên tất cả mọi người, đó là đem lòng từ bi chan rải khắp muôn loài. Do sức mạnh của lòng từ bi mà tiêu diệt được lòng sân hận của con người. Chúng ta sống nếu không có lòng từ bi thì không thể nào thực hiện được những điều đức Phật đã dạy.

Tôi nhắc lại khi đức Phật còn tại thế, có lần trên đường giáo hóa, gặp một nhóm côn đồ mắng chửi thậm tệ, nhưng Ngài vẫn thản nhiên, không có thái độ nào tỏ vẻ khó chịu hay bất mãn. Nhưng tôn giả A Nan chịu không nổi, liền thưa với Phật:

\- Bạch Thế Tôn, chúng ta nên đi nơi khác.

Phật bảo:

\- Bây giờ đi chỗ nào A Nan?

Ngài A Nan thưa rằng:

\- Đi chỗ nào không có người chửi mắng mình thì mới có thể truyền đạo.

Phật bảo:

\- Giả sử chúng ta đi đến chỗ khác cũng có người mắng chửi nữa thì làm sao A Nan?

Ngài A Nan thưa:

\- Như vậy thì chúng ta tìm lại những nơi đã từng giáo hóa như thành Xá Vệ hoặc những nơi có đệ tử của Ngài.

Phật bảo:

\- Này A Nan! Nếu là thầy thuốc giỏi thì có nên treo tấm bảng trước nhà rằng: *"Ở đây chỉ nhận chữa những bệnh thông thường, còn bệnh nặng thì mời đi nơi khác"*?

Ngài A Nan thưa:

\- Không.

Phật hỏi:

\- Tại sao vậy?

Ngài A Nan thưa:

\- Thầy thuốc giỏi thì trị bệnh nặng, còn bệnh thường có gì quan trọng.

Phật bảo:

\- Cũng vậy, người ta đang bệnh ta phải trị cho họ, chừng nào họ không cần thì ta mới đi.

Ngài A Nan nói:

\- Họ đang chửi mình thì họ đâu cần mình.

Những người côn đồ nghe nói vậy liền thức tỉnh lên tiếng:

\- Bạch Ngài, chúng con cần Ngài.

Do đó đức Phật đã ở lại giáo hóa độ những người đó.

Câu chuyện đã cho chúng ta thấy, Phật dù hóa độ chúng ta nhưng không phải tới đâu người ta cũng kính ngưỡng như nhau. Ngay cả đức Phật đi giáo hóa cũng gặp nhiều cay đắng, bị trở ngại đủ thứ hết, nhưng Ngài cũng thản nhiên chịu đựng. Nhờ vậy Ngài mới thành đạo và truyền bá Phật pháp cho tới ngày nay.

Chúng ta là hàng đệ tử của Phật thì phải học gương sáng của Ngài. Vì thương những người khổ hay người ngang ngạnh nên dù họ có gây khó khăn, làm điều hung dữ, chúng ta vẫn phải độ họ, không nên giận họ. Trong đạo Phật lúc nào cũng nhắc nhở người Phật tử luôn cố gắng thực hiện cho được tinh thần từ bi nhẫn nhục. Chưa hành được hạnh đó thì chúng ta chưa phải là đệ tử của Phật.

Thật ra chúng ta ai cũng có lòng từ bi, nhưng lòng từ bi đó bị hạn chế. Ví dụ có người đi xem hát thấy các diễn viên bi lụy rơi nước mắt họ cũng khóc theo, như vậy thì có tình thương, thấy cảnh khổ mới khóc. Nhưng có điều lạ là thấy cảnh khổ trên sân khấu thì khóc, mà thấy người khổ thật ở ngoài thì thản nhiên. Nên cái khóc đó là do các diễn viên khéo gợi cảm xúc của mình, còn những cảnh khổ không gợi được cảm xúc thì không khóc, chỉ thương vì tội nghiệp thôi.

Đó là do lòng từ bi còn bị ảnh hưởng trong tình cảm riêng tư. Cho nên chúng ta hiểu đạo Phật rồi tập theo đức từ bi, chúng ta sẽ được những điều lợi ích lớn. Tất cả những gì chúng ta làm lợi cho người khác, mới thấy như thiệt thòi nhưng thực tình chúng ta giúp cho mọi người, rồi sau này mình sẽ được mọi người giúp lại. Mình xử sự tốt với mọi người thì người sẽ xử sự tốt với mình. Cũng có người thắc mắc sao tôi xử sự tốt với người mà người lại xử sự xấu với tôi? Chúng ta không nên vội nghĩ *"làm ơn lại mắc oán"*. Sự thật không phải như vậy.

Tôi thường ví dụ như trước kia chúng ta làm khổ ai đó, bây giờ mình phát tâm hiền lành tốt, nhưng sự cải tiến của mình chưa xứng với việc mình làm khổ người khi trước. Do đó dù chúng ta giúp người nhưng họ vẫn không mang ơn chúng ta mà lại còn hầm hầm nữa chứ. Cho nên hiểu được nhân quả rồi thì không giận họ mà phải biết vì việc làm của mình chưa xứng đáng, chưa thật quý, chưa cao thượng nên người chưa vừa lòng.

Có người nói từ trước tới giờ tôi chưa từng làm khổ ai chút nào, nhưng chúng ta nên nhớ trong nhà Phật nói những sự việc xảy ra với chúng ta không chỉ xảy ra trong đời này mà có sự liên hệ tới nhiều đời trước nữa. Ngày nay chúng ta tử tế với người nhưng biết đâu trước kia chúng ta làm khổ người quá nhiều. Sự oán hờn của quá khứ còn núp trong tàng thức của người, bây giờ gặp lại, dù chúng ta có làm điều lành điều tốt, nhưng chưa xứng với việc cũ nên họ không hài lòng, không thông cảm với ta.

Hiểu như vậy chúng ta chỉ trách mình chớ không trách người. Nhờ thế việc tu hành mới không trở ngại. Hiểu được như vậy, tất cả chúng ta ai cũng ý thức được rằng cuộc đời của mình nếu được tốt đẹp xứng đáng, đó là chúng ta biết từ bi, biết thương người, biết cứu giúp người. Không phải chúng ta chỉ biết bằng lời nói suông thôi mà còn phải có sức chịu đựng, nhẫn nhục.

Tôi kể thêm câu chuyện nữa, có lần đức Phật đi khất thực, một thầy Bà-la-môn theo sau chửi bới thậm tệ mà Phật vẫn thản nhiên đi. Thầy Bà-la-môn bực tức chạy lên trước chận đường hỏi:

Cồ Đàm! Ngài thua tôi chưa?

Phật liền trải tọa cụ ngồi xuống, nói bài kệ:
  
<div class="align-center">
> Người hơn thì thêm oán  
> Kẻ thua ngủ chẳng yên  
> Hơn thua hai đều xả  
> Ấy được an ổn ngủ  
</div>

Ngài nói ai còn thấy hơn, thấy thua là còn khổ. Hơn người thì oán hờn, còn thua người thì đêm đến trằn trọc ngủ không được. Chỉ người bỏ được hơn thua thì được an ổn, hạnh phúc.

Như tôi đã nói, chúng ta tôn đức Phật là đấng Đại Hùng, vì trong trường hợp nào Ngài cũng nhịn hết, không hề chống cự hoặc hành hạ ai. Ngài chỉ nhẹ nhàng nhắc nhở giáo hóa thôi. Vì vậy Ngài không hờn, không giận, không oán thù. Sức chịu đựng đó gọi là Đại Hùng.

Đức Phật là đấng Đại Hùng, chúng ta ít ra cũng làm được tiểu hùng vì chúng ta là con Phật. Vậy trong gia đình cho tới ngoài xã hội chúng ta phải sống và tu như thế nào? Nếu ở gia đình, người chồng lớn tiếng thì vợ phải nhẫn nhịn. Nhẫn nhịn không có nghĩa là xấu hổ, là thua sút. Nhẫn nhịn người ngoài còn không thua, huống nữa là nhẫn nhịn người trong nhà. Chúng ta nhẫn nhịn được tức là chúng ta tự chế ngự được sự nóng giận của mình. Nhịn người lớn hơn hoặc bằng mình thì dễ, còn nhịn những người nhỏ hơn mới thật là khó. Có những người nhỏ kém đức hạnh, ăn nói thô lỗ, chẳng lẽ chúng ta lại đi cãi vã với họ sao? Cho nên nhịn tất cả, lớn nhỏ gì cần nhẫn nhịn thì chúng ta cứ nhẫn nhịn. Nên nhớ từ bi nhẫn nhục không chỉ đối với người ngoài mà còn đối với trong gia đình nữa. Được vậy chúng ta mới biết tu, mới gọi là đệ tử của đấng Đại Hùng được.

Nếu muốn trở thành một Phật tử chân chính thì phải có tâm từ bi, có đức nhẫn nhục. Đã là Phật tử mà người động tới mỗi việc đều nổi giận hoặc thấy kẻ đó khổ không thương không giúp, thì có xứng đáng gọi là Phật tử chưa? Trong kinh Phật thường hay nhắc nhở chúng ta phải có lòng từ bi thương chúng sanh, phải chịu đựng những khó khổ để tâm trong sáng, thanh tịnh. Đó là điều không thể thiếu được.

Chúng ta còn phải biết rằng trên đường tu luôn gặp chướng duyên. Nếu không hiểu chúng ta sẽ nghĩ, chẳng lẽ mình không có phước? Người tu hạnh nhẫn nhục mà đến đâu cũng được quý kính thì chưa thể hành hạnh nhẫn nhục. Ví như đức Phật nếu không có người mạ lị thì làm sao chúng ta thấy được đức tánh cao cả của Ngài. Nhờ có kẻ càn bướng dám mắng chửi Ngài, chúng ta mới thấy được nhẫn lực phi thường của Ngài. Chúng ta tu mà có người kính, có người chửi, có người khinh, chúng ta cũng tự nhiên như vậy, mới gọi là người thật tu.

Đa số Phật tử ngày nay cứ ngỡ tu là cúng kính, là làm phước mà không biết tu là xây dựng cho bản thân mình một cái tâm từ bi nhẫn nhục. Vì vậy những trở ngại trên đường tu, tôi không gọi trở ngại mà gọi thắng duyên. Nhờ có người chửi mình mà tròn được hạnh nhẫn nhục. Nếu không thì chúng ta đâu có biết mình nhẫn được hay không.

Quý Phật tử tu đừng sợ khó, đừng sợ bị thử thách. Bởi vì thử thách chính là cơ hội tốt để chúng ta thể hiện tinh thần tu hành của mình. Tu là có sức an nhẫn, có sức chịu đựng mọi thử thách, chớ không phải tu là để đón nhận mọi thứ an lành hết. Bởi người tu cũng như chèo thuyền ngược nước, ngược gió. Nếu chúng ta thả lơi thì thuyền sẽ trôi ra tới biển. Còn nếu ra sức chèo chống thì chúng ta mới đến được tận nguồn, tận nơi chúng ta muốn. Người tu hành muốn chi được nấy thì còn gì tu nữa.

Phật tử đến chùa lạy xin Phật cho con làm ăn phát đạt, mọi việc đều tốt đẹp, con cái học hành giỏi … Xin mọi thứ chớ không chịu tu. Như vậy là xin hay tu? Nếu xin Phật không được thì đâm chán. Nghe nói có Bà Chúa xứ linh lắm, chạy qua xin Bà. Xin Phật không được thì xin Bà. Người như vậy là chưa biết tu. Tu là gây dựng cho mình một đức tính tốt đẹp, một hạnh nguyện cao siêu, chớ đâu phải tu là đi xin xỏ. Phật tử chúng ta hay xin quá! Đi chùa thì đi nhưng nghe chỗ nào linh liền chạy đi cầu xin. Đó là thói thường của những người chưa hiểu được ý nghĩa của sự tu hành.

Khi hiểu được ý nghĩa của sự nhẫn nhục rồi thì chúng ta không còn than tu hành sao gặp nhiều khó khăn quá. Vị nào tu gặp trở ngại nên vui mừng nói với huynh đệ rằng: Tôi thật là đại phước, tu gặp cả mười cái trở ngại và đều vượt qua hết. Vậy đó, nhờ có trở ngại chúng ta mới thành công. Nếu không có trở ngại thì đâu có thành công. Như người tập nhảy cao, lúc đầu để cây thấp, lần lần đưa lên cao, như vậy người cầm cây gây trở ngại hay giúp cho người tập nhảy cao? Chúng ta tu cũng vậy. Tu là để mỗi ngày được thanh tịnh, mỗi ngày được sáng suốt. Muốn được như vậy thì tất cả trở ngại chúng ta đều vượt qua, xem như trò chơi, không có gì đáng để tâm. Như vậy mới thành công, còn sợ khổ, sợ khó, bị trở ngại thì tu mong cho sung sướng, chớ không phải tu để được giải thoát.

Hiểu như vậy quý Phật tử nên suy xét lại cho chín chắn, đừng buồn, đừng sợ khi chúng ta gặp trở ngại hay bị bạc đãi. Chúng ta phải có sức mạnh, lập chí cho vững, quyết tâm đi đến nơi đến nơi đến chốn. Được vậy mới là người quyết chí tu chân chánh. Tu còn cầu xin là tu tà đạo. Tu chân chánh thì phải biết chuyển sửa những điểm dở, điểm xấu của mình thành hay, thành tốt.

Đức Phật thường dạy rằng: Ta không có quyền ban phước giáng họa cho ai. Nếu Phật có quyền ban phước giáng họa cho người, thì chắc rằng Phật không dạy chúng ta phải nhẫn nhục, phải từ bi, tu nhân quả. Gây nhân tốt thì được quả tốt, gây nhân xấu thì chịu quả xấu. Nếu Phật cho được thì chúng ta đâu cần gây nhân, cứ lạy Phật rồi Phật cho. Vậy Phật có cứu chúng ta không? Phật chỉ cho chúng ta một con đường, ai đi đúng đường thì an vui, ai đi sai đường thì đau khổ.

Như quý Phật tử khi quy y tam bảo, Phật dạy phải giữ năm giới. Nếu giữ năm giới trọn vẹn thì được làm người tốt. Còn không giữ năm giới thì sẽ đọa vào đường ác như địa ngục … Giữ năm giới là tu, không giữ năm giới là không tu. Phật chỉ dạy chúng ta tu, chớ không phải đưa chúng ta vào loài người hay xuống địa ngục, ngạ quỷ. Con đường Phật vạch ra là để cho chúng ta đi, chớ không phải Phật dùng thần thông ban phước giáng họa cho chúng ta. Hiểu như vậy mới là hiểu đạo. Hiểu rồi quý Phật tử ứng dụng tu thì có lợi ích vô cùng. Bằng ngược lại, tuy đi chùa nhưng không được lợi ích bao nhiêu.

Tóm lại, chúng ta tu Phật là phải mở rộng lòng từ bi và đức nhẫn nhục. Nhẫn nhục từ bi đó phải từ sự tu sửa của chúng ta, chớ không phải ở đâu đem đến. Công phu có được chính là do sự huân tập hàng ngày mà thành tựu. Vì vậy chúng ta nên tập đức từ bi nhẫn nhục trong cuộc sống, trong từng giây phút để chúng ta có đủ đạo lực khi gặp các chướng duyên. Ngày này, giờ này chúng ta thấy thua thiệt nhưng phước đức sẽ sâu dày ở nhiều đời nhiều kiếp sau, không bao giờ mất.

Không có một vị Phật nào ngẫu nhiên mà thành Phật. Các Ngài đều do tu mà thành Phật, không có vị Bồ-tát nào bỗng dưng thành Bồ-tát. Tất cả đều qua biết bao năm tháng tu hành mới được. Vì vậy, là đệ tử Phật, chúng ta cố gắng tu tập cho xứng với ý nghĩa Phật đã dạy.

Mong tất cả ghi nhớ và thực hành cho, để đạt được kết quả như sở nguyện.
