# (PART\*) Tập 5 {-}
# Thế gian chú tâm vào việc nhỏ, bỏ việc lớn {- #viec-nho-bo-viec-lon}

<div class="align-right">
*Thiền viện Trúc Lâm, Đà Lạt*  
*Tháng 12, 2000*
</div>

Đề tài tôi nói hôm nay rất bình dân: *"Người đời việc ít quan trọng dồn hết tâm lực lo, việc tối quan trọng lại lơ là"*.

Tất cả chúng ta có mặt trên thế gian này, đều do không sáng suốt nên thường lầm lẫn, những điều không quan trọng hay ít quan trọng, chúng ta dồn hết tâm lực để lo, còn những điều tối quan trọng lại không để ý, không màng tới. Tôi sẽ tuần tự giảng giải điều này cho tất cả thấy rõ.

Như cuộc sống hiện giờ có ba việc ăn, uống, thở, trong đó chúng ta lo việc nào nhiều nhất? Thường người ta lo ăn nhiều nhất. Tối ngày chạy lo ăn, nhưng thật ra nếu nhịn ăn mấy ngày có chết không? Không chết. Kế đó là uống, nhịn uống hai ba ngày mới chết. Đến thở, nhịn bao lâu chết? Trong tích tắc, thở ra mà không hít vô là chết. Vậy mà người ta lại quan trọng ăn với uống, còn thở ra sao thì không biết. Rõ ràng việc tối quan trọng lại lơ là, còn việc không quan trọng thì dồn hết tâm lực vào đó. Như vậy mới thấy cái lầm lẫn của chúng ta thật đáng thương.

Bước qua phần thứ hai, thân và tâm tức thể xác và tinh thần, cái nào quan trọng hơn? Chúng ta thường lo cho thể xác hay tinh thần? Thể xác lo cho sạch đẹp sung mãn, còn tinh thần thì không nghĩ tới. Nhìn chung con người chỉ nặng về thể xác mà xem nhẹ phần tinh thần, trong khi tinh thần điều khiển thể xác. Ví dụ từ trong nhà đi ra đường, ta khởi nghĩ trước rồi mới đi. Làm việc gì cũng vậy, khởi nghĩ trước rồi mới làm. Rõ ràng tinh thần chỉ huy mà chúng ta lại không quan tâm, chỉ quan tâm thể xác.

Nhưng thử hỏi chúng ta lo cho thể xác được sung mãn, mà nó còn mãi không? Lo cho mấy nó cũng bại hoại. Lo nào nhà cửa, tiền bạc, cơm ăn áo mặc… nhưng khi nhắm mắt tất cả những thứ đó còn hay mất? Lo để ngày mai sẽ mất thì lo làm gì? Vậy mà chúng ta cứ lo, lo ngày lo đêm, lo hết sức là lo. Cái giữ không được mà dồn hết cho nó, còn cái chủ thúc đẩy chỉ huy lại không để ý, mặc tình nó ra sao thì ra. Như vậy chúng ta sáng suốt không? Đó là vấn đề chúng ta cần phải xét lại để khỏi lầm lẫn.

Nếu nói tâm hồn hay tinh thần là cái chỉ huy, sắp đặt cho cuộc sống, thì chúng ta phải lo cho nó tốt đẹp, cao quí mới phải, còn thân tạm bợ này lo xoàng xoàng cũng được. Thế mà ta làm ngược lại. Đó là điều rất sai lầm của đa số người thế gian.

Bây giờ nói tu là tu thế nào? Nhiều người bảo ăn chay, lạy Phật nhiều là tu. Ăn chay, lạy Phật cũng thuộc về phần thể xác, còn bộ chỉ huy thì không lo. Vì vậy tu cũng có nhiều cách. Tu bằng hình thức tạo phước tạo duyên, hoặc tu bằng cách lọc bỏ các vọng tưởng cho tâm được trong sáng thanh tịnh. Trong hai cách tu trên, cách tu sau mới là quan trọng. Bởi vì tâm là vị chỉ huy, nếu chỉ huy tốt thì thân miệng làm các việc tốt, cuộc sống theo đó quí đẹp. Còn tu về phần vật chất thì có phước, nhưng tâm còn phiền não thì không giải quyết được cội gốc vô minh sanh tử. Đó là điều quan trọng người tu chúng ta cần phải biết.

Muốn xây dựng, muốn gạn lọc cho tinh thần được trong sáng, tốt đẹp thì phải quay lại xem xét mình. Tất cả chúng ta hiện giờ có ai không biết tham lam, nóng giận, si mê là xấu đâu. Biết thì biết mà không nỡ bỏ, cho nên Phật quở chúng sanh thật mê muội, rất đáng thương. Bình thường không việc gì thì thấy rất hiền lành, nhưng gặp việc trái ý liền nổi sân đùng đùng. Nóng giận như vậy đã là sai rồi mà còn bảo vệ cho cái giận của mình, tại thế này, tại thế nọ nên tôi mới giận. Đã bảo vệ nó, thì làm sao bỏ được. Ít người nào giận mà nói lỗi tại tôi, lý đáng không nên như vậy, thật là xấu hổ… Không dám nhận lỗi là ngầm chấp nhận mình đúng người sai, nên không bao giờ chịu sửa đổi tật nóng giận của mình.

Con người thật là mâu thuẫn. Đến với Phật hít hà lạy lục, mong cho con được sáng suốt, thanh tịnh… mà những thói xấu không chịu bỏ. Đó là điều rất thực tế, Phật tử vẫn còn lúng túng. Tôi nói nóng giận là cái nổi nhất, còn tham lam, ngu si ngầm bên trong khó bỏ hơn nữa. Người tham lam có một triệu muốn hai triệu, có hai triệu muốn ba triệu, không dừng lại bao giờ. Có ít muốn nhiều, muốn hoài cũng không bao giờ thấy đủ.

Chúng ta tưởng tham không dính dáng gì sân, nhưng thật tình tham là cha đẻ của sân hận. Ví dụ ra chợ thấy món hàng vừa ý mình muốn mua. Nghe người bán nói năm trăm, mình trả ba trăm, người ta chưa chịu bán. Lúc đó có người trả bốn trăm, người ta bán. Vậy là mình nổi tức lên, rõ ràng giận từ tham mà ra. Đó là những cái tham nhỏ, chưa phải trong tầm tay của mình, còn những cái tham trong tầm tay của mình. Ta quí ta thích nó, khi mất mình sẽ sân giận tới đâu nữa.

Thí dụ mình vừa sắm được cái lục bình vừa ý, bất thần đứa cháu sẩy tay làm rớt bể. Lúc đó cơn nóng đùng đùng nổi lên, mình la ó om sòm. Cái nóng giận đó do tham của quí, muốn giữ mà mất nên mình mới sân hận. Như vậy có thể nói tất cả sự nóng giận đều bắt nguồn từ lòng tham. Như ta muốn được khen, được danh thơm tiếng tốt mà bị người chê thì nổi nóng liền. Tham danh, tham lợi, tham tài, tham sắc, tham cái nào mà không được cũng dẫn đến sân hận cả.

Song lòng tham gốc từ si mê mà ra. Như mạng sống của chúng ta qua một ngày là mất một phần. Cuộc đời vô thường, ngày nay sống chưa chắc ngày mai đã còn. Người thấy được lý vô thường là thấy được lẽ thật. Do vô thường, thở ra không hít lại là chết, mạng sống này đâu có bảo đảm dài lâu. Nhưng nghe ai nói ngắn, thì mình buồn, mình cự lại. Còn nghe nói dài, sống đến trăm tuổi là vui liền, như vậy không phải si mê là gì?         

Chúng ta thường sống với những ảo tưởng, mơ ước không có lẽ thật, đó là gốc từ si mê. Nếu ai nói mạng mình yểu ta liền xét biết, cuộc sống trong hơi thở không yểu sao được. Nói vậy, biết vậy thì cười thôi, không giận hờn ai. Vì không có trí tuệ, ta sống trong ảo tưởng, không đúng lẽ thật, nên sanh ra tham lam sân hận, đủ thứ phiền não che lấp tâm chân thật.

Từ si mê cho rằng đời sống cả trăm năm, rồi lo tạo dựng sự nghiệp không có ngày cùng, đến tắt thở cũng chưa rồi. Vì vậy mà cả một đời người mấy chục năm, chúng ta cứ lao vào hình thức vật chất, không nghĩ tới tâm tư của mình trong sáng hay tối tăm. Chúng ta không biết trau dồi tâm tánh của chính mình chút nào hết, mà lại đuổi theo những cái tạm bợ bên ngoài.

Đời này tạo lập, xây dựng nếu lỡ chết đi thì tiếc nuối không bỏ được, nên rồi phải trở lại nữa. Thế nên Phật nói si mê là gốc của luân hồi, chúng sanh trở đi trở lại không giải thoát được, gốc từ si mê mà ra. Từ si mê chúng ta có đủ thứ sai lầm. Si mê về sự sống, si mê danh vọng, si mê sắc đẹp… Bởi nghĩ mình đẹp nên ai chê xấu thì giận, nghĩ mình khôn nên ai chê ngu thì giận. Người ta cứ tưởng tượng về mình, chớ sự thật chắc gì mình đẹp, chắc gì mình tốt, chắc gì mình khôn. Nhưng nghe khen thì vui, nghe chê thì không chịu. Như vậy có phải si mê không? Con người chịu hết khổ này tiếp nối khổ kia, không thoát được là vì thế.

Bây giờ nếu chúng ta biết rõ mạng sống vô thường, thân này không thật. Ta không là gì trong xã hội này cả thì có gì để tự hào, ngạo mạn. Nghĩ mình là rơm là rác, tự nhiên ta sẽ buông bỏ được những thứ tạm bợ quanh mình, sửa đổi những thói hư tật xấu thành ra tốt đẹp. Biết thân này không có giá trị chân thật thì sẽ không còn đắm luyến nó nữa, ta mới vươn lên tìm cái chân thật. Đó là biết lo cái đáng lo, bỏ cái đáng bỏ.

Chúng ta kiểm lại ba điều: Một là mạng sống trong hơi thở. Hai là thân này hư dối tạm bợ, không có gì quan trọng. Ba là ta vẫn còn nhiều khiếm khuyết cần phải tu sửa. Nhớ như vậy, chúng ta sẽ tập trung vào việc tu dễ dàng, gạn lọc tâm trong sạch, thanh tịnh. Tịnh hóa được thân tâm rồi thì các thứ hình thức vật chất trong cuộc sống này không thể lôi kéo chúng ta được nữa. Đó là một lẽ thật.

Thật vậy, khi nhìn lại thấy thân này là đãy da hôi thối, giống như cái bô đậy kỹ, có ai đi ngang bịt mũi, mình sẽ cười nói tránh đường cho cái bô đi. Như vậy đâu có khổ. Rõ ràng lâu nay chúng ta sống trong mê lầm. Bây giờ phải gan lên, phải thấy được lẽ thật thì đời sống của mình mới an lành tự tại. Lúc nào cũng nhớ từ si mê sanh ra tham lam, từ tham lam sanh ra nóng giận. Ba thứ này là phiền não rất độc cần dẹp bỏ, chớ không thể nuôi dưỡng được.

Nhưng chúng ta có bệnh biết sai mà không can đảm sửa liền, cứ hẹn từ từ. Như vậy đòi tu mau ngộ đạo, mau thành Phật sao được! Bởi vì tu là phải dùng trí tuệ thấy đúng như thật, cái gì ảo tưởng phải chừa bỏ, như vậy mới hết gốc mê, hết mê mới hết khổ. Chúng ta không gan, không dám nhìn thẳng, không dám bỏ thì không bao giờ được an lạc giải thoát.

Khổ đau không phải từ đâu đem đến, mà tại chúng ta không sáng suốt, không có trí tuệ. Có người nghe Phật dạy đời là khổ, thân là vô thường, v.v… cho rằng Phật bi quan. Nhưng không ngờ thấy được lẽ thật đó sẽ cởi mở biết bao nhiêu việc, không còn đeo đẳng đau khổ nữa. Do không biết không nhận như vậy nên người thế gian đau khổ vô cùng, hết đời này tới đời khác không lúc nào hết buồn hết lo.  

Chúng ta thử nghiệm lại trên thế gian này, từ người giàu cho tới người nghèo, có ai không khổ đâu, có ai sống toàn là vui đâu. Mỗi người khổ mỗi cách, có người khổ vì thiếu thốn đói rét, có người khổ vì côi quả, có người khổ vì gia đình không hạnh phúc… ai cũng khổ, không có ai vui trọn vẹn. Vậy mà Phật nói cuộc đời là khổ thì bảo đạo Phật bi quan. Rõ ràng con người luôn chạy trốn sự thật.

Chúng ta phải dám nhìn vào sự thật mới có thể can đảm tiến lên. Biết cuộc đời vô thường để ngày nào, giờ nào mình còn sống thì cố tu tập, dẹp những thói xấu. Chỉ nhớ mạng sống trong hơi thở là hết tham ngay. Nhớ thân này nhơ nhớp thì bớt ngã mạn, tự nhiên ta trở về cuộc sống chân thật của mình. Đó là người có trí tuệ sáng suốt.

Tu là rèn luyện trí tuệ cho được sáng suốt, được tốt đẹp, đó là điều tiên quyết. Thân này dầu sửa sang, lo lắng mấy nó cũng bại hoại, cũng chỉ là tấm thân hư thối thôi. Tất cả cái được đó đều là được để mất, chớ không phải được để còn mãi. Vậy mà chúng ta cứ cắm đầu lo thôi là lo, còn việc tẩy rửa gạn lọc cho tâm trong sáng, tốt đẹp thì ít quan tâm tới. Phần nhiều Phật tử đi chùa học Phật, chỉ muốn tu để đời sau sung sướng hơn, phước đức hơn, đẹp đẽ hơn, chớ không muốn thấy đúng lẽ thật, không muốn dứt si mê, giác ngộ giải thoát.

Trong nhà Thiền tu là gạn lọc nội tâm, giống như một khạp nước đục, chúng ta lóng xuống cho nó trong. Lóng lặng rồi thì nước trong, nhưng cặn bã vẫn còn dưới đáy khạp, nếu quậy lên thì chúng sẽ ngầu đục trở lại. Bây giờ muốn nó hoàn toàn trong, không có cặn cáu nữa thì phải lọc qua một khạp khác. Cũng vậy, tham sân si là cặn cáu, nó làm cho tâm trí mình mờ tối, bây giờ chúng ta phải lọc, phải gạn cho nó lắng xuống trước. Lắng xuống rồi phải lọc bỏ nó đi, lúc đó tâm mình mới trong sáng. Tâm hồn trong sáng tức không còn đau khổ nữa, còn tâm hồn tối tăm thì đau khổ không có ngày dứt được. Đó là điều hết sức thiết yếu.

Chúng ta có hai thứ tâm, tâm sanh diệt tùy duyên và tâm thanh tịnh hằng sáng không mất. Khi chúng ta nghĩ xấu, nghĩ ác thì tâm đó luôn thay đổi hay nguyên vẹn mãi như vậy? Thí dụ có người nói trái ý, mình giận ghét họ, đó là tâm xấu. Nhưng thời gian sau họ làm gì vừa ý, mình liền vui vẻ, thương mến họ. Đó là tâm sanh diệt tùy duyên. Duyên thuận thì nó tốt, nghịch thì nó xấu chớ không cố định. Đã là sanh diệt tùy duyên thì không phải thật mình. Như vậy không ai cả ngày giận hoài, cũng không ai cả ngày ghét hoài. Thương, ghét, buồn, giận đều tùy duyên lộn qua đảo lại, không cố định. Vừa giận đó rồi thương, vừa ghét đó rồi mến, đổi thay luôn.

Phật dạy phàm những gì do duyên hợp đều hư giả, vậy mà chúng ta chỉ sống với cái giả, bỏ quên cái thật. Cả ngày đem hết sức lực để lo lắng, gìn giữ cái thân tạm bợ này. Đến tâm tức tinh thần, chúng ta giữ phần hơn thua, phải quấy, tốt xấu, được mất cho đó là tâm mình. Tâm tôi nghĩ phải, tâm tôi nghĩ quấy, tâm tôi vui buồn, thương ghét… có rồi mất, không thường còn. Tâm không thật luôn sanh diệt như vậy mà bám vào đó chấp là mình, thành ra mất mình luôn. Có đáng thương không?

Phật bảo chúng sanh do ba nghiệp mà đi trong sanh tử luân hồi. Ba nghiệp là thân, miệng và ý. Khi ý nghĩ xấu thì miệng nói xấu, thân làm xấu nên nghiệp dẫn đi trong ba đường ác địa ngục, ngạ quỉ, súc sanh. Nếu ý nghĩ tốt, thì miệng nói phải, thân làm phải nên nghiệp dẫn đi trong ba đường lành trời, người, a-tu-la.

Như vậy chánh nhân tạo nghiệp là ý, tức những thứ buồn thương giận ghét của chúng ta. Tâm đó là chủ tạo nghiệp, muốn tu giải thoát sanh tử mà bám vào nó thì không bao giờ giải thoát được. Chỉ là phước báu hoặc tội nghiệp, dẫn đi trong đường lành hoặc đường dữ thôi.

Ban đầu, chúng ta tu thì tập bỏ những thứ xấu ác, sau đó đến các thứ tốt thiện cũng phải bỏ luôn. Nhưng thường không ai bỏ cái tốt cả, uổng lắm cho nên được sanh cõi lành, thành ra cũng quanh quẩn ở sanh tử thôi. Chúng ta chưa tìm ra cái thật mình, thì chưa thể được an vui vĩnh viễn. Cái thật đó Lục Tổ nói: *“Không nghĩ thiện, không nghĩ ác, cái gì là Bản lai diện mục của Thượng tọa Minh?”*. Vậy khi tâm hằng tri, hằng giác mà không có niệm thiện ác lôi cuốn, lúc đó mình đi đâu? Không tạo nghiệp là giải thoát sanh tử, còn đi đâu nữa.

Chúng ta ai cũng sẵn có cái không tạo nghiệp, không bị nghiệp dẫn mà không chịu nhận, cứ nhận cái tạo nghiệp, cái sanh tử là mình rồi khỏa lấp cái mình thật. Bản lai diện mục tức là mặt thật xưa nay của mình, nó bị khỏa lấp bởi niệm thiện, niệm ác. Chừng nào những niệm đó lặng sạch thì mặt thật xưa nay hiện tiền. Vậy lúc niệm thiện ác chưa lặng sạch thì mặt thật kia ở đâu?

Bình thường chúng ta thấy biết tất cả mà không khởi niệm phân biệt, cái thấy biết đó không động. Nó luôn hiện tiền nhưng mình vừa khởi phân biệt thì nó khuất đi, chớ không phải mất, không phải thiếu vắng bao giờ. Chúng ta chạy theo niệm sanh diệt thì cái chân thật ẩn khuất, khi nào dừng lặng các niệm sanh diệt thì nó hiện bày. Cho nên các Thiền sư thường nói: *“Tại ông không nhận, chớ không phải không có”*.

Có ai không thấy, không nghe, không biết. Thấy, nghe, cảm giác biết hết nhưng ở giai đoạn đầu chưa khởi niệm phân biệt tốt xấu, hơn thua thì cái biết chân thật không sanh diệt. Khi tâm khởi niệm phân biệt là chuyển sang cái biết sanh diệt rồi. Thấy cứ thấy, nghe cứ nghe, có người nào thiếu đâu, nhưng ai cũng than kiếm không ra Phật tánh. Sự thật thì nó luôn hiện tiền ngay nơi chúng ta, đâu cần phải tìm kiếm ở đâu.

Khi chúng ta ngồi Thiền không có hôn trầm, những niệm nghĩ tưởng lăng xăng lặng xuống, dấy lên ta thấy biết rõ ràng tức là vẫn tỉnh vẫn biết như thường, cái biết đó nó không động không tịnh, không sanh diệt như các niệm vọng tưởng. Đó là mình đã có sẵn cái không động, không sanh diệt rồi. Chỉ cần ta không chạy theo cái động, thì trở về được với cái không động, đó là giải thoát sanh tử. Vì cái động sanh diệt tạo nghiệp đi trong sanh tử, còn cái không động, không sanh diệt thì không tạo nghiệp sanh tử. Cho nên sống được với cái không động là giải thoát sanh tử, cần gì tìm kiếm ở đâu xa. Trong nhà Thiền nói: *“Cỡi trâu đi tìm trâu”, “Cõng Phật mà đi tìm Phật”* là thế.

Vì vậy trong kinh Pháp Hoa, chàng cùng tử say sưa được bạn tặng cho hòn ngọc quí bỏ trong túi áo, anh lo say lang thang hoài nên quên mất mình có hòn ngọc. Đến khi được bạn chỉ thẳng mới nhớ lại mình có hòn ngọc trong túi áo từ lâu. Đó là chỉ cho tất cả chúng ta có cái chân thật quí báu mà không nhớ không nhận, cứ chạy theo cái tạm bợ cái giả dối hoài.

Tôi nhắc lại chúng ta tu là dẹp bớt những tâm niệm xấu ác, giữ những tâm niệm hiền lành tốt đẹp, đó là chặng thứ nhất. Kế đến tất cả niệm sanh diệt dù tốt hay xấu cũng đều bỏ hết, đừng luyến tiếc mà phải sống với cái chân thật không sanh không diệt, không hình tướng của mình. Như vậy tu là làm một việc cao siêu phi thường, chớ không phải tầm thường.

Chúng ta hiện giờ đang sống đang tu, mà chỉ mong muốn những cái nho nhỏ, như đời sau có phước hơn đời này, giàu sang sung sướng hơn đời này. Nhưng ta quên rằng dù được như vậy chắc gì đã hạnh phúc, vì có thân là có khổ. Có ai khỏi bệnh, khỏi chết đâu. Bệnh chết là khổ hay vui? Cái án đó đã sẵn cho mọi người. Ai rồi cũng phải đi tới già, tới bệnh, tới chết. Đã có án tử hình thì cuộc sống là vui hay là khổ? Vậy mà chúng ta cứ buông trôi, ngày mai ra sao mặc nó, bây giờ cứ cười cứ vui. Người không thấy xa biết rõ, là người không sáng suốt, không có trí tuệ.

Người tu có hai trường hợp, thứ nhất nhớ cuộc đời vô thường rồi buồn rầu chán nản không muốn làm gì. Như vậy chưa phải khéo tu. Thứ hai cũng biết vô thường nhưng vui vẻ, vì biết đó là luật chung của mọi người, không ai tránh được. Muốn tránh phải tự tìm một lối đi khác, chớ không thể ngồi buồn mà tránh được. Đây là người khéo tu. Cho nên chúng ta học Phật, biết đời là khổ nhưng mình vẫn vui. Vì trong cái khổ sanh diệt có cái chân thật không sanh diệt, luôn hằng hữu bên mình. Thế thì ta dại gì sống với cái sanh diệt, bỏ mất cái không sanh diệt cho phải khổ. Vì vậy đạo Phật không những không bi quan, mà còn lạc quan yêu đời nữa là khác.

Người biết tu thì biết sửa đổi sai lầm, luôn tỉnh giác và đánh thức mọi người cùng tỉnh giác, như vậy cuộc sống mới có giá trị. Nếu cả cuộc đời mấy chục năm, sống trong u tối thì thật vô nghĩa. Đời này qua đời khác, cứ chồng chập như vậy thì khổ não biết bao nhiêu. Lại, Phật bảo được thân người là khó, như rùa trăm năm mới gặp bọng cây giữa biển khơi.

Tuy thân này hư tạm, nhưng nếu chúng ta biết lợi dụng nó, để tu hành thì sẽ vượt thoát khỏi dòng sanh tử, sống với Pháp thân chân thật, muôn đời không sanh diệt. Giống như rùa mù nương bọng cây được vào bờ. Ngày nào sống là một ngày thức tỉnh, ngày nào sống là một ngày an lạc. Khi không còn nghĩ chuyện tốt xấu, phải quấy ta sẽ thấy vui. Vui thế nào? Tất cả niệm hơn thua phải quấy không khởi thì gương mặt mình lúc nào cũng tươi sáng, đó là cái vui chân thật. Còn vui hỉ hạ là cái vui của thế gian, không chân thật.

Nhưng người đời luôn tìm vui trong cái hơn thua được mất. Ví dụ người ta tổ chức đá bóng, đội nào thắng mình vỗ tay cười vui, trong khi đội thua rất đau khổ. Vui trong sự đau khổ của người khác, thì cái vui đó không thật vui. Người thắng thì vui, người thua thì khổ. Như vậy vui của thế gian chỉ là cái vui tương đối, vui khổ theo nhau, chớ không hoàn toàn vui.

Chỉ khi tâm chúng ta dứt các niệm phải quấy, hơn thua v.v… lặng lẽ thanh tịnh mới thật là vui. Nhưng có nhiều người, nhất là tuổi học sinh sinh viên, nói tu cái gì cũng bỏ hết thành ra ngu ngốc. Phải nhét vô đầu thật nhiều mới có kiến thức rộng, mới là người hiểu biết. Thật ra không phải vậy, người tu bỏ những niệm lăng xăng tạp loạn, để tập trung vào một việc thì sáng thêm chớ ngu sao được. Ví dụ khi học cứ một tâm chuyên chú vào việc học, không nhớ nghĩ viển vông chuyện nọ chuyện kia, thì càng học càng thông minh sáng suốt hơn, chớ ngu sao được. Khi làm việc cũng vậy, buông hết chuyện tạp, tập trung vào công việc thì kết quả sẽ tốt hơn.

Thời nay, người ta muốn nhớ nhiều quá thành ra quên hết. Bởi vì nhét đầy óc ách trong não, khiến nó mỏi mệt nên nó không thể tiếp nhận được gì cả. Rồi rốt cuộc càng muốn nhớ thì càng quên. Trong khi người càng buông lại càng nhớ, nhớ một cách tự nhiên trong sáng nên mọi việc hiện ra rất rõ ràng phân minh.

Chúng ta thử nghiệm xem khi nào đầu mình rối nuồi việc này việc kia, lúc đó mình cứ quên đầu quên đuôi. Khi ấy, chỉ cần ngồi thiền một chút ta liền nhớ trở lại. Vì vậy nhiều người mới tập tu thiền nói ở ngoài không nhớ gì hết, đến lúc ngồi thiền, lại nhớ đủ chuyện. Như vậy có lỗi không? Tôi giải thích đó không phải tội lỗi, vì lúc ở ngoài việc này việc kia khỏa lấp nên ta không nhớ, khi ngồi thiền tâm yên định, nó trồi lên nên ta thấy đủ chuyện. Thấy thì thấy, biết nó không thật liền buông thì không có lỗi gì cả, quan trọng là đừng chạy theo nó.

Như đức Phật khi ngồi thiền dưới cội bồ-đề, chứng được Túc mạng minh, Ngài nhớ lại chuyện vô số kiếp về trước như nhớ chuyện hôm qua. Khi buông bỏ hết, ta tưởng như quên nhưng trái lại nhớ rõ hơn. Còn ráng nhớ rốt cuộc nhớ không bao nhiêu. Hiểu như vậy mới thấy tâm mình là kho chứa, nên nhà Phật gọi là Tàng thức. Cái kho ấy chứa tất cả chủng tử lành dữ của mình, nếu ta loại hết những lăng xăng tạp loạn thì kho Tàng thức đó biến thành Như Lai tàng. Kho thức phân biệt mà sạch hết những niệm phân biệt thì trở thành kho Như Lai, kho Phật chớ không phải hết trơn.

Vì vậy khi tu chúng ta buông bỏ hết, nhưng đừng tưởng mất tất cả. Không phải vậy, ngồi yên định lại, muốn nhớ thì nhớ rõ ràng, không muốn nhớ thì thôi. Đó là người đã làm chủ được mình và các pháp, sống tùy duyên an vui tự tại, không bị các pháp nhiễu loạn. Nên những người tu càng cao càng hay, thì càng ít chú ý tới mọi thứ, nhưng cần thiết thì các ngài thấy biết rõ ràng, không nghi ngờ. Còn chúng ta những thứ cần biết thì không biết, những thứ không cần biết lại biết. Vì vậy chúng ta khác các ngài.

Tóm lại, hôm nay tôi muốn nhắc tất cả nhớ điều này: Việc gì đáng lo thì mình lo, việc gì không đáng lo thì buông bỏ bớt. Người khéo tu lúc nào cũng nhớ quay lại mình, nhận ra và sống được với Tâm chân thật, ngoài ra tất cả đều vô thường hư ảo, không cần chú tâm làm gì.

Người tu không sợ ngu, chỉ sợ không tu được thôi. Tu được tức là giác ngộ, mà đã giác ngộ tức là trí tuệ viên mãn, nói gì là ngu với không ngu!

