# Đạo Phật là đạo yêu đời {- #dao-phat-la-dao-yeu-doi}

<div class="align-right">
*Giảng tại Virginia, Hoa Kỳ*  
*Tháng 11, 2000*
</div>

Đề tài chúng tôi giảng hôm nay *"Đạo Phật là đạo yêu đời"*. Lâu nay người ta ngỡ rằng đạo Phật là đạo yếm thế. Giờ đây chúng tôi nói đạo Phật là đạo yêu đời chắc quí vị không khỏi ngạc nhiên. Chúng tôi sẽ tuần tự giải thích tinh thần yêu đời của đạo Phật.

Theo cái nhìn thông thường của người đời, đạo Phật dường như yếm thế. Tại sao? Vì trong kinh Tứ Diệu Đế, đế đầu tiên là Khổ đế. Phật nói khổ trước nhất, sau đó còn nói thêm thân này vô thường, bất tịnh, giả dối v.v... Nói như thế tức rõ ràng đạo Phật là chán đời. Nhưng thật ra ấy là do cái nhìn thiển cận mà thôi.

Đức Phật có điểm đặc biệt, khi chỉ một phương pháp nào trước Ngài nói quả, sau mới chỉ nhân. Từ đó Ngài mới dạy phương pháp tiêu diệt nhân để hết quả khổ. Phật nói thân này là khổ, là nói trên quả. Khổ từ đâu ra? Từ tham, sân, si, mạn, nghi, ác kiến v.v… Biết được lý do tức là biết được nhân, sau đó phải tìm cách tiêu diệt nhân ấy. Cho nên Khổ đế là quả, Tập đế là nhân. Diệt sạch nhân khổ rồi thì được quả vui gọi là Diệt đế. Muốn diệt nhân không phải ngẫu nhiên tự diệt, mà có phương pháp tu hành gọi là Đạo đế.

Ví như bác sĩ thấy bệnh nhân đau nặng, nhưng người ấy chưa biết nên trước bác sĩ giải thích, bệnh này trầm trọng lắm cần phải uống thuốc trị mới lành. Bệnh nhân nghe vậy sợ mới chịu điều trị. Sau đó bác sĩ hướng dẫn cách chữa trị, người đó nghe và làm theo lời dặn của bác sĩ nên lành bệnh.

Cũng vậy, ban đầu nghe nói bệnh trầm trọng chúng ta sợ, đó là khổ. Nhờ sợ mới hỏi cách chữa trị. Khi trị đã lành thì hết khổ, được an vui. Vì vậy đạo Phật nói khổ nhưng không phải cố định, nếu biết cách tiêu diệt nhân khổ thì quả khổ sẽ hết. Hết khổ tức là vui. Cho nên đạo Phật nói khổ không phải để cho chúng ta thở than, buồn thảm, mà nói khổ để chúng ta diệt khổ. Diệt khổ để được vui, vui thì yêu đời. Đó là ý nghĩa cao siêu của đạo Phật.

Như trong kinh có câu: *“Phật ái chúng sanh như mẫu ái tử”*. Tức là Phật thương chúng sanh như mẹ thương con. Mẹ thương con thì không bao giờ bỏ được. Không bỏ được nên phải tìm mọi cách để chỉ dạy, hướng dẫn sao cho con mình bớt khổ, đó là tinh thần từ bi của đức Phật. Có học Phật, mới thấy tình thương của Phật đối với chúng ta thật tràn trề lai láng. Tinh thần đó là yêu đời chớ không thể chán đời mà có được.

Trong kinh Hoa Nghiêm, chư Bồ-tát thường nói: *“Thấy chúng sanh khổ thì Bồ-tát khổ. Thấy chúng sanh vui thì Bồ-tát vui”*. Cái khổ, cái vui của chúng sanh là cái khổ, cái vui của Bồ-tát. Do đó lúc nào các ngài cũng muốn độ, muốn cứu chúng sanh, như vậy không phải thương yêu là gì?   

Trong kinh Lăng Nghiêm, sau khi A-nan ngộ được lý đạo rồi, Ngài phát nguyện rằng: *“Trong đời ác ngũ trược con xin vào trước. Còn có một chúng sanh chưa được Niết-bàn, con nguyện không vào Niết-bàn”*. Như vậy yêu đời hay chán đời? Từ đức Phật cho tới Bồ-tát, Thanh văn A-la-hán cũng phát nguyện mạnh mẽ như vậy. Vì lợi ích chúng sanh, các ngài không bao giờ tự an phận mình để chúng sanh phải chịu đau khổ. Tinh thần đó làm sao chán đời được?    

Trong kinh Pháp Hoa, chàng cùng tử rời bỏ cha mẹ đi lang thang, đói khổ. Khi muốn tìm trở về cha mẹ, vô tình lạc tới chỗ ông Trưởng giả. Tại đây, chàng xin làm một công việc nhỏ để kiếm sống qua ngày. Ông Trưởng giả nhận ra chàng là con mình nên bảo người gọi đến. Khi được gọi, cùng tử hoảng hốt bỏ chạy không dám trở về nữa. Người cha thương bảo gia nhân đuổi theo và đem về, nói sẽ thuê hốt phân. Nghe thế chàng mới hết sợ. Trưởng giả muốn gần con nên cởi áo bào sang trọng, mặc áo rách, cầm đồ hốt phân đến gần cùng tử. Gần gũi được rồi mới tìm cách dụ dỗ cho làm những công việc lớn hơn. Cuối cùng biết chàng không còn sợ hãi nữa, Trưởng giả mới nói thật ông là cha của chàng và trao lại gia tài cho chàng.

Trưởng giả chỉ cho đức Phật, chàng cùng tử chỉ cho chúng ta. Vì thương con nên từ ngôi vị an lạc, Trưởng giả phải xuống hầm phân để gần gũi và dìu dắt con. Chư Phật cùng các vị Bồ-tát đều như thế, hết lòng hết dạ thương xót chúng sanh. Tinh thần đó có phải yêu đời không?  Đó là một lẽ thật không thể phủ nhận được.

Người đời mới nhìn thấy cuộc sống như lạc quan vui thích. Nhưng khi gặp hoàn cảnh trái ý, liền muốn tự tử, hoặc chạy trốn cuộc đời bằng nhiều cách sa đọa hư hỏng. Nếu lạc quan tại sao phải tự tử? Tự tử có phải trốn đời không, đã trốn đời thì đâu còn yêu đời nữa. Cho nên Phật tử tu theo đạo Phật không có quyền tự tử. Tại sao? Trong kinh Tứ Thập Nhị Chương, đức Phật dạy rất rõ, những người gặp hoàn cảnh khó xử, buồn nản tự tử, chẳng những không hết khổ mà còn chuốc khổ nhiều hơn nữa.

Thí như con trâu bị kéo cày, nó thấy cái ách là tai họa của nó. Mỗi khi để ách lên vai là nó khổ, cho nên nó tìm cách phá hoại cái ách đó, như lấy sừng quật cho gãy ách. Nhưng nó không ngờ ách cũ gãy rồi, ông chủ sẽ làm cái ách mới tốt hơn, chắc hơn. Con trâu muốn hết khổ quật cho gãy ách, đâu ngờ lại mang cái ách mới còn khổ hơn.

Cũng vậy, Phật dạy tất cả chúng ta sanh trong cõi đời này, gặp những cảnh vui tươi sung sướng hoặc đau khổ. Khi khổ quá chúng ta tưởng chết đi cho hết khổ, cũng giống như con trâu kia vậy. Người sợ thân này khổ, chịu không nổi nên muốn tự tử. Nhưng không ngờ tự tử rồi, mang thân khác còn khổ hơn, lâu dài hơn.

Chúng ta không chạy trốn đi đâu được, nếu nghiệp ác của mình chưa hết, cũng như con trâu không thể trốn cái ách khi nghiệp trâu vẫn còn. Chừng nào nghiệp trâu hết thì hết ách, còn mang thân trâu thì phải mang ách, không sao tránh khỏi. Chúng ta cũng vậy còn mang thân nghiệp báo, ân oán chưa hết mà muốn giải quyết bằng cách chạy trốn thì không bao giờ được.

Cho nên Phật dạy người Phật tử sống trong cảnh vui sướng cũng nhớ làm lành, đừng tạo nghiệp ác. Ở trong cảnh khổ cực nên biết rõ rằng, khổ này không phải bỗng dưng tự đến với mình mà do nghiệp ác đã tích lũy đời trước, ngày nay phải chịu. Nghiệp là mối nợ, nợ đến mà chạy trốn không chịu trả thì chừng nào hết nợ? Ở đây thiếu nợ trốn qua chỗ khác, nếu ở đó người ta gặp lại cũng đòi như thường. Như vậy chỉ trả hết nợ, thì mới được an lành.

Hiểu thế, chúng ta có thân này trong cảnh vui thì sống theo cảnh vui, trong cảnh khổ thì chấp nhận trả nợ nần của cảnh khổ. Nợ nần trả xong thì chúng ta sẽ hết khổ. Biết rõ như vậy sẽ không còn gì để lo sợ nữa. Chấp nhận trả hết nợ thì hết khổ, còn chưa hết nợ mà trốn thì không được. Như vậy đạo Phật dạy chúng ta chán đờihay yêu đời? Dù đời có cay đắng mấy cũng ráng chịu, không chạy trốn, vậy là quá lạc quan quá yêu đời rồi.

Trong kinh A-hàm, đức Phật dạy được thân này rất khó. *“Thiên niên thiết thọ khai hoa dị, nhất thất nhân thân vạn kiếp nan”*, nghĩa là ngàn năm cây sắt mới trổ bông còn dễ, một khi mất thân này rồi, được trở lại làm người rất khó. Như vậy được làm người là tốt, tại sao lại đi hủy hoại, thật hết sức dại khờ. Vì vậy Phật dạy chúng ta phải quí tiếc thân này, biết mượn nó làm phương tiện tu hành, lợi ích cho chúng sanh chớ không nên hủy hoại nó.

Phật ví dụ như con rùa mù ở giữa biển khơi, một trăm năm nó mới trồi đầu lên một lần. Trên mặt biển có bọng cây nổi tùy theo gió đẩy đưa. Như vậy không biết bao giờ con rùa mù trồi lên mới gặp được bọng cây, chuyện ấy nếu có thật là hi hữu. Phật nói cũng vậy, mất thân này được trở lại làm người cũng khó như con rùa mù tìm gặp bọng cây giữa biển cả. Thế mà chúng ta được thân này lại xem thường, không cố gắng duy trì gìn giữ cho nó khoẻ mạnh, để tu hành và làm lợi ích cho mọi người. Thái độ hủy hoại thân này thật là dại khờ lắm vậy.

Phật dạy tu Nhân thừa Phật giáo là giữ năm giới: không sát sanh, không trộm cướp, không tà dâm, không nói dối, không uống rượu mạnh và dùng các chất nghiện như xì ke ma túy v.v… Giữ đủ năm giới này, sau khi thân hoại mạng chung sẽ được trở lại làm người. Thiếu một cũng không được. Chúng ta thử kiểm lại xem mình có xứng đáng làm người chưa? Nếu chưa thì phải ráng tu cho xứng đáng.

Chúng ta hay xem thường những việc lành, lại nghĩ làm ác qua rồi thì mất, không ngờ đó là tai họa hại mình về sau. Nên người biết tu rất sợ một lời nói ác, một hành động ác, luôn bảo vệ giá trị tu hành của mình, không để cho tham sân si làm chủ, dẫn đi trong ba đường ác địa ngục, ngạ quỉ, súc sanh.

Cũng trong kinh A-hàm, Phật dạy rằng:

> Bị thiêu đốt trong địa ngục chưa phải là khổ, bị làm loài quỉ đói lang thang chưa phải là khổ, bị mang lông đội sừng làm trâu bò kéo xe, kéo cày chưa phải là khổ, chỉ những kẻ si mê không biết lối đi mới là khổ.

Như vậy Phật đánh giá cái khổ không phải ở trong cảnh địa ngục, ngạ quỉ, súc sanh mới thật là thật khổ, mà si mê mới  là gốc khổ.

Tại sao si mê là gốc khổ? Vì khi si mê rồi chúng ta tạo nghiệp, nếu nghiệp ác thì phải đi trong đường dữ không biết tới bao giờ cùng. Ở địa ngục hết tội được lên, ở ngạ quỉ hết nghiệp được ra, súc sanh mãn kiếp được thoát, còn si mê dẫn mình liên miên trong sanh tử không có ngày ra khỏi. Nên đạo Phật cho si mê là cái đáng sợ hơn hết. Nhưng thường chúng ta chỉ sợ địa ngục, ngạ quỉ, mà không sợ si mê. Cái đáng sợ thì không sợ, cái không đáng sợ lại sợ.

Si mê dẫn mình muôn kiếp trong luân hồi, còn nợ nần trong các đường trả hết thì có ngày ta khỏi. Vậy si mê rất nguy hiểm, đáng sợ nhất. Cho nên nói si mê là gốc khổ. Người tu theo đạo Phật phải phá trừ gốc si mê trước tiên.

Phật dạy:

> Các ngươi phải tự thắp đuốc lên mà đi, thắp lên với chánh pháp.

Thắp đuốc lên tức là thắp sáng ngọn đuốc trí tuệ. Nhưng làm sao để thắp? *“Thắp lên với chánh pháp”*. Người con Phật phải hiểu đạo lý chân chánh đó. Hiểu được rồi, áp dụng tu hành chúng ta mới thoát si mê. Như trong Mười hai nhân duyên, vô minh là đầu. Vô minh tức si mê. Si mê là nhân dẫn chúng ta đi trong luân hồi không cùng. Vì vậy muốn phá si mê phải dùng trí tuệ. Cũng như trong nhà tối, muốn hết tối phải thắp đèn.

Si mê chỉ đáng sợ nếu mình cứ để cho nó hoành hành tự do. Ngược lại, si mê không đáng sợ nếu mình biết dùng trí tuệ diệt trừ nó. Cũng như trong nhà tối, nếu không thắp đèn chúng ta sẽ va đầu này, chạm đầu kia rất khổ. Nhưng khi thắp đèn lên, trong nhà liền sáng. Tối thì khổ, sáng thì an vui. Đạo Phật lấy giác ngộ làm trọng tâm tu hành. Người học Phật, tu Phật mà không giác ngộ thì không biết bao giờ thoát khỏi si mê. Không thoát khỏi si mê tức là ôm vô minh để muôn kiếp chịu khổ. Cho nên ai đến với đạo Phật cũng đều phải cố gắng mở sáng con mắt trí tuệ của mình thoát khỏi si mê.

Mở sáng mắt trí tuệ bằng cách nào? Bởi trí tuệ có hai: trí tuệ xuất thế và trí tuệ thế gian. Người thế gian từ không biết gì, do học hành lần lần tiến lên mỗi ngày mỗi giỏi, gọi là người có trí tuệ. Trí tuệ đó nhà Phật gọi là trí tuệ thế gian, nằm trong sanh diệt đau khổ. Còn trí tuệ của Phật, trí tuệ của bậc giác ngộ là trí tuệ xuất thế gian. Trí tuệ này có công năng đưa chúng ta đến chỗ thoát khổ, không còn bị lôi kéo, dính mắc trong sanh tử luân hồi nữa.

Kinh Kim Cang có câu: *“Phàm sở hữu tướng giai thị hư vọng, nhược kiến chư tướng phi tướng tức kiến Như Lai”*, nghĩa là phàm những gì có tướng đều là hư giả, nếu thấy các tướng không phải tướng là thấy được Phật. Thiền sư Duy Tín đời nhà Tống Trung Quốc nói: *“Khi chưa gặp thiện hữu tri thức, tôi thấy núi sông là núi sông. Khi gặp thiện hữu tri thức rồi, tôi thấy núi sông không phải là núi sông. Đến nay qua ba mươi năm, tôi lại thấy núi sông là núi sông”*. Những câu nói như vậy mới nghe thật khó hiểu, nhưng chính thật nó thấu đáo tột cùng.

Trước tôi giải thích câu trong kinh Kim Cang. Phàm cái gì có tướng, có hình thức Phật nói đều là hư dối. Người nào thấy các tướng đó, không chấp nó là thật, đó là người thấy được Phật. Đơn giản làm sao! Như vậy thấy Phật khó hay dễ? Nếu mình đừng chấp tướng là thật thì thấy Phật dễ vô cùng. Còn chấp tướng là thật thì khó vô cùng.

Như cái đồng hồ là thật hay giả? Nếu nói giả, có người lượm bỏ túi thì sao? Cho nên nói thì dễ nhưng thực hành rất khó. Phân tích đồng hồ, từng bộ phận rã ra, chúng ta thấy không có đồng hồ. Nhưng nếu ráp các bộ phận ấy lại đầy đủ thì có đồng hồ. Như vậy đồng hồ là thật hay là giả?    Trên lý ta nói nó giả, nhưng trên sự mất nó chúng ta la. Như vậy mình vẫn còn mắc mứu trong đó, chưa thấy đúng hoàn toàn lẽ thật.

Đồng hồ dưới con mắt của Phật là do nhân duyên hợp lại thành, cái gì do nhân duyên hợp lại thì không thật. Nếu thật thì nó nguyên vẹn, không thể tách ra từng phần được. Nhưng ta mở ra từng phần, nó không còn bóng dáng của đồng hồ nữa, làm sao nói thật được. Tuy nhiên nói không thật thì dễ, nhưng động tới đồng hồ thấy không thật là dễ hay khó? Đó là sự, chúng ta thấm nhuần ở trong tâm lâu rồi.

Qua đó đủ thấy chúng ta mê lầm như thế nào. Nghe Phật dạy thấy dễ hiểu, nhưng chạm sự thật mới biết mình chưa tỉnh chút nào hết. Đó là chỉ nói những sự vật nhẹ nhẹ bên ngoài thôi, chưa nói đến thân này. Nếu như có ai đó chỉ mặt mình nói *“anh này ngu quá”*, chừng đó biết liền. Thân đã giả thì người ta nói ngu có gì quan trọng. Thế mà trên thực tế, nghe như vậy là nổi sân si với nhau liền.

Xét lại người ta nói mình ngu cũng phải thôi. Nếu chúng ta chấp nhận *“tôi ngu”*, đó là biết nhận sự thật. Bởi lâu nay chúng ta cứ ảo tưởng mình là số một, là hơn thiên hạ. Nhưng sự thật mình chưa ra gì hết. Trên thế gian có muôn triệu ức việc, muôn triệu ức nghề, mà chúng ta biết được chừng bao nhiêu? Giỏi lắm vài việc trong sở trường của mình thôi, chớ đâu có biết hết. Những thứ không biết thì gọi khôn sao được. Vậy mà nói ngu không chịu.

Chúng ta sống bằng ảo tưởng nhiều hơn sự thật. Cho nên người học Phật phải can đảm nhận chân lẽ thật, không nên ảo tưởng. Sống trong ảo tưởng là sống trong si mê, đã si mê thì tất cả ý nghĩ và việc làm đều sai lầm, hậu quả phải chuốc lấy đau khổ là điều không thể tránh khỏi. Còn nhiều si mê tức là còn nhiều đau khổ. Cho nên tu thì phải giảm bớt si mê. Giảm bằng cách nào?    

Si mê có hai: Một chấp ngoại cảnh là thật. Hai chấp thân tâm mình là thật. Như đồng hồ, bàn ghế, nhà cửa nhẫn đến chim muông các cảnh đều thuộc về ngoại cảnh. Tất cả cảnh bên ngoài đều là duyên hợp không có thật. Không thật mà mình chấp thật, đó là si mê, thấy không đúng chân lý. Còn không thật biết không thật, đó là trí tuệ sáng suốt. Người sống đạo phải tập mỗi ngày, mỗi ngày sống bằng trí tuệ chân thật.

Thiền sư Duy Tín, ban đầu Ngài thấy núi sông là núi sông, giống như chúng ta lúc mê thấy núi sông là núi sông thật. Khi gặp thiện hữu tri thức chỉ dạy rõ ràng, Ngài thấy núi sông không phải là núi sông, vì biết rõ nó do duyên hợp giả có nên không thật. Qua ba mươi năm quán chiếu như vậy, tâm hết si mê, chừng đó Ngài thấy núi sông là núi sông. Bấy giờ, vì tâm thanh tịnh nhìn bằng trực giác, không qua cái nhìn mê chấp của phàm phu, cũng không qua trình tự quán chiếu của Thanh văn, Duyên giác hay Bồ-tát.

Chúng ta nghe thế, cũng không chịu quán chiếu gì hết, mà không biết mình tu tới đâu. Nghe người ta nói thật liền hưởng ứng theo, rồi thêm chuyện này chuyện kia, phê phán hay dở đủ thứ. Cho nên trên đường tu, trước cần phải dùng trí tuệ quán chiếu để thấy đúng như thật. Nhờ trí tuệ, cái gì giả ta biết giả, cái gì thật ta biết thật, không lầm đó là giác ngộ. Nên đức Phật nói nếu biết các tướng không phải tướng tức là thấy Phật.

Chúng ta kiểm lại tất cả cảnh bên ngoài có gì không phải do duyên hợÏp? Đã duyên hợp tạm có rồi tan, không thật. Không thật mà tưởng là thật ấy là si mê. Thứ si mê này đậm lắm, nó dẫn chúng ta đi trong luân hồi, không có ngày dừng. Muốn hết si mê chúng ta phải thường quán chiếu, thường xét nét kỹ càng ngoại cảnh bên ngoài chẳng có gì thật hết. Đó là nói về phần ngoại cảnh.

Kế đến, thân thiết với chúng ta nhất là thân và tâm. Thân của chúng ta có thật không? Ai cũng nói không, nhưng tôi chưa dám tin. Vì sao? Vì trên miệng thì nói không thật nhưng ra đường gặp việc liền thành thật hết. Đó là một lẽ thật.

Đức Phật dạy thân chúng ta được bởi kết hợp rất nhiều phần. Nói tổng quát gồm bốn phần: đất, nước, gió, lửa, bốn phần đó là gốc của thân này. Chất cứng là đất, chất ướt là nước, chất động là gió, chất ấm là lửa. Thiếu một trong bốn thứ đó thì thân này không còn. Trên cơ bản bốn thứ đó tụ hợp lại thành thân, nhưng còn phải bồi bổ, nuôi dưỡng nó mỗi ngày nữa.

Như hiện tại lỗ mũi chúng ta đang làm gì? Đang thở. Thở nghĩa là sao? Mượn không khí ở ngoài đem vô, rồi trả ra; mượn trả mượn trả liên tục như vậy gọi là thở. Nói ngồi chơi chớ có chơi đâu, cứ mượn trả mượn trả không dừng. Nếu trả rồi mà làm biếng không mượn nữa thì chết mất. Lát mượn tách nước, mượn rồi trả. Lát mượn ổ bánh mì hoặc chén cơm, mượn rồi trả. Chỉ có mượn trả mà nhiều khi không chịu bình dị, còn muốn cầu kỳ nữa chứ. Nước cạn thì mượn nước, nước gì cũng được, phải nước này nước nọ mới chịu. Đất hết thì mượn đất, đất nào cũng được, nhưng phải đất có mùi vị hấp dẫn. Thành ra chúng ta khổ, khổ vì cầu kỳ. Chúng ta sống không đơn giản, vì mượn trả mà không biết thật mượn trả, cứ nghĩ mình ăn, mình uống mà không ngờ mình đang mượn trả.

Như vậy kiểm lại mỗi ngày chúng ta sống bằng sự mượn trả, mượn trả. Khi cần mượn được mượn, khi cần trả được trả, đó là tốt. Mượn trả suôn sẻ là hạnh phúc. Nếu mượn trả không suôn sẻ là mất hạnh phúc liền. Nên giá trị của con người, nói thẳng ra chỉ là sự mượn trả mà thôi. Vậy mà chúng ta lại cho cái ngã này là trên thiên hạ, là số một, nói động tới thì không được.

Quí vị thấy, thân này khi mượn thức ăn đem vô, tích lũy một ngày rồi tuôn ra. Thời gian tích lũy đó nó biến chất thành thứ này thứ nọ, thì mùi vị ra sao? Vậy mà ai nói anh này hôi quá liền giận ngay. Rõ ràng chúng ta sống bằng ảo tưởng, không có lẽ thật. Cái đãy da hôi thối, mà không chịu nhìn nhận, phải khen mới được. Rõ ràng chúng ta từ chối sự thật, nên không thấy được chân lý, sống bằng tưởng tượng. Sống bằng tưởng tượng là sống bằng si mê, không có lẽ thật. Đó là nói về chấp thân.

Kế đến nói về chấp tâm. Tâm chúng ta có thật không? Vấn đề này quan trọng vô cùng. Khi quí vị giận ai thì nói tôi giận, buồn ai nói tôi buồn. Buồn thương giận ghét, cái nào cũng tôi hết. Như vậy cái tôi đó có thật không? Ví dụ mình đang giận ai trong nhà, bất thần thấy người bạn tri kỷ ở xa về, mừng quá quên giận, nên cái giận tan mất. Như vậy cái giận có thật không? Không.

Lâu nay chúng ta cứ ngỡ rằng buồn, thương giận, ghét là tâm mình. Ai nói trái ý hoặc làm trái ý mình thì không chịu nổi. Chính đó là cái khổ của chúng ta. Sống trong gia đình mà người chồng nghĩ khác, người vợ nghĩ khác thì sẽ thế nào? Sẽ gây gổ, có khi dẫn đến chia tay. Trong kinh A-hàm, Phật dạy một câu hết sức chí lý: *“Người biết tôn trọng chân lý là khi suy nghĩ vấn đề gì, thì bảo "đây là suy nghĩ của tôi", đừng nói rằng tôi suy nghĩ đúng.”* Nếu không thấy mình đúng thì đâu có cãi, dầu hai cái thấy khác nhau. Còn nếu thấy mình đúng người khác sai thì sẽ sanh cãi vã.

Như tôi ngồi trong thất, thấy phương Nam có cụm mây đen và có gió thổi qua, lát sau trời mưa. Ngày mai, vừa thấy cụm mây đen ở phương Nam, nhưng chưa biết gió phương nào, tôi vội kêu những người chung quanh đem đồ vô, lát nữa mưa. Nói như vậy là tôi nói theo kinh nghiệm hôm qua và xác định mình thấy đúng. Nếu ai không đem đồ vô, tôi giận vì nghĩ họ không nghe mình. Nhưng một lát, gió phương Nam không thổi mà phương Bắc thổi qua, đám mây đó tan, trời không mưa. Như vậy tôi đúng hay sai? Sai rồi. Nên biết kinh nghiệm của mình có khi đúng, có khi sai. Nếu ta cho đó là chân lý thì ai nói khác mình sẽ cự lại, như vậy có phải khổ không.

Người tu phải biết rõ tâm suy nghĩ của mình không thật. Nhiều khi Phật tử không nhận định kỹ, nghe nói tâm mà không biết tâm là gì. Nhà Phật giải thích rất rõ. Tâm là *“biết”*. Cái biết do suy nghĩ phân biệt là cái biết hư dối. Còn cái biết hiện tiền, không thiếu vắng lúc nào, cái biết đó là chân thật gọi là tâm. Thế nhưng đa số người lại chấp cái biết do suy nghĩ là tâm mình. Chấp như vậy nên cái biết chân thật bị ẩn khuất. Nhà Phật gọi cái biết chân thật sẵn có là Chân tâm, cái biết do suy nghĩ phân biệt là vọng tâm.

Như khi chúng ta rảnh rang nhàn hạ, ra cội cây ngồi chơi. Trong lòng không nghĩ, không tính toán gì hết. Lúc đó chim kêu nghe, gió thổi… chúng ta đều nhận biết rõ ràng, không lẫn lộn. Vậy mà chúng ta lại quên cái biết đó, chỉ nhớ cái biết sanh diệt liên miên do sự nghĩ tưởng vọng động của mình.

Chúng ta chấp thân hư giả làm thân mình, chấp tâm sanh diệt làm tâm mình thì chừng nào ra khỏi luân hồi? Nên nhớ mình tu là để lặng hết tâm sanh diệt thì Tâm chân thật mới hiện ra. Vì vậy các pháp môn trong đạo Phật cuối cùng đều gặp nhau chỗ cốt tâm được thanh tịnh.

Như người niệm Phật, muốn thấy đức Phật Di-đà hiện thân đón rước thì phải niệm được nhất tâm bất loạn, từ một ngày cho tới bảy ngày. Còn người tu thiền thì phải định tâm, tọa thiền quán chiếu thấy rõ các thứ nghĩ suy là hư huyễn, không theo. Khi chúng lặng hết thì Tâm chân thật hiện bày. Phật là giác, Tánh giác sẵn có trong mỗi chúng ta nên nói Phật tánh. Ai cũng có Phật tánh nhưng vì vọng tưởng phủ che, nên chúng ta không thấy.

Bây giờ niệm Phật để dứt sạch những phủ che đó thì Phật tánh hiện bày, chừng đó chúng ta thấy Phật. Phật Di-đà là Vô lượng thọ, Vô lượng quang tức tuổi thọ vô lượng, hào quang vô lượng. Tuổi thọ vô lượng thì Phật tánh của mình không sanh không diệt nên cũng vô lượng. Phật tánh là hằng giác hằng tri sáng suốt nên gọi là Vô lượng quang. Còn người tu Thiền phải dừng lặng vọng tưởng. Vọng tưởng dừng lặng rồi mới được định, được định thì hết niệm sanh diệt, gọi đó là Niết-bàn.

Trong kinh A-hàm, có nói thế này:

> Nếu người nào niệm Phật hay tu Thiền quán Tứ niệm xứ từ một ngày, hai ngày cho tới bảy ngày, tâm không di chuyển, không dao động thì người đó sẽ chứng từ Tam quả cho tới Tứ quả A-la-hán.

Chứng A-la-hán tức là chứng Niết-bàn. Như vậy vọng tâm lặng, thì Chân tâm hiện bày, không sanh không diệt. Khi đó tùy theo pháp môn tu mà chúng ta được vào Niết-bàn hay vãng sanh về cõi Cực lạc.

Trong nhà Thiền có ví dụ rất hay. Như chúng ta xuống hồ, múc nước đục đổ vào khạp. Nước đục nên đứng gần nhìn vào, chúng ta không thấy bóng của mình. Dần dần nước lóng xuống, cặn bã lặn hết thì nước trong. Như vậy nước trong đó mới có hay đã sẵn có. Sẵn có. Nhưng tại sao trước chúng ta không thấy? Tại vì cặn, vì bẩn nên không thấy. Muốn thấy chỉ cần cặn bẩn lắng xuống hết thì nước trong hiện ra.

Tâm chúng ta cũng vậy. Suy nghĩ vọng tưởng đều là cặn bã, những thứ đó lặng xuống rồi thì cái chân thật hiện bày, đó là Chân tâm, là Phật tánh.

Hiện giờ chúng ta mê lầm chấp thân tứ đại vay mượn là thật, chấp tâm suy nghĩ hư dối là thật. Do hai thứ chấp ấy mà quên mất Tâm chân thật luôn sẵn bên mình. Nên trong nhà Thiền thường dùng câu *“Cõng Phật đi tìm Phật”* hay *“Cỡi trâu tìm trâu”*. Mình có Phật sẵn mà không chịu nhận, chạy tìm chỗ này chỗ kia. Ngồi sẵn trên lưng trâu mà không biết, lại đi tìm trâu. Thật đáng thương!  

Tôi dẫn bài kệ trong kinh Niết-bàn, Phật dạy:

<div class="align-center">
> Chư hành vô thường  
> Thị sanh diệt pháp  
> Sanh diệt diệt dĩ  
> Tịch diệt vi lạc  
</div>

Tạm dịch:

<div class="align-center">
> Các hành vô thường  
> Là pháp sanh diệt  
> Sanh diệt diệt rồi  
> Tịch diệt là vui  
</div>

Các hành vô thường, biến đổi, là pháp sanh diệt. Nếu biết rõ pháp sanh diệt ấy rồi, không còn lầm lẫn chạy theo nó, tự nó sẽ tan biến. Nó tan biến tức diệt mất rồi, chừng ấy cái lặng lẽ còn lại gọi là tịch diệt, cái ấy là vui. Cái vui này không sanh không diệt, chân thật hiện tiền nên không bị vô thường làm biến đổi. Đây là cái vui cứu kính chân thật.

Như vậy đạo Phật dạy tu lạc quan hay bi quan? Lạc quan. Lạc quan vì tìm được cái vui chân thật. Tất cả thú vui của thế gian hiện giờ là cái vui giả dối, tạm bợ, vui trong đau khổ. Thí dụ như quí vị coi đá bóng thấy vui. Nhưng vui đó có lẫn khổ. Bên thắng thì vui, bên bại thì khổ. Vui trong cái khổ của người khác thì đâu phải thật vui. Vậy mà người ta thích lắm. Cũng ở quê mấy chú thanh niên thích coi đá gà. Hai con gà đá nhau đổ máu mà người ta vỗ tay kêu vui. Vui trong cái chết chóc của loài vật, cái vui đó có tốt không? Thậm chí có nhiều người coi đấu quyền anh. Anh A hạ được anh B nằm dài, người xem vỗ tay hoan nghênh. Đó là vui trong cái đau khổ của người khác. Vì vậy cái vui của thế gian không phải thật vui. Chỉ khi nào tâm sanh diệt lặng hết, tịch diệt hoàn toàn mới thật là vui.

Như vậy những cái vui trong đạo Phật là vui tốt đẹp, vui trong sự an lành của mọi người, chớ không phải vui trong sự đau khổ của kẻ khác. Nên đạo Phật là đạo từ bi. Chúng sanh khổ thì ta khổ, chúng sanh vui thì ta vui. Đó là niềm vui chân chánh của đạo Phật. Nếu làm cho người khác khổ mà mình vui, cái vui đó phàm tục, không phải niềm vui chân chánh tốt đẹp.

Đã là Phật tử thì chúng ta phải tập vui trong đạo chân chánh. Người đói chúng ta cho họ một ít cơm, họ vui chúng ta vui theo. Người buồn chúng ta dùng lời an ủi, họ bớt buồn được vui, chúng ta vui với họ. Những niềm vui đó tuy cũng tạm bợ, nhưng không có đau khổ kèm theo thì chúng ta nên thực hành. Còn những thứ vui trong nỗi khổ của kẻ khác, tuyệt đối chúng ta không làm.

Có người nói coi hát cải lương vui chớ đâu có khổ. Nếu vui tại sao đôi khi lại khóc. Cho nên nói đi coi cải lương cho vui, không ngờ đi khóc. Qua đó để thấy rằng, con người không tìm niềm vui thật, mà tìm niềm vui trong ảo tưởng. Chỉ có đến với đạo, tu hành chân chánh, chúng ta mới tìm được niềm vui thật.

Ví dụ gần nhất như khi quí vị ngồi niệm Phật hoặc ngồi thiền chừng năm mười phút, tâm lặng yên, thanh tịnh, không nghĩ không suy. Lúc  đó gương mặt quí vị rất tươi tắn, tuy không cười nhưng hiện rõ nét hoan hỉ an lạc từ bên trong. Ngược lại, quí vị ngồi chừng năm mười phút, lát nhớ giận người này, tức người kia v.v… thì gương mặt lát đỏ, lát xanh thấy đáng ghê sợ. Mới thấy rằng chúng ta biết tu, tâm lặng yên thanh tịnh thì có niềm vui chân thật. Còn vui trong đối đãi tạm bợ là vui trong cái khổ, chưa phải niềm vui chân thật.

Muốn tìm được niềm vui chân thật thì chúng ta phải theo sự hướng dẫn của chư Phật, Bồ-tát, các vị tu hành trước chỉ bảo. Nghe rồi ứng dụng tu hành, để nhận ra và sống được với lẽ thật sẵn có nơi mình, như thế mới mong được giải thoát an vui.

Tôi giảng tới đây, quí vị thấy đạo Phật là bi quan hay lạc quan, yêu đời? Nếu quí vị đồng ý đạo Phật lạc quan yêu đời là tôi đã thành công rồi.

