# Đường lối tu Thiền {- #duong-loi-tu-thien}
<div class="align-right">
*Giảng tại Tịnh xá Trung Tâm, 1998*
</div>

Đề tài chúng tôi muốn nói hôm nay là *"Đường lối tu Thiền"*. Muốn biết đường lối tu Thiền cần phải giản trạch các pháp Thiền. Pháp Thiền nào của Phật, pháp Thiền nào không phải của Phật. Pháp Thiền nào của hệ thống Nguyên thủy, pháp Thiền nào của hệ thống Phát triển v.v... để cho quí Sư có cái nhìn chính xác trong lúc tu hành. Chúng ta có đường lối cụ thể thì không sợ lạc đường, không sợ xảy ra những việc bất trắc trong lúc tu.

Chúng ta tu Thiền là thực hành theo đúng nguồn gốc của đạo Phật. Quí vị đọc sử thấy rõ ràng đức Phật tọa thiền bốn mươi chín ngày đêm dưới cội bồ-đề mà được giác ngộ. Sau khi giác ngộ, Ngài tuyên bố thành Phật. Như vậy đức Phật thành Phật gốc từ tu Thiền. Điều này không còn nghi ngờ gì nữa. Ngày nay chúng ta là con cháu trong nhà, dĩ nhiên phải học theo gương của Phật và đi theo con đường Phật đã đi, nên chúng ta cũng tu Thiền. Nhưng muốn tu Thiền chúng ta phải nhận định cho kỹ, pháp nào của Phật dạy để thực hành đúng theo con đường giác ngộ, chớ không lầm đường khác. Dù những đường khác có người cho là hay, là mầu nhiệm, chúng ta cũng không màng, chỉ tiến theo con đường mình đã chọn. Nên hôm nay chúng tôi sẽ trình bày đường lối tu Thiền thế nào đúng, thế nào sai cho tất cả chư Tăng nhận định đúng đắn hơn trên con đường tu hành của mình.

Tu Thiền có nhiều pháp mà ngày xưa chính tôi khi tu cũng rất khổ sở. Bởi vì thời của tôi nói tu Thiền nhưng người tu ít giản trạch, nên có những phái Thiền không phải của đạo Phật mà người ta vẫn đem ra tu. Như vậy tu theo Phật để cầu giác ngộ, để giải thoát sanh tử mà lại tu đường lối khác. Đã tu đường lối khác thì khi nhắm mắt sẽ đi lối khác, trái với bản nguyện ban sơ của mình. Vì vậy quí vị cần phải nhận định kỹ, Thiền nào của đạo Phật, Thiền nào không phải của đạo Phật. Trước tiên, tôi nói Thiền không phải của đạo Phật.

Một là Thiền chuyển luân xa. Tức là tưởng từ rún chạy lên đầu, vòng ra sau lưng rồi lại về rún, lên đầu. Chạy vòng tròn như vậy gọi là chuyển luân xa. Chuyển luân xa là pháp tu ở ngoài, không phải của đạo Phật.

Hai là Thiền xuất hồn. Xuất hồn là mở những khiếu huyệt của mình, phóng tinh thần *(hay gọi là hồn)* bay đi học đạo với những bậc thầy mà mình chưa từng biết; hoặc xuất hồn mong tìm gặp vị minh sư. Khi xuất hồn, không biết minh sư là ai, nên vị nào nói minh sư liền tin, người ta dạy cái gì cũng làm theo. Đó là họa lớn vô cùng, lớn ở hai mặt. Mặt thứ nhất là trong khi mở khiếu huyệt để xuất hồn, có người mở không khéo phát điên. Mặt thứ hai là khi mình xuất hồn tìm bậc minh sư, gặp ai xưng minh sư mình cũng nhận liền, không có cái nhìn giản trạch ai chánh, ai tà. Vì vậy dễ bị những vị thần linh đánh lừa, xưng là minh sư nhận mình làm đệ tử, mình liền đi theo. Như vậy đã lạc hướng mà mình không hay. Thiền này của ngoại đạo, không phải của đạo Phật.

Ba là Thiền thai tức. Nghĩa là hít vô tới đan điền nín lại mười phút, năm phút hay ba phút rồi thở ra. Lâu ngày bụng nó phì ra, gọi đó là thai, vì giống như phụ nữ có thai. Bụng lớn là do hơi thở nên gọi là tức. Vì vậy Thiền này được gọi là Thiền thai tức. Thiền này không phải là Thiền của đạo Phật.

Bốn là Thiền luyện tinh hóa khí, luyện khí hóa thần. Nhiều người trẻ tu thấy khổ về bệnh tinh khí quá, nên dùng tưởng đem tinh lên không cho xuống, để luyện thành thần khí. Đó là Thiền của những vị tu Tiên, chớ không phải Thiền của đạo Phật. Thiền này chỉ đưa đến kết quả sung sướng được bay đi, được thần thông v.v... chớ không giải thoát.

Năm là thiền Yoga, còn gọi là Du-già. Thiền này cũng có nhiều cách, khi ứng dụng tu phát tâm từ bi, thương yêu tất cả. Nhưng trọng tâm của Thiền này là luyện cho thân thể khỏe mạnh, mục đích trị bệnh nhiều hơn cầu giải thoát.

Phật dạy rằng: *“Nếu tu mà nghĩ giữ thân này được lâu dài là si định”*. Tại sao? Hồi tôi còn là Học tăng, có một cư sĩ tu Thiền theo lối luyện tinh hóa khí, luyện khí hóa thần. Lúc đó tôi bị bệnh sốt rét. Thấy tôi lên cơn trùm mền, ông cười nói: *“Tu gì bệnh hoạn hoài, tôi tu không có bệnh”*. Nghe nói tôi cũng ham, liền hỏi ông tu ra sao, ông nói tu theo pháp luyện tinh hóa khí, luyện khí hóa thần này sẽ giúp cho thân thể khỏe mạnh. Mỗi lần ông ngồi thiền đầu cứ lắc lư. Trong nhà Phật gọi là si Thiền.

Tại sao si? Vì thân này dưới con mắt đức Phật, nó là duyên hợp hư dối, vô thường sanh diệt. Vậy mà muốn giữ cái không thể giữ được, thì có phải si không? Quí vị thấy, nói tu Tiên sống hai ba trăm năm, nhưng bây giờ tìm khắp thế gian xem có ông Tiên nào không? Các ông đi đâu mất. Đi mất hay là chết? Cuối cùng rồi cũng chết, đâu có ai sống.

Phật dạy mình tu mà nghĩ được sống lâu, được mạnh khỏe là niệm không chân chánh, tâm si mê nên còn luyến ái thân. Cho nên người tu Phật, bệnh thì mặc bệnh. Bệnh tu theo bệnh, khỏe tu theo khỏe, đừng nghĩ mạnh khỏe tu mới được. Người tu Thiền khi bệnh phải làm sao? Chúng ta cứ nghĩ bệnh tu không được, nhưng thật ra người biết tu, bệnh là cơ hội tốt để thấy thân này là vô thường, là tướng bại hoại, là gốc của đau khổ, thấy như vậy là trí tuệ, vì thấy đúng như thật. Như vậy chúng ta tu bằng trí tuệ, không phải tu bằng Thiền định. Ngồi yên là Thiền định, còn nằm quán thấy rõ thân mình là trí tuệ.

Ngày xưa Phật có hai vị đệ tử cự phách, đó là ngài Xá-lợi-phất và ngài Mục-kiền-liên. Ngài Mục-kiền-liên chuyên về Thiền định, ngài Xá-lợi-phất chuyên về trí tuệ. Chuyên Thiền định nên ngài Mục-kiền-liên thường dùng thần thông, còn ngài Xá-lợi-phất dùng trí tuệ để hàng phục tất cả ma quân. Vì vậy ngài Mục-kiền-liên được gọi là thần thông bậc nhất, ngài Xá-lợi-phất được gọi là trí tuệ bậc nhất. Cả hai đều giải thoát sanh tử nhưng ngài Xá-lợi-phất được xem như là Sư huynh.

Quí vị đừng lo bệnh tu không được, chỉ sợ mình mê muội, bệnh cứ nằm rên thì tu không được. Còn sáng suốt, quán chiếu thì bệnh là cơ hội tốt để chứng nghiệm sự thật của thân này. Chúng ta mới chán ngán nó, mới mong giải thoát sanh tử. Sở dĩ chúng ta không giải thoát sanh tử được là vì quá quyến luyến thân, nên thân này hoại liền chụp thân khác nữa. Cứ vậy mà luân hồi. Khi chúng ta đã thấy thân này tồi tệ, không có giá trị gì, không muốn được nó nữa thì đâu còn tìm thân khác. Đã không còn tìm thân khác thì đâu có thọ sanh. Không có thọ sanh thì giải thoát sanh tử, dễ như trở bàn tay.

Tôi được nghe một câu chuyện như sau: Có vị đó chết. Khi ra khỏi thân xác này thấy lạnh lẽo, bức xúc quá không chịu nổi, mới chạy tìm nơi trốn, bỗng thấy chiếc tủ máng mấy chiếc áo, liền lấy một chiếc trùm lên cho đỡ lạnh. Không ngờ lát sau nghe như có tiếng người nói: *“heo đực”*. Vị ấy giật mình: *“Ủa! Mình làm heo rồi sao?”*. Chỉ vì không chịu nổi cái lạnh sau khi chết, nên hốt hoảng tìm chỗ tựa cho ấm áp, không ngờ đã đi vào bào thai heo. Vị ấy cũng còn phước nên kịp tỉnh, biết mình là heo đực vì vậy không thèm bú nên bảy ngày sau chết, rồi lại được thọ sanh làm người.

Có những trường hợp như vậy, nhiều người không chịu nổi cái bức bách sau khi chết nên chạy bậy chạy bạ. Nếu chúng ta tu hành đàng hoàng, lúc nhắm mắt có chư thiên đưa đi thì lo gì chuyện ấy. Người không tu, lang thang phải chịu khổ sở như vậy.

Đó là tôi đã nói qua những lối tu không phải của đạo Phật. Đến đây, tôi nói những lối tu của đạo Phật. Thiền của đạo Phật có chia ra các hệ phái Thiền Nguyên thủy và hệ phái Thiền Phát triển.

## Hệ phái Thiền Nguyên thủy {- #thien-nguyen-thuy}

Người tu theo Thiền Nguyên thủy đa số ở các nước Campuchia, Lào, Thái Lan, Miến Điện và Tích Lan. Tu theo Thiền Nguyên thủy có nhiều pháp nhưng ở đây tôi chỉ xin kể hai pháp:

### Pháp quán Tứ niệm xứ {- #tu-niem-xu}

Quán tứ niệm xứ gồm có:

- Quán thân bất tịnh: Thân này có nguồn gốc nhớp nhúa, bẩn thỉu.
- Quán thọ thị khổ: Sự cảm thọ hay cảm giác của sáu căn đều là đau khổ, không vui.
- Quán tâm vô thường.
- Quán pháp vô ngã.

#### Quán thân bất tịnh {- #quan-than-bat-tinh}

Chúng ta quán thân bất tịnh từ đầu tới chân. Quán chiếu toàn là một đãy da bọc trong đó nào là da, thịt, gân, xương, máu, mủ v.v... Khi những thứ đó còn nằm trong thân này thì dễ coi một chút, nhưng nếu ra khỏi thân này thì cái gì cũng gớm hết. Đầu mặt là chỗ quí nhất mà các chất nhờn chảy ra lỗ mũi, lỗ tai, ra miệng, ra con mắt thành ghèn có gớm không? Nếu nó sạch, thơm tho như hoa sen thì chắc không gớm, nhưng vì nó bẩn thỉu nhơ nhớp quá nên chúng ta gớm.

Nhiều khi tôi ngồi gẫm lại mà tức cười. Sở dĩ người ta chế dầu thơm, xà phòng thơm chẳng qua là biết thân này lôi thôi quá, hai ba ngày không tắm không ai chịu nổi, nên có chút dầu thơm xịt vô cho đỡ, hoặc tắm gội xà bông thơm để lấp bớt mùi hôi. Nếu nó toát ra mùi như hoa sen thì đâu cần mấy thứ đó, chế chi cho cực, mua chi cho tốn tiền.

Tôi nhớ khi xưa đức Phật ngồi tu dưới cội bồ-đề, lúc đó ma vương hiện hình những thể nữ xinh đẹp đến để khuyến dụ Ngài, nhất là hiện hình Da-du-đà-la *(Yasadhara)* đến gọi Ngài trở về. Bấy giờ Ngài chỉ nói một câu: “*Cái đãy da hôi thối, đi! Ta không có dùng”*. Nói như vậy rồi các cô ấy hổ thẹn bỏ đi mất.Chúng ta bây giờ chưa thấy được đãy da hôi thối nên nhiều khi cũng lầm. Nếu thấy được như Phật thì chúng ta không còn lầm nữa. Không lầm thì tu quá dễ rồi. Như vậy quán thân bất tịnh không phải là tưởng tượng thân bất tịnh mà là thấy thật sự nó bất tịnh. Đạo Phật không dạy tưởng tượng mà bảo chúng ta phải thấy đúng như thật, đó là cái nhìn của người giác ngộ. Như thân này là nhớp nhúa, thấy đúng nó là nhớp nhúa. Chúng ta bây giờ phần nhiều sống với ảo tưởng, nhớp nhúa mà cứ tưởng thơm sạch rồi tự hào, ngã mạn đủ thứ hết.

Ngày đức Phật còn tại thế dạy các thầy Tỳ-kheo quán bất tịnh. Các thầy quán thấy thân gớm quá không chịu nổi, nên một hôm thầy nọ nhờ thầy kia cắt cổ giùm, cứ như vậy mà trong một tinh xá cắt cổ hết mấy chục thầy. Hôm sau Phật tới thăm chỉ còn có hai ba thầy.

Phật hỏi: Các thầy đâu hết rồi?

Có thầy trả lời rằng: Phật dạy quán thân bất tịnh, quí thầy quán thấy gớm quá chịu không nổi nên nhờ người cắt cổ chết rồi.

Phật quở: Ta dạy các ông quán bất tịnh để trị bệnh tham sắc, chớ không phải quán để tự tử.

Vì vậy tu pháp quán bất tịnh thấy chán, gớm là phải dừng, chớ không phải quán bất tịnh hoài. Vì bệnh nặng nhất của con người là bệnh tham ái nên phải gớm nó mới bỏ được, còn ưa nó thì không tu được. Đó là pháp quán thứ nhất.

#### Quán thọ thị khổ {- #quan-tho-thi-kho}

Thọ là cảm thọ, bây giờ gọi cảm giác. Lỗ mũi ngửi mùi, chúng ta biết đây là thơm, kia là hôi. Lưỡi nếm thức ăn biết rõ cái này ngon, cái kia dở. Thân xúc chạm biết nóng, biết lạnh, biết mềm mại êm ái v.v... Lỗ tai nghe tiếng biết hay, biết không hay. Sáu căn tiếp xúc với sáu trần, chúng ta có nhận định, có khổ, vui và không khổ, không vui. Ba thứ đó gọi là: lạc thọ, khổ thọ và không khổ không lạc thọ, Phật nói đều khổ hết.

Chúng ta thấy nói như vậy có quá đáng không? Vì nếu chúng ta ăn thứ gì ngon thì lưỡi mình có cảm giác ngon, mà ngon tức là vui nên gọi lạc thọ. Ăn món dở cảm giác là khổ, đó là khổ thọ. Nhưng mà dù khổ dù vui, nhai qua vài cái nuốt mất tiêu cũng không còn. Những cảm giác khác đều như vậy, qua rồi mất. Mà qua rồi mất là vô thường, vô thường là khổ.

Như vậy cảm thọ thuộc về tướng vô thường, ngon, dở, tốt, xấu đều là cảm giác qua rồi mất, không có gì còn, tất cả đều bị vô thường chi phối. Cho nên Phật nói: *“Tất cả thọ đều là khổ”*. Quán  chiếu như vậy khi sáu căn tiếp xúc với sáu trần, chúng ta còn nhiễm ái không? Chắc là không. Đó là pháp quán để tu trị bệnh nhiễm sáu trần.

#### Quán tâm vô thường {- #quan-tam-vo-thuong}

Tâm chúng ta khi như vầy, khi thế khác, luôn luôn không dừng phút giây nào. Cứ nghĩ quấy, nghĩ hơn, nghĩ thua, dù cho người tu cũng có khi nghĩ bậy. Đã là tướng vô thường thì không nhất định, luôn luôn chuyển biến nên chúng ta không nên tin. Thường chúng ta có bệnh cho rằng cái gì mình nghĩ cũng là chân lý. Vì vậy mình nghĩ thế này, người khác nghĩ thế kia, mình liền sân giận, có khi cãi vã và đi tới ấu đả nhau. Chấp cái nghĩ của mình là thật có đúng không? Nếu đúng hết thì thế gian này chắc không có ai nghèo, không có ai khổ hết. Tại sao? Vì nghĩ đúng thì làm ăn được, làm đâu trúng đó. Do nghĩ trật nên đang bỏ vốn làm ăn việc này tưởng sẽ gặp thời, ai ngờ nó khác đi, bị thua lỗ thành ra khổ.

Những năm tôi ở trên núi, thấy xa xa có cụm mây đen theo chiều gió thuận thổi đến hướng của mình, tôi cứ đinh ninh đám mây đó sẽ mưa nên dọn đồ đạc bên ngoài vô. Một hồi gió thổi tạt hướng khác, trời không mưa. Như vậy cái nghĩ của mình chưa bao giờ đúng trăm phần trăm. Vậy nên chúng ta ai cũng cho rằng mình nghĩ đúng, đó là nhân của sự tranh cãi hay nói cách khác là nhân của đấu tranh.

Trong kinh, Phật có dạy một câu thật chí lý: Người biết tôn trọng chân lý là người nghĩ điều gì thì nói: “*Đây là cái nghĩ của tôi”*, ngang đó dừng. Nếu nói cái nghĩ của tôi đúng thì đã bậy rồi vì không tôn trọng chân lý. Chỉ thêm chữ *“đúng”* thì có tranh cãi. Chúng ta có bị bệnh không trọng chân lý không? Có lẽ đa số đều bị bệnh đó, nhất là người lớn chừng nào thì bệnh nặng chứng ấy. *“Thầy ra lệnh mà!”* Vì thầy thấy như vậy, biết như vậy nên đệ tử phải làm như vậy. Nhưng thầy cũng trật mất, không đâu vào đâu cả. Nên chúng ta tu phải thấy tường tận lẽ thật. Tâm là vô thường không lâu dài, kiên cố, luôn luôn đổi thay. Như vậy làm sao tâm thật được, làm sao là chân lý được. Nó không thật, không là chân lý mà chúng ta cho là chân lý. Đó là sai lầm.

#### Quán pháp vô ngã {- #quan-phap-vo-nga}

Quán pháp này có hai cách:

- **Tâm pháp:**  
Duy thức học gọi là Tâm sở pháp tức là tất cả Tâm sở như: buồn, thương, giận, ghét v.v... Những thứ đó không có chủ, không thật. Chúng ta sống hiện giờ bị những Tâm sở đó làm rối bời. Khi thì thương, khi thì giận, khi thì buồn, khi thì ghét... đổi qua đổi lại làm mình bất an. Khi đã tu chúng ta phải quán kỹ nó chỉ là tướng không thật thì chấp ngã của mình mới giảm đi, không còn bị chi phối bởi buồn, thương, giận, ghét nữa.

- **Sắc pháp:**  
Chữ *“pháp vô ngã”* này nói rộng hơn cũng gồm luôn tất cả sự vật như cái bàn, bình hoa... Với con mắt phàm tục thì mọi vật đều có thật nhưng với con mắt của người có trí tuệ thì thấy cái bàn, bình hoa không thật có. Như hoa cúc có nhiều cánh, nếu chúng ta gỡ từng cánh ra, mỗi cánh có phải là hoa cúc không? Không phải. Như vậy cái đẹp là do sự cấu tạo nhiều phần hợp lại, chớ không thật có. Nhưng khi nó thành rồi, với một dáng vẻ nào đó khiến chúng ta thích, chúng ta cho là thật rồi đâm ra quyến luyến. Các pháp nếu quán kỹ sẽ thấy chúng không tự thành mà do duyên hợp, không thật nên gọi là pháp vô ngã. Ngã là chủ thể. Không có gì làm chủ sự vật cả, tất cả đều do duyên hợp, do từng phần cấu tạo thành, không có chủ thể.

Quán thân này cũng do duyên hợp, không có chủ thể. Nhờ quán pháp vô ngã chúng ta không còn chấp thân này là thật, cảnh này là thật. Do đó chúng ta hết mê muội, hết luyến ái. Đó là lối tu Thiền Tứ niệm xứ.

Trong kinh A-hàm đức Phật dạy:

> Nếu người nào chuyên tâm trong Tứ niệm xứ một ngày, hai ngày, ba ngày cho đến bảy ngày không dời đổi thì người đó chứng quả A-na-hàm cho đến quả A-la-hán. Chẳng những bảy ngày mà sáu ngày, năm ngày, bốn ngày, nếu người chuyên tâm trong Tứ niệm xứ không dời đổi cũng chứng từ Tam quả trở lên.

Rốt lại Phật nói một ngày mà ai chuyên tâm trong Tứ niệm xứ không dời đổi thì người đó cũng chứng được Tu-đà-hoàn trở lên.

Như vậy chứng quả Thánh đâu có khó, chỉ khó vì chúng ta không chuyên tâm. Chuyên tâm một chỗ trong một ngày thì khỏi các niệm sanh diệt. Niệm sanh diệt không còn thì đi sâu vào tâm thể chân thật của mình rồi. Vì vậy dễ chứng được các quả vị. Đó là nói về Tứ niệm xứ.

### Minh sát tuệ {- #minh-sat-tue}

Thiền này cũng dùng trí tuệ xem xét rõ ràng tất cả các vật. Có khi các ngài dùng Minh sát tuệ để quán Tứ đế, có khi các ngài dùng Minh sát tuệ để quan sát hơi thở: hít vô bụng phình ra, thở ra bụng xẹp xuống. Hít vô phình, thở ra xẹp. Đó là lối quán của Thiền Minh sát tuệ.

Chúng ta thấy tu theo Nguyên thủy cũng là tu Thiền. Hoặc Thiền Tứ niệm xứ, Minh sát tuệ, Ngũ đình tâm v.v... Đó là phương pháp tu của đạo Phật theo hệ Nguyên thủy.

## Hệ phái Thiền Đại thừa {- #thien-dai-thua}

Trong hệ Đại thừa này căn cứ theo các vị Thiền sư ở Trung Hoa dạy như Lục Diệu Pháp Môn. Lúc đầu chúng tôi cũng có học và ứng dụng pháp Thiền này.

### Lục Diệu Pháp Môn {- #luc-dieu-phap-mon}

Lục Diệu pháp môn là gì?

Là bao gồm các pháp:

- Sổ tức
- Tùy tức
- Chỉ
- Quán
- Hoàn
- Tịnh

Đức Phật khi vào Thiền định cũng tu hơi thở. Điều này trong các kinh A Hàm có ghi lại.

1. **Sổ tức:**
Chúng ta sử dụng sổ tức là đếm hơi thở. Hít vô cùng, thở ra sạch đếm một. Hít vô cùng, thở ra sạch đếm hai. Đó là cách đếm hoãn. Còn cách đếm nhặt thì hít vô cùng, đếm một; thở ra sạch, đếm hai. Cứ như vậy đều đặn hơi vô, hơi ra. Đếm từ một đến mười rồi bỏ, đếm lại. Công việc thấy như đứa con nít chơi vậy, nhưng thật là quan trọng. Vì chúng ta đã quen tâm phóng chạy ra ngoài, bây giờ muốn cột nó lại, làm sao cột? Phải mượn hơi thở. Thường người tu Thiền là phản quan, soi lại. Soi lại cái gì? Soi lại hơi thở. Hít vô cho tới cùng, đếm một; thở ra cho tới hết, đếm hai. Biết hơi thở ra vô, biết đếm một hai nên quên hết các thứ bên ngoài, do đó tâm được yên. Thời gian thuần thục từ nửa giờ cho đến một giờ, đếm không còn lộn. Đó là thành công quán sổ tức.

2. **Tùy tức:**
Bỏ đếm, chỉ theo dõi hơi thở. Hít vô biết, thở ra biết. Trong nhà Thiền nói như chú chăn trâu đang theo dõi con trâu của mình vậy, đi tới đâu mình theo dõi tới đó. Thở vô tới đâu biết, thở ra tới đâu biết. Biết một cách rõ ràng đó là tùy tức.

3. **Chỉ:**
Tùy tức xong rồi phải định, tức là chỉ. Chỉ là dừng lại, trụ tâm hoặc ở mũi, hoặc ở ngực, hoặc ở rốn, tùy theo mỗi người. Như trụ tâm ở mũi chỉ thấy mũi thôi, không nhớ gì khác đó là chỉ.

4. **Quán:**
Quán hơi thở này từ đâu mà có? Từ ngoài hít vô rồi thở ra mất, thấy như vậy thuần thục cho đến cuối cùng biết rõ hơi thở không thật, vô thường nên thân này cũng không thật, cũng vô thường, đó là quán hơi thở.

5. **Hoàn:**
Quán như vậy là chưa cứu kính, liền tới hoàn. Hoàn là xoay trở lại xem cái quán hơi thở ra vô đó nó ở đâu. Tìm lại xem là hoàn.

6. **Tịnh:**
Đến đây tâm yên lặng, thanh tịnh, không còn quán, không còn xoay gì nữa cả, đó là tịnh. Đến tịnh là thành công.

Nói thì dễ chớ làm không phải dễ. Hồi xưa lúc tôi ở Chân Không tôi cũng dùng pháp này. Sổ tức, Tùy tức tôi làm được. Tới Chỉ, đầu tiên tôi trụ tâm ở chót mũi, trụ một hồi hai con mắt nó nhức giật giật; tôi liền dồn xuống ngực, nghe tức ngực quá, chịu không nổi tôi liền dồn xuống rốn, một lúc gục lên, gục xuống, đến khóc mà thôi. Thật ra người tu nào cũng có những cay đắng trong lúc hạ thủ công phu tu nhưng tùy theo người, theo duyên mà mỗi người gặp những khó khăn khác nhau. Nếu pháp nào hợp, có lợi ích cho sự tu thì chúng ta phải theo. Nếu gặp pháp nào trở ngại thì mình chuyển qua pháp khác. Nên Phật dạy nhiều pháp môn là vì vậy. Do nghiệp chúng sanh sai khác nên pháp tu cũng sai khác.

Trong kinh có kể: Một hôm ngài A-nan đi khất thực tới chỗ ông thợ rèn, sau khi cúng dường cơm xong, ông xin Ngài dạy cho một pháp tu. A-nan liền dạy ông pháp quán thân bất tịnh. Người thợ rèn về quán hoài không có kết quả. Hôm khác ngài A-nan đi khất thực ghé vào nghĩa địa gặp ông giữ nghĩa địa, cúng dường cơm xong ông cũng xin Ngài dạy pháp tu. Ngài dạy ông này quán hơi thở. Ông hành một thời gian cũng không thành công. Ngài về lễ Phật thưa rằng:

\- Bạch Thế Tôn, có hai người đệ tử xin con dạy pháp tu. Con dạy một người quán Sổ tức, một người quán Bất tịnh, nhưng cả hai đều thực hành không có kết quả.

Phật hỏi:

\- Hai người đó làm nghề gì?

Ngài A-nan thưa:

\- Bạch Thế Tôn, người làm nghề thợ rèn thì con dạy quán Bất tịnh, còn người giữ nghĩa địa thì con dạy quán Sổ tức.

Phật bảo:

\- Vậy là ông dạy sai rồi. Người làm thợ rèn mỗi ngày thường thổi ống bễ phì phịch, sao ông không dạy quán hơi thở cho dễ? Còn người giữ nghĩa địa mỗi ngày đều thấy thây ma hoài, sao ông không dạy quán Bất tịnh?

Nhờ Phật chỉ nên sau đó ngài A-nan dạy lại hai vị đệ tử tu được thành công.

Quý vị thấy, pháp tu cũng ảnh hưởng đến nghề nghiệp và cuộc sống của mỗi người nên chúng ta không nên cho một pháp nào là cứu kính. Nếu một pháp cứu kính thì Phật không dạy nhiều pháp môn. Tùy theo căn cơ chúng sanh, với những nghề nghiệp khác nhau, bệnh hoạn khác nhau nên pháp tu cũng khác nhau.

### Pháp quán Không, Giả, Trung {- #phap-quan-khong-gia-trung}

Pháp này của ngài Thiên Thai Trí Giả đại sư ở Trung Quốc.

Quán Không là quán sát tất cả pháp trên thế gian này đều do duyên hợp mà có hình tướng, có danh tự, tên tuổi, chớ thật tình nó không thật, không có thực thể, nên gọi là Không. Tuy Không nhưng duyên hợp thì giả có. Giả có nên đâu phải là không ngơ. Vì vậy nói quán Giả. Người thấy được nghĩa Không, Giả hòa hợp, đó gọi là quán Trung.

Tôi xin dẫn câu chuyện chúng ta thường nghe trong các kinh sách Phật. Các ngài thường nói *“bóng trúc quét thềm”* hay là *“bóng trăng đáy nước”*. Trước sân nhà chúng ta có bụi tre, khi trời nắng lên, bóng của bụi tre ngả vào trước sân, gió đưa qua đưa lại nên chúng ta thấy trước sân mình có bóng trúc quét qua, quét lại. Tuy thấy quét mà không sạch bụi. Như vậy bóng trúc là có hay là không? Chúng ta thường cho là không, vì nó là bóng mà. Không thì sao mắt nhìn thấy, còn nếu thật thì sao nắm bắt nó không được? Như vậy nó không phải thật, cũng không phải không. Không phải thật có, không phải không ngơ, chỉ là giả danh.

Giống như mặt trăng dưới đáy nước. Khi hồ nước trong, vầng trăng sáng, chúng ta nhìn dưới hồ nước thấy có mặt trăng. Vậy bóng trăng ở dưới nước là thật có hay thật không? Nói thật có cũng không được, vì mò vớt nắm bắt không được. Nói thật không sao mắt nhìn thấy, mình đi đâu nó cũng theo mình.

Như vậy để thấy tất cả pháp trên thế gian này không thật mà cũng không phải là không ngơ. Chỉ là duyên hợp thì có, duyên tan thì không, không có thể cố định chân thật nên gọi là giả danh. Chúng ta có thói quen cho cái gì cũng thật cả. Vật gì mình sờ mó được mà ai nói giả, mình không bao giờ chịu. Như vậy để thấy rằng cái nhìn, cái hiểu của chúng ta nông cạn, sai lầm nên Phật quở không đúng lẽ thật.

Người tu theo Thiền Đại thừa dùng pháp quán Không, quán Giả, quán Trung để biết rõ tất cả vật đúng như thật, không lầm lẫn. Tôi chỉ nói về Thiền Đại thừa đại khái như thế thôi. Tiếp theo tôi nói đến Thiền tông.

Thiền tông còn gọi Tối thượng thừa thiền. Thiền tông ở Trung Hoa truyền sang Việt Nam: Từ Tổ Bồ-đề-đạt-ma truyền xuống Tổ Huệ Khả, Tổ Huệ Khả truyền xuống cho Tổ Tăng Xán, dưới Tổ Tăng Xán có ngài Tỳ-ni-đa-lưu-chi truyền sang Việt Nam.

Như vậy ngài Tỳ-ni-đa-lưu-chi truyền Thiền tông sang Việt Nam từ đầu thế kỷ thứ sáu và sau này ngài Vô Ngôn Thông cũng truyền Thiền tông sang nước ta vào cuối thế kỷ thứ chín. Thế nên Thiền tông ở Việt Nam có từ thế kỷ thứ sáu đến mãi về sau. Chư Tổ từ Bắc chí Trung đều tu theo hệ Thiền này. Gần đây ở miền Trung các Tổ Nguyên Thiều, Tổ Liễu Quán v.v... cũng tu theo Thiền tông. Tôi đọc trong Thiền sư Việt Nam thấy ở miền Bắc cũng có nhiều vị Tổ tu theo Thiền tông, theo các hệ phái Tỳ-ni-đa-lưu-chi hay hệ phái Vô Ngôn Thông.

Tôi xin nói lại Thiền tông trước đời nhà Tống ở Trung Quốc, tức từ Tổ Bồ-đề-đạt-ma, Thiền tông là một lối tu phản quan tự kỷ. Tổ Bồ-đề-đạt-ma khi sang Trung Hoa, Ngài trú ở chùa Thiếu Lâm, ngồi xây mặt vào vách, không nói chuyện với ai gần chín năm.

Bấy giờ ngài Thần Quang là một Thiền sư tu theo các pháp Thiền Đại thừa nhưng không có kết quả, song công phu cũng khá thâm hậu. Ngài Thần Quang tìm đến chùa Thiếu Lâm thấy Tổ Bồ-đề-đạt-ma đang ngồi xây mặt vào vách, không biết làm sao, nên vào một mùa đông tuyết rơi đầy mà Ngài vẫn đứng ngoài sân chắp tay nhìn về Tổ Bồ-đề-đạt-ma suốt đêm. Sáng ra tuyết đã ngập gối nhưng gương mặt Ngài vẫn tỉnh sáng như thường. Tổ Bồ-đề-đạt-ma xoay lại nhìn thấy, hỏi:

\- Ông đến đây cầu việc gì mà khổ hạnh như vậy?

Ngài Thần Quang thưa:

\- Con đến đây xin Ngài dạy cho con pháp môn cam lộ.

Tổ Bồ-đề-đạt-ma quở:

\- Muốn đạt được pháp của Phật dạy phải nhiều năm khổ hạnh, nhiều đời bỏ thân này đến thân khác, mới có thể lãnh thọ. Ông chỉ dùng một chút khổ hạnh như vậy làm sao cầu được.

Ngài Thần Quang nghe quở liền đi xuống nhà bếp, mượn dao chặt một cánh tay dâng lên Tổ Bồ-đề-đạt-ma để cầu pháp. Tổ Đạt-ma thấy Ngài tha thiết quá nên bằng lòng dạy.

Trong câu chuyện này khi giảng tôi cũng hơi dè dặt. Việc chặt cánh tay tôi còn bán tín, bán nghi, không dám khẳng định. Nhưng qua việc ấy có thể hiểu rằng các ngài muốn cho chúng ta biết: Phật pháp là một pháp cao siêu tuyệt vời, đưa người tới giải thoát sanh tử thì phải liều chết, quyết tâm mới được, không phải chần chờ hay tu một cách bình thường mà có thể được. Vì vậy các ngài lập ra hình ảnh chặt tay cho chúng ta thấy gương cương quyết của người xưa học đạo mà chúng ta cố gắng.

Được Tổ Bồ-đề-đạt-ma nhận rồi Ngài theo học một thời gian. Hôm đó Ngài quì thưa:

\- Bạch Hòa thượng ! Tâm con không an, xin Hòa thượng dạy con pháp an tâm.

Tổ Bồ-đề-đạt-ma bảo:

\- Ông đem tâm ra ta an cho.

Ngài Thần Quang xoay lại tìm mãi không thấy tâm của mình đâu hết nên thưa:  

\- Bạch Hòa thượng, con tìm tâm không được.

Tổ Đạt-ma bảo:

\- Ta đã an tâm cho ngươi rồi.

Ngay đó ngài Thần Quang lãnh hội được pháp an tâm.

Quí vị thấy dễ hay khó? Lời nói của Tổ Bồ-đề-đạt-ma có phải lời đùa chăng? Thật ra ngày xưa khi chưa nhận được lý Thiền, tôi thấy các Tổ của mình dường như đùa cợt với nhau chơi, chớ không thật thà chút nào hết. Khi biết được rồi mới nể phục các ngài vô cùng.

Chúng ta thường cho cái suy nghĩ là tâm của mình. Nghĩ đông, nghĩ tây, nghĩ đủ thứ, nói đó là tâm tôi nghĩ nên tâm bất an vì cứ chạy hoài, loạn động luôn luôn. Tổ bảo: *“Đem tâm ra ta an cho”*. Đây đâu phải là lời nói nhẹ. Bảo đem tâm ra tức là phản quan tìm lại cái tâm lăng xăng của mình đó xem nó ở đâu. Nhìn lại nó mất dạng. Nó mất dạng thì lúc đó có an hay không? Đó là an rồi.

Như vậy phản quan lại tâm lăng xăng thì tâm lăng xăng mất. Đây chính là pháp tu để đi cho tới chỗ an tâm. Soi sáng lại chính mình xem tâm lăng xăng ở chỗ nào, nó ra làm sao. Tìm lại thì nó mất nên tâm được định không còn chạy, không còn loạn. Đó là đã an tâm rồi. Rõ ràng như vậy, nhưng chúng ta không hiểu nên tưởng các ngài đùa chơi.

Khi ngài Thần Quang nhận lãnh được liền đảnh lễ thưa rằng:

\- Con đã biết lối vào.

Tổ bảo:

\- Ông khá đó.

Nên Tổ đổi tên Ngài là Huệ Khả.Quý vị thấy an tâm dễ hay khó? Nó đơn giản làm sao, gần gũi làm sao! Khi nhận hiểu điều này rồi chúng ta thấy thật là quá hay, thật là đơn giản không phải chuyện xa vời.

Đến ngài Huệ Khả dạy ngài Tăng Xán. Ngài Tăng Xán đang bị bệnh hủi *(cùi)* một hôm gặp Tổ Huệ Khả, Ngài bạch:

\- Xin Hòa thượng dạy cho con phương pháp sám hối.

Tổ Huệ Khả bảo:

\- Đem tội ra ta sám cho.

Ngài Tăng Xán xoay lại tìm mãi không được, mới bạch Tổ:

\- Bạch Hòa thượng, con tìm tội không thấy.

Tổ Huệ Khả bảo:

\- Ta đã sám hối cho ngươi rồi.

Ngay đó ngài Tăng Xán liền ngộ. Từ đó bệnh hủi của Ngài cũng lần lần thuyên giảm.

Đoạn trước thì phản quan tìm tâm, đoạn này phản quan tìm tội, tìm nghiệp của mình. Tìm đáo để không thấy tức là nó cũng không thật.

Tới vị Tổ thứ ba là ngài Đạo Tín. Khi Ngài còn là Sa-di, một hôm gặp Tổ Tăng Xán, Ngài thưa:

\- Bạch Hòa thượng, xin Ngài dạy cho con phương pháp giải thoát.

Ngài Tăng Xán bảo:

\- Ai trói buộc ngươi?

Ngài Đạo Tín nhìn lại không thấy ai trói buộc hết nên thưa:

\- Dạ không ai trói buộc con.

Tổ bảo:

\- Vậy cầu giải thoát làm gì?

Ngay đây ngài Đạo Tín liền ngộ.

Chúng ta xoay lại tìm xem cái gì làm mình trầm luân, làm mình khổ sở. Tìm lại không thấy, mà cứ tưởng tượng mình đang bị trói buộc, bị này, bị kia, đủ thứ hết. Đã là tưởng tượng không thật thì cầu giải thoát làm gì? Có bị trói mới nhờ người mở, còn không bị trói mà nhờ người mở thì sao? Ngài Đạo Tín xoay lại tìm không thấy cái gì trói buộc hết nên Tổ Tăng Xán bảo: *“Ta đã giải thoát cho ngươi rồi”*.

Chúng ta thấy các ngài ngộ đạo đều do nhìn lại, soi chiếu lại nơi mình, tìm xem tâm thật hay không; tìm tội, nghiệp xem thật hay không; tìm sự trói buộc nơi mình xem thật hay không? Rốt cuộc chỉ là ảo tưởng không thật. Thấy được không thật là ngộ lý đạo, từ đó tu hành thành Tổ. Lối phản quan là vậy.

Hết đời Tùy tới đời Đường, mãi cho đến đời Tống, Thiền sư Trung Hoa dạy lý Thiền thì chư Tăng đương thời đều hiểu hết, nhưng cứ nói suông chớ không chịu tu. Do đó các ngài làm ngược lại, không dạy lý nữa mà cho một câu thoại đầu: *“Trước khi cha mẹ chưa sanh, ta là cái gì?”*. Chỉ dạy một câu đó về nghiền ngẫm mãi thì đâu còn lý thuyết chi nữa. Vì chư Tăng cứ hiểu lý hoài mà không tu, nên bây giờ các ngài bắt phải tu mà không cho hiểu lý. Nên ở Trung Hoa từ đời Tống về sau mới xuất hiện Thiền thoại đầu là vì vậy.

Hiện giờ ở Việt Nam, Tăng Ni và quí Phật tử đã hiểu lý Thiền hết chưa? Nếu chưa mà tôi dạy Thiền thoại đầu thì không được, nên buộc lòng tôi phải nói cho quí vị hiểu, biết đường lối tu. Sau này năm, ba chục năm hoặc là một, hai trăm năm người ta hiểu nhiều quá, thông minh quá, mở miệng là nói thiền thì lúc đó không giảng dạy nữa, chỉ dùng một câu thôi. Nên phương tiện giáo hóa phải tùy thời, tùy hoàn cảnh mà sử dụng. Quí vị đừng nghĩ rằng Thiền thoại đầu mới là Thiền tông. Không phải vậy, Thiền tông trước kia không có thoại đầu, chỉ sau này thôi. Đó là tôi nói hệ thống tu Thiền từ trên đến dưới.

Chúng ta tu tập tọa thiền để làm gì? Chúng ta tọa thiền là tập cho tâm yên, lặng xuống. Bởi vì khi ngồi thiền chúng ta không suy nghĩ, mọi suy nghĩ phải dừng. Nếu tâm chúng ta dừng, không suy nghĩ lộn xộn, đó là thanh tịnh. Tâm thanh tịnh thì trí chúng ta sáng suốt.

Đến đây, tôi muốn nói pháp tu Thiền là pháp thực tế, thích hợp với tinh thần khoa học hiện đại. Đây là điều tôi muốn nói rộng cho tất cả quí vị lưu tâm. Tại sao pháp tu Thiền thực tế?

Quí vị thấy lúc nào trong gia đình có chuyện bối rối, chúng ta nghĩ lăng xăng lộn xộn đủ thứ hết. Những lúc đó mình để đồ đạc nơi này nơi nọ, muốn nhớ lại món đồ để chỗ nào, thì quên mất không biết để đâu. Chỉ khi nào yên tịnh, ngồi lặng xuống một chút liền nhớ. Rõ ràng nhờ yên lặng trí mình sáng.

Nhiều người mới tập ngồi thiền, khi ở ngoài mình thấy mọi chuyện bình thường không có gì, ngồi lại hơi yên một chút liền nhớ chuyện năm trên năm dưới. Người đó có ân gì với mình, người đó có oán gì với mình, nhớ đầy đủ hết! Nhớ nên khổ quá. Sao mình ngồi cho yên mà nó cứ nhớ chuyện đâu đâu không. Như vậy cái nhớ đó xấu hay tốt?

Thật ra, như tôi đã nói vì bận tâm chuyện này chuyện nọ nên mình quên, bây giờ ngồi yên lại mình liền nhớ. Như vậy nhớ là sáng mà quên là tối. Quí vị ngồi thiền mới sơ sơ thôi, mà nhớ được chuyện năm trên năm dưới là biết mình sáng rồi đó. Hồi xưa ở ngoài đời mình lộn xộn nên không nhớ, bây giờ nhờ yên nên nhớ. Như vậy là sáng hơn, sáng hơn thì mừng chớ sao buồn! Đến chừng nào chúng ta yên trọn vẹn sẽ nhớ ra vô số kiếp.

Cho nên đức Phật ngồi thiền bốn mươi chín ngày đêm dưới cội bồ-đề, tới đêm cuối, tâm Ngài hoàn toàn thanh tịnh. Ngài sực nhớ đến câu hỏi Ngài đã đặt ra: *“Trước khi có mặt ở đây ta từng ở đâu?”*. Vừa nghĩ ta từng ở đâu, Ngài liền nhớ suốt hết bao nhiêu kiếp từng ở nơi này, nơi kia, nơi nọ… nhớ rõ ràng không nghi ngờ. Đời đó tên gì họ gì, cha mẹ là ai, nhớ hết. Nhớ suốt như vậy gọi là chứng Túc mạng minh.

Chúng ta ngồi sơ sơ, yên chút chút nên nhớ được chuyện hai ba năm, chín mười năm trước là kha khá rồi đó. Nếu ngồi yên hoàn toàn thì chúng ta cũng nhớ như Phật. Như vậy tu là một lẽ thật, tâm yên tịnh thì trí sáng, không nghi ngờ gì hết. Đây không phải chuyện gì xa xôi, chuyện gì huyền hoặc. Tu rồi chúng ta mới thấy kết quả đúng như vậy.

Hiện tại tâm chúng ta đang loạn, đang lăng xăng, nếu chúng ta khéo quán hay là khéo an định thì nó lặng. Lặng nhiều thì biết nhiều, lặng ít thì biết ít. Trong lòng còn tham, sân, si biết rõ còn tham, sân, si. Tham, sân, si yếu giảm thấy rõ yếu giảm, tu tới đâu biết kết quả tới đó. Tu là đoạn trừ phiền não, dẹp hết những vọng tưởng điên đảo ở trong tâm mình. Vậy thì pháp tu này là pháp tu khoa học tâm linh của con người. Đó là sự tu thực tế nơi nội tâm mình, chớ đâu phải chuyện xa vời. Có tiến mình biết tiến, không tiến mình biết không tiến. Bước được bước nào là biết rõ bước ấy. Như vậy có thực tế hay không? Rất thực tế.

Khoa học ngày nay phân ra nhiều môn học. Môn học này, môn học nọ, mỗi môn đều có chia thành khoa riêng. Chúng ta chuyên tu để dẹp bỏ cái hư ảo của tâm linh, hiện bày cái chân thật nơi mình. Cái giả mình biết giả, cái thật mình biết thật rõ ràng, thì không phải một môn chân thật hữu lý của khoa học là gì!

Vì vậy chúng ta tu Thiền rất thích hợp với thời hiện đại. Giới Phật tử trí thức này nay đến với đạo Phật cũng thích tu Thiền. Người Tây phương học hỏi Phật pháp đều muốn học Thiền. Vậy, Thiền học của Phật giáo là môn học mà giới trí thức trong nước, cũng như ngoài nước hiện nay đều đang hâm mộ, kính trọng. Thế thì tại sao chúng ta không khai thác, không thực hành tu tập Thiền tông. Có đáng tiếc không? Vì vậy tôi thấy chúng ta nên mở mang đường lối tu Thiền từ các bậc Tôn túc thuở xưa, để rồi hướng dẫn cho những người ham tu, hiếu học ngày nay có một hướng tu cụ thể, thực tế. Có thế, người ta mới hứng thú tu.

Theo tôi, tu Thiền là một pháp tu quá dễ. Tại sao? Vì vọng tưởng từ mình có thì bỏ nó cũng từ mình mà bỏ. Không có Trời, Phật nào chen vào đó hết. Chúng ta có quyền quyết định hoàn toàn. Muốn cho vọng tưởng hết thì phải dẹp sạch nó. Đây là việc làm trong tầm tay của chúng ta, không phải đợi Phật cho mình mới làm được, hay các Tổ ủng hộ mình mới làm được.

Quí vị ngồi nhớ chuyện đông, chuyện tây viển vông thì phải rầy nó: *“Đó là bậy, không được theo”* liền bỏ đi thì tự nó hết chớ gì. Chúng ta có quyền dẹp nó, cứ dẹp hoài thì có sẽ hết thôi. Như trong túi của chúng ta có sẵn những món đồ xấu và tốt. Nếu chúng ta muốn giữ đồ tốt thì phải lượm đồ xấu quăng ra. Trong túi của mình, lượm quăng ra dễ hay khó? Rất là dễ, vì của mình mà.

Vọng tưởng cũng vậy còn dễ hơn bỏ đồ xấu nữa. Vì vọng tưởng là ảo, bỏ cái vọng tưởng ảo để cái thật hiện bày. Như đêm rằm trên hư không có mặt trăng sáng nhưng mây đen cứ bay đến nên thấy tối. Nếu mây đen tan thì mặt trăng liền sáng rực. Mây với mặt trăng, cái nào dễ dẹp. Mây tan hay mặt trăng tan? Mây tan chớ mặt trăng đâu có tan.

Như vậy nơi mình có Tánh giác chân thật còn vọng tưởng là đồ ảo, mà đồ ảo thì bỏ chớ ai đi bỏ Tánh giác. Bảo bỏ cái thật mới là khó, chớ cái ảo thì bỏ quá dễ rồi. Ai cũng có quyền làm được việc này, chỉ có quyết chí hay không thôi. Ai quyết chí mạnh dạn thì thành công, ai lơ lơ, lửng lửng thì thất bại. Đó là quyền của mọi người.
