# Thiền tông là cội gốc của đạo Phật {- #thien-tong-la-coi-goc-cua-dao-phat-2}

<div class="align-right">
*Giảng tại chùa Huệ Quang, Hoa Kỳ*  
*Tháng 11, 2000*
</div>

Hôm nay tôi sẽ nói đề tài Thiền tông là cội gốc của đạo Phật. Ở Việt Nam từ cuối thế kỷ thứ mười chín cho đến thế kỷ hai mươi, Thiền tông gần như thất truyền. Vì vậy chúng tôi là hàng hậu bối sau này, làm sao hiểu được, nhận được đường lối tu của chư Tổ mà tu thiền. Đó là một nghi vấn không thể tránh khỏi của nhiều vị. Để giãi bày điều này, tôi xin phép được kể lại một vài nét tu tập của mình. Từ đó chúng tôi tìm ra một hướng đi theo đường lối tu của chư Tổ Việt Nam.

Trước kia chúng tôi thường giảng dạy cho Tăng Ni các trường Phật học và Phật tử ở các tỉnh. Nhưng đến năm 1968 tôi nhất định đóng cửa thất tu. Năm 1961 chúng tôi đã dịch cuốn *“Lục Diệu Pháp Môn”* của Tổ Trí Khải, cho nên giai đoạn đầu tu thiền chúng tôi tu theo hướng của Ngài. Lục diệu pháp môn là một pháp tu rất phù hợp với lời Phật dạy trong kinh. Vì vậy những năm tuy còn giảng dạy ở trường, chúng tôi vẫn tập tu theo pháp môn đó.

Tới năm 1966 tôi nghỉ dạy ở Phật học viện Huệ Nghiêm, lên núi cất thất chuyên tu. Lúc đó, tôi đọc rất nhiều lần sử ba mươi ba vị Tổ từ Ấn Độ đến Trung Hoa sang Việt Nam, nhất là đọc sử Tổ Trung Hoa. Tôi đọc qua đoạn sử Tổ Huệ Khả đến cầu pháp với Tổ Bồ-đềâ-đạt-ma, sau thời gian tha thiết xin thọ giáo, được Tổ Bồ-đề-đạt-ma nhận làm đồ đệ. Một hôm Ngài thưa với Tổ Đạt-ma:

\- Bạch Hòa thượng, tâm con không an xin Hòa thượng dạy con pháp an tâm.

Lời thưa hỏi rất thật thà, rất chí lý. Nhưng Tổ Đạt-ma bảo:

\- Đem tâm ra ta an cho.

Tổ Huệ Khả ngạc nhiên quá, không ngờ lại có một câu dạy lạ lùng như vậy. Ngài quay lại tìm, không thấy tâm bất an ấy ở đâu, nên Ngài thưa:

\- Bạch Hòa thượng, con tìm tâm không được.

Tổ bảo:

\- Ta đã an tâm cho ngươi rồi.

Ngay đó Tổ Huệ Khả liền biết được đường vào. Đọc ngang đó tôi lắc đầu. Tại sao tâm rối loạn cầu dạy pháp an tâm, mà Tổ không dạy gì hết. Khi Tổ Huệ Khả thưa tìm tâm không được, Tổ Đạt-ma lại nói đã an tâm cho rồi. Như vậy an bằng cách nào, chỗ nào? Đó là vấn đề trước kia chúng tôi đọc đi đọc lại nhiều lần vẫn không hiểu, cứ ngỡ như Tổ đùa cợt chơi thôi.

Mãi tới năm 1968 tôi nhập thất. Trong thất tôi mới lục lại bộ *“Ba Mươi Ba Vị Tổ”* đọc thật kỹ. Đọc đến chỗ Tổ Huệ Khả xoay lại tìm không thấy tâm, thưa rằng con tìm tâm không được, Tổ Bồ-đề-đạt-ma bảo: *“Ta đã an tâm cho ngươi rồi”*, bỗng dưng tôi thấy được đường vào của Tổ Huệ Khả. Từ đó tôi mới chuyên tâm tu theo Thiền tông.

Khi Tổ Huệ Khả xoay lại tìm tâm của mình xem nó ở đâu, tìm không thấy tức là nó đã lặng, mà nó lặng là đã an rồi. Vì vậy nghe ngài Huệ Khả thưa con tìm tâm không được, Tổ bảo ta đã an tâm cho ngươi rồi. Vậy đường hướng Tổ Đạt-ma dạy Tổ Huệ Khả là gì? Tức dạy phản quan nhìn lại tâm của mình. Lâu nay tâm ấy đang chạy nhảy lung tung nên nói *“tâm viên ý mã”*, như khỉ như vượn. Tìm lại nó mất hình mất dạng, như vậy tâm đó thật hay không?

Tất cả chúng ta lâu nay quen cho rằng cái suy nghĩ, tính toán là tâm mình nên khi ngồi lại tu, nó chạy tứ tung kềm không được. Bởi kềm không được nên xin pháp này pháp nọ để an tâm. Giờ đây chúng ta phản quan nhìn lại, tìm coi nó ra sao thì tự nhiên nó mất. Đường hướng của Tổ Đạt-ma chỉ dạy hết sức rõ ràng, bảo mình phải xoay lại tìm xem tâm bất an ra sao, thì nó tiêu tan không còn hình bóng tức được an tâm. An tâm mà không có phương pháp, chỉ dùng trí quán chiếu lại tâm hư dối thì nó mất, đó là an tâm.

Thời gian lâu sau, Tổ Huệ Khả thưa với Tổ Đạt-ma:

\- Nay con đã dứt hết các duyên.

Tổ Đạt-ma bảo:

\- Coi chừng rơi vào không.

Tổ Huệ Khả thưa:

\- Rõ ràng thường biết, làm sao không được.

Tổ Đạt-ma bảo:

\- Ông như thế, ta như thế, chư Phật cũng như thế.

Đó là Tổ Đạt-ma đã truyền tâm ấn cho Tổ Huệ Khả. Tại sao nói truyền tâm ấn? Vì tâm người đệ tử đến được chỗ đúng như tâm thầy, tâm Phật nên lấy tâm ấn tâm. Chữ ấn là in, tâm của Phật của thầy thế nào, tâm của mình cũng như vậy. Đó là tâm tâm hợp nhau nên gọi truyền tâm ấn. Giống như dấu ấn in vào giấy trắng, con dấu có chữ gì thì trên giấy cũng có chữ đó. Như vậy chúng ta mới thấy tinh thần truyền tâm ấn của nhà Phật, nói truyền mà thật ra không có gì để truyền, chỉ là thừa nhận chỗ thấy của người trò đúng với chỗ thấy của thầy, của chư Phật.

Chúng ta nghiền ngẫm xem pháp tu đó của Thiền tông có hợp với giáo lý của chư Phật không? Nhiều người nghĩ rằng Thiền tông nói làm lạ quá, dường như không hợp với kinh điển Phật. Nhưng thật sự tất cả phương pháp Phật dạy đều là phản quan tự kỷ hết. Như trong kinh Tứ Niệm Xứ, Phật dạy chúng ta quán thân bất tịnh, quán thọ là khổ, quán tâm vô thường, quán pháp vô ngã tức là xoay lại thân tâm này, thấy cho tường tận, hiểu cho rõ ràng. Tới Ngũ đình tâm quán cũng vậy, pháp nào cũng phản quan hết.

Gần nhất là kinh Bát-nhã chúng ta tụng hằng đêm. Chỉ một câu đầu thôi chúng ta cũng thấy hay đáo để *“Quán Tự Tại Bồ-tát hành thâm Bát-nhã ba-la-mật-đa thời, chiếu kiến ngũ giai không, độ nhất thiết khổ ách”*. Nghĩa là Bồ-tát Quán Tự Tại khi thực hành sâu trí Bát-nhã, Ngài soi thấy năm uẩn đều không, liền qua hết các khổ nạn. Tăng Ni Phật tử đọc kinh Bát-nhã từ xưa đến giờ biết bao nhiêu biến, có qua hết khổ nạn chưa? Tụng thì tụng mà khổ nạn vẫn chưa hết. Qua đó thấy rằng chúng ta tụng Bát-nhã mà không quán chiếu Bát-nhã. Quán chiếu Bát-nhã là sao? Là quán chiếu năm uẩn: sắc uẩn, thọ uẩn, tưởng uẩn, hành uẩn, thức uẩn, tánh nó rỗng không; được thế mọi khổ ách đều qua hết. Như vậy có phải phản quan không?

Kinh A-hàm dạy phản quan, kinh Bát-nhã cũng dạy phản quan, nghĩa là phải quán chiếu ngược trở lại thì chúng ta mới thấy đạo. Nhưng rất tiếc lâu nay Phật tử học đạo lại có những lầm lẫn như nói Bát-nhã là Bổ Khuyết Tâm Kinh, tức kinh bù lại những gì thiếu sót trong khi chúng ta tụng đọc. Đâu phải thế, kinh Bát-nhã là trí tuệ, mà trí tuệ là gốc của đạo Phật.

Đạo Phật lúc nào cũng dạy chúng ta mở sáng trí tuệ, thấy đúng chân lý. Dù tu Tịnh độ hay tu Thiền tu Mật, tu pháp môn nào cũng phải lấy Bát-nhã làm nền tảng. Cho nên người tụng kinh Di-đà, sau cùng cũng tụng Bát-nhã. Chúng tôi tu Thiền cũng tụng Bát-nhã, quí vị tu Mật cũng tụng Bát-nhã. Rõ ràng Bát-nhã là trí tuệ, là gốc của đạo. Tu cần phải có trí tuệ, nên trong kinh dạy chúng ta phải quán chiếu ngũ uẩn, tức soi sáng lại thân năm uẩn này không thật. Thấy thân năm uẩn không thật thì khổ ách không còn. Nếu chúng ta không chịu quán chiếu thì tụng bao lâu, khổ cũng chưa hết.

Ngài Thái Hư giảng Bát-nhã có ba: một là Văn tự Bát-nhã, hai là Quán chiếu Bát-nhã, ba là Thật tướng Bát-nhã. Văn tự Bát-nhã dụ như chiếc thuyền, Quán chiếu Bát-nhã như chèo dầm để bơi, Thật tướng Bát-nhã như đến bờ bên kia. Nếu người xuống thuyền muốn qua bờ bên kia, trước hết phải nhờ chiếc thuyền, đó là Văn tự Bát-nhã. Kế tiếp phải bơi chèo mới qua tới bờ bên kia, đó là Quán chiếu Bát-nhã. Đến được bờ bên kia rồi, đó là Thật tướng Bát-nhã.

Ngày nay chúng ta tu có chặng đầu thôi, tức là chỉ có Văn tự Bát-nhã mà không có Quán chiếu Bát-nhã. Thử hỏi kẻ muốn qua sông, bước xuống thuyền rồi, cứ ngồi trên đó hoài, thì chừng nào tới được bờ kia? Ngồi đến thuyền mục cũng không tới. Muốn qua được thì phải bơi, phải chèo đó là Quán chiếu.

Như vậy tu Phật, quan trọng nhất là dùng trí tuệ chiếu soi lại chính mình. Từ chư Phật đến chư Tổ đều như vậy, nên tôi nói Thiền tông là cội gốc của đạo Phật. Lục tổ Huệ Năng chỉ nghe kinh Kim Cang một đoạn liền tỉnh. Sau tìm tới Ngũ tổ Hoằng Nhẫn, ở đó tu học cuối cùng được Tổ cho vào thất và giảng kinh Kim Cang. Đến câu: *“Bất ưng trụ sắc sanh tâm, bất ưng trụ thanh, hương, vị, xúc, pháp sanh tâm, ưng vô sở trụ nhi sanh kỳ tâm”*, Ngài liền ngộ đạo và thốt lên rằng: "Đâu ngờ tánh mình xưa nay thanh tịnh, đâu ngờ tánh mình vốn không sanh diệt v.v…" Từ đó Ngũ Tổ mới truyền y bát cho và dạy đi về phương Nam.

Kinh Kim Cang dạy: *“Phàm sở hữu tướng giai thị hư vọng. Nhược kiến chư tướng phi tướng tức kiến Như Lai”*, nghĩa là những gì có hình có tướng đều là hư dối, nếu thấy các tướng không phải tướng, đó là thấy được Phật. Mọi pháp trên thế gian đều do nhân duyên hòa hợp, cũng do nhân duyên mà ly tán nên nó tạm bợ, giả dối. Biết rõ như vậy là có trí tuệ, là thấy Phật.

Cũng trong kinh Kim Cang, hai câu hỏi của ngài Tu-bồ-đề: *“Người phát tâm Vô thượng Chánh đẳng Chánh giác làm sao hàng phục tâm, làm sao an trụ tâm?”. Đức Phật giải thích về an trụ tâm thế này: “*Muốn an trụ tâm thì đối với sắc, thanh, hương, vị, xúc, pháp không dính, không kẹt. Nên không có chỗ dính kẹt mà an tâm”*. Như vậy không chạy theo sáu trần là an tâm.

Tâm chúng ta luôn chạy theo sắc, thanh, hương… như keo sơn. Vì vậy cứ chứa chấp bóng dáng hình ảnh trong lòng. Ví dụ ra đường thấy một người có tật nguyền kỳ quái hoặc một người đẹp tuyệt trần. Về nhà liền nhớ lại hình ảnh đó. Hình ảnh đó là pháp trần, đã dính chặt trong tâm mình. Nên khi tụng kinh, niệm Phật, toạ Thiền nó hiện lên hoài. Nhưng những bóng dáng ấy không thật nên nhìn lại nó liền tan biến, tâm liền an.

Như vậy muốn được an chúng ta không cho tâm đuổi theo sáu trần bên ngoài. Tâm an mới biết được chỗ Lục Tổ nói: *“Đâu ngờ tánh mình xưa nay thanh tịnh. Đâu ngờ tánh mình vốn không sanh diệt…”*. Chúng ta có sẵn tâm an tịnh trong sạch, không sanh không diệt mà quên thành như không có. Cứ chạy theo tâm hư dối rồi tạo nghiệp đi trong luân hồi sanh tử. Bây giờ dừng tâm ấy lại, quay về Tâm chân thật, thì chấm dứt luân hồi sanh tử thôi.

Nhận ra chỗ đó rồi, Ngũ Tổ liền đưa Lục Tổ qua sông trở về phương Nam. Khi qua sông đi được một đoạn đường, có người đuổi theo giành lại y bát, trong đó có Thượng tọa Minh đuổi theo kịp. Tổ thấy thế liền nghĩ y bát vật ấn chứng, chớ không phải tầm thường, nên Ngài để y bát trên bàn thạch, trốn vô lùm cây. Thượng tọa Minh đến, thấy y bát mừng quá tới ôm lên, nhưng ôm không được. Hoảng quá, ông đổi tâm giành y bát thành tâm cầu pháp, mới thưa vào trong: *“Hành giả, hành giả, tôi đến đây vì pháp chớ không phải vì y bát”*. Lục Tổ nghe thế bước ra bảo: *“Nếu ông muốn cầu pháp thì đứng yên lặng giây lâu, ta sẽ nói cho”*. Thượng tọa Minh yên lặng giây lâu, Tổ liền bảo: *“Không nghĩ thiện, không nghĩ ác, cái gì là Bản lai diện mục của Thượng tọa Minh?”*. Ngay đó Thượng tọa Minh liền ngộ, nhận được Bản lai diện mục của mình.

Bản lai diện mục là gì? Bản là xưa, lai là nay, diện mục là mặt mày. Bản lai diện mục là mặt mày thật xưa nay. Bản lai diện mục là tên khác của Chân tâm, của Phật tánh. Khi không nghĩ thiện, không nghĩ ác, ngay đó là Bản lai diện mục rồi. Không nghĩ ác thì chúng ta đồng ý, nhưng nghĩ lành nghĩ thiện là tốt, tại sao không cho? Bởi vì chỗ cứu kính chân thật đó không cho nghĩ, còn nghĩ lành cũng là nghĩ. Khởi nghĩ là khởi niệm, khởi niệm là vọng động nên mất cái chân thật của mình. Cả hai thứ dừng lại thì cái chân thật mới hiện bày.

Nghĩ thiện nghĩ ác, nghĩ phải nghĩ quấy, nghĩ hơn nghĩ thua, nghĩ tốt nghĩ xấu, tất cả nghĩ hai bên đều phải lặng xuống, dừng lại thì cái chân thật hiện tiền. Một bài pháp hết sức đơn giản, hết sức là thực tế mà lâu nay chúng ta nghe thì nghe chớ không hiểu.

Trong kinh Phật dạy chúng sanh luân hồi trong Lục đạo: địa ngục, ngạ quỉ, súc sanh, người, a-tu-la, trời. Chúng ta nghĩ ác thì đi xuống ba đường ác địa ngục, ngạ quỉ, súc sanh. Nghĩ lành thì đi lên ba đường lành người, a-tu-la, trời. Đi lên hay đi xuống cũng đều luân hồi trong Lục đạo, hoặc xấu hoặc tốt. Nếu chúng ta không còn khởi nghĩ đó thì đi đâu? Không nghĩ thì không tạo nghiệp, tâm trong sạch thì giải thoát sanh tử, còn muốn hỏi đi đâu!

Như vậy chúng ta thấy Thiền tông dạy rất kỹ. Rõ ràng cội gốc của luân hồi sanh tử là do ý nghiệp dấy lên, rồi khẩu nghiệp phát ra, thân nghiệp hành động. Ý, khẩu và thân ba cái đó hoạt động tạo ra nghiệp. Nếu tu Thiền thì không nghĩ thiện, không nghĩ ác. Niệm Phật tới nhất tâm hay vô niệm cũng không còn hai thứ. Vì vậy Thiền tông, Tịnh độ tông v.v… cuối cùng đều gặp nhau, nhưng trong lúc tu hành, chỗ ứng dụng có sai biệt.

Tất cả những nghĩ tưởng đều kẹt hai bên. Mở miệng nói là hai bên, cho nên trong nhà Thiền có những chuyện kỳ quái, người ta không hiểu cho là lạ lùng. Như ngài Lâm Tế Nghĩa Huyền học đạo với Thiền sư Hoàng Bá. Học cả năm trời, mà Ngài không hỏi một câu nào hết. Thủ tọa là Trần Tôn Túc thấy vậy mới gọi:

\- Sư huynh tới đây học thiền, sao không hỏi Hòa thượng câu gì hết?

Ngài Lâm Tế thưa:

\- Tôi không biết hỏi câu gì bây giờ?

Thủ Tọa dạy:

\- Ông nên hỏi Hòa thượng: ‘Thế nào là đại ý Phật pháp?”

Ngài Lâm Tế nghe liền đắp y đảnh lễ Hòa thượng và hỏi:

\- Bạch Hòa thượng, thế nào là đại ý Phật pháp?

Ngài Hoàng Bá cầm gậy đập cho một gậy, đuổi đi xuống. Lần thứ hai, Thủ tọa thúc:

\- Huynh lên hỏi nữa đi.

Ngài cũng đắp y lên hỏi:

\- Bạch Hòa thượng, thế nào là đại ý Phật pháp?

Ngài Hoàng Bá đập cho một gậy nữa, đuổi xuống. Lần thứ ba, Thủ tọa xúi lên hỏi một lần nữa. Ngài chần chừ nhưng cũng ráng đi. Đắp y đàng hoàng, Ngài hỏi:

\- Bạch Hòa thượng, thế nào là đại ý Phật pháp?

Tổ Hoàng Bá đập cho một gậy nữa, không dạy lời nào hết.

Chúng ta thấy có tàn nhẫn quá không? Đi hỏi đạo mà ba lần ăn gậy. Bây giờ chúng ta chỉ cần một bạt tai thôi, là cằn nhằn la lối không biết tới đâu. Đằng này ba lần bị đánh bằng gậy, mà Ngài vẫn kiên nhẫn chịu đựng. Tới lần thứ ba Ngài khóc, hết chịu nổi nên cuốn gói đi. Khi sắp đi, Thủ tọa hỏi:

\- Huynh tính đi đâu?

Ngài đáp:

\- Tôi cũng không biết đi đâu, nhưng không có duyên ở đây, phải đi vậy thôi.

Thủ tọa bảo:

\- Huynh lên trình với Hòa thượng rồi hãy đi.

Nghe lời, Ngài lên trình:  

\- Bạch Hòa thượng, con xin đi nơi khác vì không đủ duyên ở đây.

Tổ Hoàng Bá hỏi:

\- Ông định đi đâu?

Ngài thưa:

\- Dạ con cũng không biết đi đâu. Vì không có duyên ở đây thì con đi thôi.

Tổ Hoàng Bá bảo:

\- Ông nên đến chỗ Đại Ngu.

Khi tới núi Đại Ngu, Thiền sư Đại Ngu hỏi:

\- Ông từ đâu đến?

Ngài thưa:

\- Bạch Hòa thượng, con từ chỗ Hoàng Bá đến.

\- Hoàng Bá đã dạy gì cho ông?

\- Bạch Hòa thượng, con hỏi *“thế nào là đại ý Phật pháp”*, mỗi lần hỏi đều ăn gậy, tới ba lần như vậy. Con không biết có lỗi lầm gì?

Ngay đó ngài Đại Ngu liền nói:

\- Hoàng Bá thật là tâm lão bà, chỉ tột cùng cho ông mà ông không thấy còn hỏi có lỗi, không lỗi.

. Vì sao? Vì đời Trần chúng ta cũng có một vị Vua đi tu. Ngài cũng từ bỏ ngai vàng, sách sử ghi lại vua Trần Nhân Tông xem ngai vàng như dép rách, tức Ngài từ bỏ một cách không nuối tiếc, đủ biết Phật giáo với cái nhìn của các ngài cao siêu tới đâu. Tất cả những thứ tầm thường của thế gian, như địa vị danh vọng tiền của v.v… không gì quí bằng đạo, vì thế Ngài mới đi tu.

Giờ đây chúng ta nương theo tinh thần cao thượng của người xưa để xứng đáng là con cháu trong nhà Thiền. Người xưa đã thế thì chúng ta cũng phải cố gắng như vậy. Do đó tôi lấy tinh thần Thiền tông đời Trần làm tiêu chuẩn, để khuyến khích chư Tăng Ni tu phải cao thượng giống như người xưa. Đó là lý do thứ nhất.

Thứ hai là thời Trần không chỉ người xuất gia tu mới ngộ đạo mà kể cả cư sĩ tu cũng ngộ đạo như thường. Đó là hình ảnh Tuệ Trung Thượng Sĩ, một cư sĩ ngộ được lý Thiền. Khi sắp tịch Ngài nằm ngựa giữa, tỳ thiếp vây quanh khóc lóc. Một hồi Ngài mở mắt ra bảo lấy nước súc miệng. Súc miệng xong, Ngài ngồi dậy quở: *“Ta đi có nơi về có chốn, tại sao các ngươi làm nhiễu loạn Chân tánh của ta?”*. Nói rồi, Ngài nằm xuống nhắm mắt đi. Mọi người im lặng, không ai dám làm kinh động nữa.

Chúng ta mới thấy Phật giáo đời Trần là Phật giáo bình đẳng trong sự tu chứng, hàng xuất gia cũng như tại gia tu đều có thể ngộ đạo hết. Cho nên tôi lấy đó làm tiêu chuẩn cho tất cả Tăng Ni tu, đồng thời khuyến khích Phật tử cùng tu, không bỏ một ai. Ở Trung Hoa có ông Bàng Long Uẩn, một cư sĩ tu Thiền ngộ đạo, cả nhà chết một cách tự tại. Việt Nam chúng ta cũng có một cư sĩ sanh tử tự do. Như vậy để chúng ta tự vui rằng, nơi khác có người tu hay, ở Việt Nam cũng có những người tu tốt. Đó là chỗ quan trọng mà chúng tôi chú ý.

Nói tới Thiền tông Việt Nam, nhất là Thiền tông đời Trần ta không thể không nhắc tới Tuệ Trung Thượng Sĩ. Vì Tuệ Trung Thượng Sĩ là thầy của Thái tử Trần Khâm, tức vua Trần Nhân Tông sau này. Một hôm, Thái tử hỏi Tuệ Trung Thượng Sĩ:

\- Bạch Thượng Sĩ, thế nào là chủ yếu của người tu thiền?

Thượng Sĩ đọc một câu chữ Hán:

\- Phản quan tự kỷ bổn phận sự, bất tùng tha đắc.

Nghĩa câu ấy là quay lại soi sáng mình đó là phận sự chánh, không phải từ ngoài mà được. Như vậy phản quan tự kỷ đúng với tinh thần thiền mà Tổ Đạt-ma đã truyền cho Tổ Huệ Khả. Các kinh Phật cũng dạy người tu phải quay lại mình chớ không cầu nơi khác. Thái tử Trần Khâm lãnh hội được yếu chỉ đó, trở về lên ngôi Vua cũng lấy đó làm phương châm cho việc đời việc đạo. Khi hoàn thành trọng trách đối với đất nước dân tộc, Ngài nhường ngôi lại cho con rồi đi tu. Thế là Thiền phái Trúc Lâm Yên Tử ra đời và Ngài là Sơ Tổ Trúc Lâm.

Ngài có làm bài phú Cư Trần Lạc Đạo, bài phú kết thúc bằng bốn câu thơ:

<div class="align-center">
> Cư trần lạc đạo thả tùy duyên  
> Cơ tắc san hề khốn tắc miên  
> Gia trung hữu bảo hưu tầm mích  
> Đối cảnh vô tâm mạc vấn thiền  
</div>

Tạm dịch:

<div class="align-center">
> Ở đời vui đạo hãy tùy duyên  
> Đói đến thì ăn mệt ngủ liền  
> Trong nhà có báu thôi tìm kiếm  
> Đối cảnh không tâm chớ hỏi Thiền  
</div>

*"Cư trần lạc đạo thả tùy duyên"* tức là ở trong cõi trần muốn vui với đạo phải tùy duyên. Tùy duyên là sao? Đói đến thì ăn mệt ngủ liền. Có người nào đói mà không ăn, mệt mà không ngủ đâu. Nhưng thật sự câu này rất khó làm đúng như ý nghĩa của nó. Có một Thiền sư tu trên núi nhiều năm, khi xuống núi có người hỏi:

\- Ngài ở núi làm những việc gì?

Ngài nói:

\- Đói ăn mệt ngủ.

Người kia thưa:

\- Việc đó tôi làm cũng được.

Ngài nói:

\- Tuy vậy mà không được.

\- Tại sao?

\- Bởi vì người đời đói không chịu ăn, mệt không chịu ngủ, còn ta thật sự đói ăn mệt ngủ.

Điều này đối với thế gian quả thật không đơn giản. Mỗi bữa ăn phải có một cốc rượu, nếu không có rượu thì không chịu ăn. Hoặc trên mâm cơm phải có ớt, bữa nào thiếu ớt là ăn không ngon. Đó là chưa kể những người khó tánh, bữa nào dọn cơm không vừa ý, chẳng những không ăn mà còn cằn nhằn nặng nhẹ nữa. Như vậy đói có chịu ăn đâu. Đến ngủ, mệt có chịu ngủ chưa? Hay nằm xuống nhớ chuyện hôm qua hôm kia, chuyện năm trên năm dưới, nhớ lăng xăng cả nửa giờ mới ngủ được. Đó là mệt không chịu ngủ. Như vậy là chưa tùy duyên.

Tùy duyên là đói đến có cái gì ăn cái nấy, mệt nằm ở đâu ngủ cũng ngon. Đó mới gọi là tùy duyên. Nói đói ăn mệt ngủ không phải chỉ thế thôi, nghĩa là chúng ta xử sự mọi việc đến với mình, không phải suy đi tính lại nhiều lần. Cái gì đến giải quyết liền, không suy nghĩ tính toán, mất thời giờ.

Gia trung hữu bảo hưu tầm mích, nghĩa là trong nhà có hòn ngọc sẵn, chớ tìm kiếm ở đâu xa. Chúng ta ngỡ rằng tu muốn thành Phật phải lên non, lên rừng mới được. Nhưng Phật ở đâu? Trong nhà Thiền thường nói *“cõng Phật đi tìm Phật”* hay *“cỡi trâu tìm trâu”*. Phật chính ngay nơi tâm mình. Ngay tâm không sanh diệt là tánh Phật của chúng ta. Ai cũng có nhưng vì vọng tưởng phiền não che lấp nên không thấy. Bây giờ lặng hết những thứ khuất lấp, tự nhiên nó hiện tiền, không nghi ngờ.

Đối cảnh vô tâm mạc vấn thiền. Đối cảnh tức là mắt tai mũi lưỡi thân, tiếp xúc với năm trần sắc thanh hương vị xúc, đừng dính đừng mắc thì hỏi chi Thiền, bởi vì ngay đó là Thiền rồi, đúng như chỗ Lục Tổ ngộ trong kinh Kim Cang: *“Bất ưng trụ sắc sanh tâm…”*. Chúng ta thấy hệ thống Thiền từ cổ chí kim không hai, nhưng phương tiện truyền bá chỉ dạy có khác. Cho nên Thiền tông là gốc của đạo Phật, không nghi.

Trong kinh Lăng Nghiêm khi ngài A-nan hỏi Phật:

\- Bạch Thế Tôn, cái gì là cội gốc của phiền não luân hồi? Cái gì là cội gốc của Bồ-đề Niết-bàn?

Lúc đó đức Phật Thích-ca không trả lời, nhưng mười phương chư Phật *“dị khẩu đồng âm”* đều xướng lên rằng:

\- Này A-nan, cội gốc phiền não luân hồi sanh tử là sáu căn của ông, cội gốc của Bồ-đề Niết-bàn cũng là sáu căn của ông.

Cho nên đối cảnh vô tâm là sáu căn đối với sáu trần không dính không mắc, đó là Thiền, là cội gốc giải thoát Bồ-đề, chớ có gì lạ. Như vậy tu Thiền đâu khác với những gì Phật dạy.

Chúng tôi hiện giờ dạy tu như thế nào? Với tinh thần phản quan tự kỷ hay tinh thần của Tổ Huệ Khả, nhìn lại tâm mình biết nó hư dối, tự tan biến đó là an tâm. Vì vậy Thiền sư Vô Nghiệp khi được hỏi câu gì, Ngài đều trả lời: *“Chớ vọng tưởng!”*. Giờ đây chúng tôi dạy Phật tử cũng như Tăng Ni tu phải nhìn lại tâm của mình. Nếu ngồi Thiền vừa thấy nó dấy lên thì nói vọng tưởng không theo, như vậy mà buông xả. Đó là trong thời gian toạ thiền ban đầu.

Khi ứng dụng bên ngoài, làm việc gì hay đi đâu chúng ta cũng đừng để dính mắc với các trần cảnh. Nhưng nhiều Phật tử nói, con làm ngành này, ngành kia mà bảo vô tâm sao được. Tôi nói không khó, vô tâm ở trường hợp nào, còn trường hợp nào không vô tâm. Thí dụ người làm kế toán phải tính việc này, việc nọ nhưng nếu khéo tu, làm việc gì chỉ chú tâm vào việc đó, không cho một niệm khác chen vào. Tuy rằng chưa được vô tâm, nhưng chính lúc đó đã giảm loạn tưởng. Nếu khá hơn thì trong việc làm ví dụ lái xe, ta cứ ngó thẳng, không suy nghĩ, không lo ra việc khác, đó là tu rồi.

Chúng ta thường có bệnh lo ra, đang làm việc này lại nghĩ việc kia, cho nên tâm lộn xộn không làm chủ được. Khi đặt mình trong một hoàn cảnh nào, làm một việc gì thì chú tâm vào đó, vừa nghĩ khác là bỏ, đó là khéo tu. Tuy rằng chưa vô tâm trọn vẹn, nhưng chúng ta đã gạn lọc được những niệm không ích lợi, làm chủ không để nó lôi. Như thế có mất mình đâu, đó là cách tu trong bận rộn. Dần dần chúng ta làm chủ được trọn vẹn, mới vô tâm đối với sáu trần, chớ không tập từng bước thì tu không thể tiến được.

Đường lối tu Thiền là đường lối của Phật Tổ dạy, không phải ai tự đặt riêng. Chỉ khác ở thủ thuật độ người của chư Tổ thôi, nếu hiểu một ngài tức là hiểu tất cả, còn không hiểu thì đọc hoài cũng không biết gì. Chúng tôi nghĩ rằng, tất cả chúng ta hữu duyên với Phật, với Tổ nên ngày nay mới được học những lời Phật Tổ còn ghi chép lại. Nếu chịu khó nghiền ngẫm ứng dụng tu, nhất định chúng ta sẽ lãnh hội được thâm ý của các ngài. Theo đó tu tiến thì chắc chắn sẽ được an lạc giải thoát.

Mong tất cả chúng ta cố gắng thực hành, để đời mình hết khổ và giúp người hết khổ. Được vậy trên đường tu tiến chúng ta xứng đáng là đệ tử Phật.
