# Mục đích tu thiền {- #muc-dich-tu-thien}

<div class="align-right">
*Giảng tại chùa Quán Sứ – Hà Nội, 2001*
</div>

Cùng tất cả quí Phật tử,

Đạo tràng Quán Sứ ra đời đã nhiều năm. Tôi là người thầy chỉ dạy quí Phật tử tu theo Thiền tông, nhưng ít có cơ hội đến thăm cũng như nhắc nhở việc tu hành cho quí vị. Đây là lần đầu chúng tôi về chùa Quán Sứ hướng dẫn Phật tử Đạo tràng Quán Sứ về đường lối tu thiền.

Chúng ta làm một việc nào, trước hết phải biết mục đích của việc làm đó. Nếu không biết mục đích, việc làm đó sẽ không có căn cứ, hay không có chỗ nhắm đến. Vì vậy đề tài của buổi nói chuyện hôm nay là *"Mục đích tu thiền"*.

Nói đến tu thiền là nói đến một con đường, một phương pháp đưa tới giác ngộ giải thoát. Đức Phật xưa kia tu thiền được giác ngộ thành Phật. Ngày nay chúng ta muốn giác ngộ như đức Phật, dĩ nhiên cũng phải tu thiền. Đó là điều không thể khác hơn được. Là người tu Phật, chúng ta phải biết Phật là gì? Phật là đức Thích-ca Mâu-ni phải không? Chữ Phật ở đây chỉ cho một con người đã được giác ngộ. Ngoài đức Phật Thích-ca Mâu-ni, những người giác ngộ như Ngài cũng đều gọi là Phật. Cho nên nói tới tu Phật là nói tới sự giác ngộ.

Lâu nay chúng ta nghi ngờ tại sao ngoài Bắc, từ thế kỷ 13 về trước gọi Phật bằng *“Bụt”*, còn ngày nay gọi Ngài bằng Phật. Như vậy ai gọi đúng? Tôi sẽ giải thích về điều này. Ngày xưa, vùng đất Luy Lâu là vùng đất thương mại rất phồn thịnh, thương thuyền người Ấn sang đây buôn bán mang theo các nhà Sư truyền đạo. Sư Ấn Độ sang Việt Nam vẫn nói tiếng Ấn. Các ngài gọi Phật là *“Buddha”*, Trung Hoa dịch là “Giác giả”. Giác là giác ngộ, giả là người. Chữ *“Buddha”* là *“Người giác ngộ”*. Tổ tiên mình gọi chữ *“Bud”* là *“Bụt”*. Như vậy gọi *“Bụt”* rất gần với phiên âm tiếng Phạn, nhưng tại sao ngày nay chúng ta gọi *“Phật”*?

Bởi vì vào đời Minh, Trung Hoa có in Tạng kinh bằng chữ Hán, người Việt Nam ta thỉnh về để đọc. Chữ *“Buddha”* dịch âm chữ Hán là *“Phật-đà”*. Chữ *“Bud”* đọc là *“Phật”*, chữ *“dha”* đọc là *“Đà”*. Nên *“Phật-đà”* là người Việt đọc theo âm chữ Hán. Thế nên từ đời Minh, tức khoảng thế kỷ 17 - 18 về sau mới có danh từ *“Phật”*, còn thời gian trước chỉ có danh từ *“Bụt”*. Hiểu như vậy chúng ta mới biết cách gọi Phật của người xưa và người nay khác nhau như thế nào. Tuy khác trên danh xưng nhưng vẫn cùng một ý nghĩa, Phật là chỉ cho bậc giác ngộ.

Đức Phật là bậc giác ngộ nên đạo do Ngài truyền cũng là đạo giác ngộ. Vì vậy nói đạo Phật là đạo giác ngộ. Chúng ta xưng mình là Phật tử tức con của bậc giác ngộ, hoặc ta cũng là người giác ngộ chút chút. Giác ngộ chút chút chớ không phải không chút giác ngộ. Đến với đạo Phật là phải có giác ngộ, chớ không thể mù quáng được. Thế nhưng có Phật tử đến với đạo Phật nhiều năm, vẫn nói chưa giác ngộ gì cả. Thật ra có, nhưng quí vị không biết đó thôi.

Đạo Phật là đạo giác ngộ, nên người tu theo đạo Phật phải có giác ngộ. Giác ngộ từ gần tới xa, từ thấp lên cao. Giác ngộ gần như thế nào, giác ngộ xa như thế nào? Tôi xin hỏi quí vị học Phật mấy năm nay có biết lý vô thường, lý nhân quả, lý nhân duyên không? Nếu biết tức quí vị đã giác ngộ khá rồi. Đối với cuộc sống vô thường mà tưởng thường là người mê, cuộc sống vô thường ta biết vô thường tức là giác.

Người mê cứ nghĩ gặp ác là bị trời phạt, được vui là trời thưởng. Phật tử không như thế, biết gặp ác là do nhân xấu mình đã tạo từ đời trước, gặp lành là do nhân lành đã tạo từ trước, nên ngày nay cảm quả thiện ác đến với mình, chớ không phải do trời ban. Biết đúng lẽ thật như vậy là giác rồi còn gì. Vậy mà quí vị cứ nói mình không giác, đó là do chưa nắm vững đường hướng Phật dạy.

Phật tử hiểu các pháp hiện có mặt đây do nhân duyên tụ họp thành, không có gì gọi là bỗng nhiên mà được. Tất cả đều do nhân duyên tụ họp mới thành. Do nhân duyên tụ họp thành thì các pháp là thật hay giả? Các pháp là giả. Tôi dẫn một vài điều cho quí vị thấy có tu Phật là có giác, chỉ tại không chăm chú, không để ý tới, nên quí vị tưởng mình vẫn mê như thuở nào.

Phật bảo chúng sanh bất giác nghĩa là không giác ngộ gì hết, Bồ-tát phần giác nghĩa là giác ngộ từng phần, còn Phật là mãn giác nghĩa là giác ngộ tròn đầy. Chúng ta nghiệm xem mình thuộc hạng nào? Nếu giác chút chút tức đã được một phần nhỏ, nếu chưa thành Bồ-tát chánh thức thì cũng là Bồ-tát con, phải không?

Bồ-tát là tiếng gọi tắt của âm chữ Phạn *“Bồ-đề-tát-đỏa”* (Bodhisattva), Hán dịch là giác. Bồ-tát là giác từng phần, Phật là giác viên mãn, tròn đầy, không thiếu. Chúng ta giác chút chút thì cũng là con cháu của Bồ-tát rồi. Phải hiểu tu là giác chớ không có quyền mê. Mê thì chưa biết tu. Quí vị là Phật tử, tức biết tu nên cũng có giác chút chút rồi. Chúng ta đang tiến trên con đường giác ngộ, chớ không phải đứng ở vị trí của người mê hoàn toàn. Dám xưng mình là Phật tử, tức con cháu của Phật nghĩa là chúng ta giác ngộ được chút chút, chớ không mê như thuở xưa.

Nhưng nói cho thật rõ, chúng ta giác ngộ được điều gì? Phật dạy sở dĩ chúng sanh không giác ngộ nên trầm luân trong sanh tử. Mê lầm thì trầm luân sanh tử, chỉ có giác ngộ mới giải thoát sanh tử. Chúng ta mê lầm cái gì, giác ngộ cái gì? Đó là điều tối yếu mà toàn thể Phật tử phải biết.

Người phàm phu luôn luôn thấy thân này là thật, còn người Phật tử biết tu thấy thân này là giả. Nhưng e rằng chỉ thấy giả khi tụng kinh, nghe pháp, còn gặp chuyện thì thật ngay. Đó là do chưa thấm nhuần chân lý trong mạch sống của mỗi người, chỉ thấy giả trên mặt suy luận thôi, chớ chưa nhập tâm.

Khi nhìn thấy thân này thật, tự nhiên chúng ta quí trọng nó. Từ quí trọng nên tìm đủ mọi cách cho nó được thụ hưởng sung túc. Tất cả những gì ngon, những gì đẹp, những gì sung sướng trên thế gian đều muốn chu cấp cho nó. Thụ hưởng như vậy là chúng ta đuổi theo dục lạc của thế gian. Ta thử đặt câu hỏi, nếu người thụ hưởng đầy đủ sung mãn mọi dục lạc trên thế gian, người đó có chết không? Thụ hưởng cho nhiều rồi cũng phải chết. Thế thì họ giành giật tất cả mọi thứ trên đời, để cuối cùng chỉ còn một thây thối thôi, có ý nghĩa gì đâu? Thân giả dối mà người ta ngỡ là thật, nên mới giành nhau từng miếng ăn, từng cái mặc. Càng giành thì càng khổ, nên khổ gốc từ mê lầm mà ra, rõ ràng như vậy.

Nếu biết thân này giả tạm, không thật, chúng ta sẽ tùy duyên mà sống, tùy duyên mà tu hành, nên bớt giành giật. Bớt giành giật thì bớt tranh đấu, bớt khổ đau. Nhờ thấy đúng về thân, chúng ta giảm bao nhiêu đau khổ. Biết thân hư giả, khi hết duyên sắp ra đi Phật tử có sợ không? Nó giả tạm thì hư hoại là lẽ thường, có gì phải sợ. Người chấp thân thật, thụ hưởng cho nhiều, khi sắp chết thì hoảng sợ, đắm luyến thân vô cùng Trong khi tranh giành để được thụ hưởng đã là khổ, lúc sắp bỏ thân cũng khổ nữa. Hai ba chặng khổ.

Người biết thân này giả thì cuộc sống rất đơn giản, không tranh hơn về phần mình, nhờ vậy bớt khổ. Khi chết biết đã hết duyên, nó phải đi, ta cười thôi, có gì đâu mà sợ. Hiểu như vậy, thấy như vậy thì đứng trước cái chết chúng ta an ổn, tự tại. Như vậy, giác được một chút là đã bớt khổ bao nhiêu rồi.

Người làm việc lành, giúp đỡ mọi người, cuối cùng cũng chết, người không làm gì hết, cứ lo hưởng thụ rồi cũng chết. Cả hai đều đi đến chỗ chết, nhưng một người chết bao nhiêu người quí, còn một kẻ chết bao nhiêu người ghét. Nên người biết tu ngay nơi thân này sử dụng làm lợi ích cho đời, cho đạo. Người không biết tu cứ cưng dưỡng, không dám nhọc thân, nhưng rốt cuộc rồi cũng chết, không hơn được chút nào. Đó là một lẽ thật.

Người rõ biết thân hư dối tạm bợ, đủ duyên thì còn, thiếu duyên nó tan hoại. Thấy như vậy là thấy được lẽ thật. Thấy được lẽ thật là giác rồi. Đó là giác về thân. Còn giác thứ hai là giác về tâm. Quí Phật tử nghĩ cái này phải, cái kia quấy; ai làm theo điều mình nghĩ thì thương, còn làm ngược lại thì ghét. Ai nói gì mình cho là phải thì quí trọng, nói gì mình cho là quấy thì khinh thường. Nhưng thật ra, cái phải quấy ở đời có là chân lý chưa? Chưa là chân lý. Bởi vì cái phải ở đây không là cái phải ở kia, cái phải của người này không là cái phải của người khác. Người ta thấy cái đó chưa phải mà mình cho là phải, họ cãi lại mình liền giận, liền ghét. Đau khổ từ đó phát sanh.

Chúng ta thử đặt lại vấn đề, phải quấy từ đâu mà ra? Chẳng qua lớp người trước đặt định ra thế này phải, thế kia là quấy, rồi lớp người sau bắt chước theo. Cứ như vậy thế hệ này truyền nối sang thế hệ khác, tùy theo xứ sở chủng tộc mỗi nơi mà lập định phải quấy. Như hiện giờ Quốc hội họp lại định luật thế này thế kia, nếu ai làm khác tức là phạm tội. Nhưng năm mười năm sau sửa lại, thế thì phải quấy ở chỗ nào?

Gần nhất chúng ta quen thuộc với người Pháp. Khi xưa họ cai trị mình, ra đường bắt đi bên phải là đúng, đi bên trái là quấy. Nhưng qua Anh thì ngược lại đi bên trái là phải, đi bên phải là quấy. Như vậy ai đúng? Rõ ràng phải quấy của thế gian không thật. Vậy mà chúng ta chấp, mình nghĩ thế là phải, ai nghĩ khác đi liền giận. Từ đó lôi kéo theo bao nhiêu sự việc nữa. Chấp những suy nghĩ của mình là đúng, nhưng tới khi xảy ra sai thì tự tha thứ được. Còn trước đó ai cãi lại, mình nổi sân lên la mắng người ta.

Như tôi ở trên núi, thấy cụm mây đen từ phía Nam thổi tới, lát sau trời mưa. Ngày mai, thấy cụm mây đen ở phương Nam nữa, tôi liền kêu quí thầy dọn đồ đang phơi vô, vì sẽ có mưa. Nếu ai nghe lời tôi vui, không nghe lời tôi rầy. Không ngờ lát sau gió đổi chiều, cụm mây bay đi, trời không mưa. Như vậy, những gì ta cho là đúng chẳng qua là kinh nghiệm của quá khứ. Nhưng quá khứ bao giờ cũng khác hiện tại. Chuyện hôm qua khác, chuyện hôm nay khác. Song người đời cứ chấp vào kinh nghiệm của quá khứ, cho những suy nghĩ thấy biết của mình đúng, ai nói khác là sai. Từ đó sanh ra cãi vã, phiền não khổ đau.

Thêm một câu hỏi nữa, những nghĩ suy đó có phải thật tâm của chúng ta chưa? Đây là vấn đề khó giải quyết. Tất cả sự hiểu biết của chúng ta thuộc về phần tinh thần, còn thân thuộc về thể xác. Thể xác do duyên hợp, không thật, thì tinh thần tức những hiểu biết, hơn thua, phải quấy, tốt xấu… thật là tâm chưa? Lâu nay chúng ta cứ cho cái nghĩ suy là tâm mình. Nghĩ phải, nghĩ quấy, nghĩ tốt, nghĩ xấu, nghĩ hơn, nghĩ thua… tất cả đều là tâm mình hết. Nếu vậy, ta thử kiểm xem từ khi cha mẹ sanh ra cho tới ngày ta nhắm mắt, là một *“mình”* hay nhiều *“mình”*? Một cái *“ta”* hay nhiều cái *“ta”*?

Nếu nghĩ phải là ta, thì nghĩ quấy là ai? Rồi nghĩ tốt, nghĩ xấu, nghĩ lung tung hết, vậy ta có bao nhiêu cái? Chúng ta tự thừa nhận mình là một từ thủy chí chung, như vậy nhiều thứ suy nghĩ đó là mình sao được. Nói tôi nghĩ thế này, tôi nghĩ thế kia, tôi vui, tôi buồn… đủ thứ. Nó còn nguyên hoài hay đổi thay như chong chóng? Nó đổi thay luôn, đang buồn đó có ai chọc vui thì cười lên. Như vậy cái buồn đi qua, nhường chỗ cho cái vui tới. Rồi đang vui bỗng ai nói gì làm mình tức, nổi giận lên thì hết vui. Cứ thay đổi không dừng làm sao thật ta được. Đó là điều hết sức cụ thể, rõ ràng mà lâu nay chúng ta không biết.

Những suy nghĩ, phân biệt hơn thua phải quấy… thuộc về tâm, nhưng là tâm vọng tưởng, hư dối, không phải tâm chân thật. Vì nếu thật nó phải còn nguyên, chớ không đổi thay luôn như vậy. Chúng ta phải biết để dẹp bỏ, đừng chấp vào những thứ đó, mới thấy được tâm thật của mình. Tâm buồn thương, giận ghét… là dòng sanh diệt không dừng. Đã sanh diệt không dừng mà theo nó là ta chấp nhận đi trong dòng sanh diệt.

Tuy nhiên, bên cạnh tâm hư dối đó có tâm chân thật. Chúng ta phải làm sao phăng cho ra, tìm cho được tâm chân thật ấy. Đó là gốc của sự tu. Như chúng ta ngồi thiền để làm gì? Để bỏ tâm hư dối, cho nó lặng xuống. Tâm hư dối lặng thì tâm chân thật hiện. Đó là giác ngộ được thân này giả dối, tâm suy nghĩ hư dối, thì tâm chân thật hiện bày. Chừng nào tìm và sống được với tâm chân thật trọn vẹn mới gọi là gần giác ngộ viên mãn. Như vậy, chúng ta đang đi trên đường giác ngộ chớ đâu phải thường.

Ở đời, người ta mê chấp thân, mê chấp tâm nên phải luân hồi sanh tử. Vì vậy kinh Viên Giác, Bồ-tát Văn-thù hỏi Phật: *“Cái gì là nhân sanh tử luân hồi?”*. Đức Phật dạy: *“Người chấp thân tứ đại giả hợp là thân thật, chấp tâm hư giả sanh diệt là tâm thật, đó là nhân luân hồi sanh tử”*. Bây giờ chúng ta biết rõ điều này tức đã có giác rồi. Chúng ta tu là thức tỉnh, nên cố gắng để thoát khỏi mê lầm đó. Đây là lý do vì sao chúng ta chuyên tu thiền.

Tu thiền để làm gì? Để dừng, lặng tâm lăng xăng. Tâm lăng xăng lặng xuống thì tâm chân thật hiện đủ. Đó là giác. Giác bằng cách thực hiện ngay nơi mình, chớ không phải tìm kiếm ở đâu khác. Song muốn thực hiện điều này, chúng ta phải đi từng bước.

Bước thứ nhất là sao? Trong các thời khóa tụng của nhà thiền, thường nhất là kinh Bát-nhã. Bát-nhã là tiếng Phạn, Trung Hoa dịch trí tuệ, loại trí tuệ siêu xuất thế gian, chớ không phải trí tuệ thường. Muốn bước vào cửa thiền trước tiên phải thâm nhập lý Bát-nhã. Lý Bát-nhã còn được gọi là cửa Không. Sắc tức thị Không, Không tức thị Sắc. Tại sao chúng ta tu thiền phải đi từ cửa Không? Vì nếu thấy thân này thật, đối với ngoại cảnh, từ con người cho tới muôn vật, chúng ta đều thấy thật hết thì tâm sẽ chạy theo nó.

Bây giờ, muốn tâm không chạy theo, chúng ta phải quán sát kỹ tất cả sự vật ở ngoài cũng do duyên hợp, không thật. Cái nhà từ khoảnh đất trống, ta dựng cây cối, gạch ngói v.v… để thành cái nhà. Do vậy cái nhà là tướng duyên hợp. Do duyên hợp nên có ngày nó phải bại hoại, tường vách đổ sụp. Những gì duyên hợp đều hư dối. Từ cái nhà cho đến mọi sự mọi vật, có thứ nào không phải duyên hợp đâu, nên chúng sẽ đi đến bại hoại. Biết rõ như vậy mới không dính mắc với cảnh bên ngoài. Không dính mắc ngoại cảnh thì tâm mới an định được, còn dính mắc thì không bao giờ an định.

Tôi nói thí dụ như quí Phật tử vừa mới to tiếng với ai đó chừng nửa giờ, bây giờ vô ngồi thiền có yên không? Vừa ngồi vừa tiếp tục cãi, không cãi bằng miệngmà cãi bằng tâm. Họ nói câu đó là sao? Mình phải trả lời sao cho xứng v.v… cứ ôn tới ôn lui hoài. Vì chúng ta thấy câu nói thật nên không bỏ được. Nếu ta quán con người đó không thật thì lời nói của họ có thật đâu, tất cả là chuyện rỗng, có gì quan trọng. Thấy vậy liền buông nhẹ. Buông được thì ngồi thiền mới yên. Cho nên trước tiên bước vào cửa thiền, chúng ta phải đi từ lý Bát-nhã, dẹp bỏ tất cả những cái cố chấp của mình.

Kinh Bát-nhã nói: *“Sắc tức là Không, Không tức là Sắc”* nghĩa thế nào? Đa số người thế gian không hiểu nổi câu này. Bây giờ tôi dẫn câu chuyện xưa thế này. Đời Đường, có hai vị Thiền sư trẻ Trí Tạng và Huệ Tạng, đệ tử của Mã Tổ Đạo Nhất. Một hôm hai huynh đệ ra ngoài vườn chơi. Ngài Trí Tạng hỏi ngài Huệ Tạng:

\- Sư đệ biết bắt hư không chăng?

Ngài Huệ Tạng trả lời:

\- Biết.

\- Làm sao bắt?

Ngài Huệ Tạng liền đưa tay ra ôm hư không. Ngài Trí Tạng quở:

\- Bắt như vậy làm sao được hư không?

Ngài Huệ Tạng hỏi:

\- Huynh làm sao bắt?

Ngài Trí Tạng liền nắm lấy lỗ mũi Huệ Tạng lôi đi. Ngài Huệ Tạng la:

\- Nắm như vậy chết người ta, buông ra!

Ngài Trí Tạng nói:

\- Bắt như vậy mới được hư không.

Câu chuyện này có đạo lý gì không? Lỗ mũi tuy là hình thức vật chất, nhưng bên trong trống rỗng. Nắm cái sắc thì trong đó đã có cái không rồi. Đây là nghĩa Sắc tức thị Không. Nếu ôm hư không bên ngoài thì làm sao nắm được hư không? Như bình hoa trước mắt chúng ta, nếu bỏ mấy cọng hoa mỗi nơi mỗi cái thì bình hoa không còn. *“Bình hoa”* là giả danh, do đủ duyên hợp lại mới có, nếu thiếu duyên bình hoa không còn nữa. Nên nói thể bình hoa là không, do duyên hợp tạm có. Ngay nơi bình hoa chúng ta biết tánh nó là không. Tuy Tánh không nhưng đủ duyên hợp lại thì thành bình hoa.

Như vậy lý Không ở đây không phải không ngơ, mà là không có chủ thể cố định. Duyên hợp tạm có, duyên ly tán trở về không. Hoa khi phân tán khắp nơi, chỉ còn lại bình không, nếu ta cặm vào đó các hoa khác thì có bình hoa trở lại, nên nói *“Không tức là Sắc”*. Rõ ràng sắc và không đều không thật. Nói sắc nói không nhằm chỉ ra lý duyên hợp, đủ duyên thì không biến thành sắc, thiếu duyên thì sắc biến thành không. Nên ngay khi duyên hợp, tánh nó vẫn là không. Vì vậy kinh Bát-nhã nói *“không”* tất cả: không nhãn, nhĩ, tỹ, thiệt, thân; không sắc, thanh, hương… Không là nói đến thể của tất cả các pháp. Tất cả pháp chỉ có giả danh, không có Thật thể.

Từ đó chúng ta dùng trí quán xét hết các sự vật bên ngoài, đều là duyên hợp Tánh không. Biết như thế là tỉnh, hết mê. Cho nên biết được lý Tánh không rồi, chúng ta mới bỏ được vọng tưởng điên đảo, các vị Bồ-tát mới có thể tu hành tiến lên thành Phật. Dùng Trí tuệ Bát-nhã tức là dùng thanh kiếm bén ruồng hết sáu trần, không chấp không kẹt. Không chấp thì ngồi thiền êm ru, không nghĩ, không tính. Vừa chợt nhớ gì liền tự nhắc: *“Nó giả dối, có thật đâu mà nhớ”*.

Thế nên bước vào cửa Không phải thấy rõ: Một, tất cả cảnh sắc đều hư dối, Tự tánh là không. Hai, thân tứ đại duyên hợp hư dối, Tự tánh là không. Ba, tâm vọng tưởng sanh diệt hư dối, Tự tánh là không. Biết ba cái đó không thật rồi, chúng ta phải tìm cho ra cái chân thật. Đây là chỗ thiết yếu hành giả tu thiền cần phải biết. Cái thật đó lâu nay chúng ta không nhớ không biết nên chạy theo trăm thứ đảo điên. Bây giờ ta phải nhớ để nhận ra và sống lại với cái chân thật của chính mình, thì mới chấm dứt sanh tử và đau khổ.

Như câu chuyện đức Phật kể trong kinh Lăng Nghiêm: Một buổi sáng, có anh chàng Diễn-nhã-đạt-đa đứng trước gương soi mặt, anh thấy mặt mày mình hiện rõ trong đó. Khi úp gương xuống, anh không thấy mặt mình nữa, liền chạy la hoảng: *“Tôi mất đầu rồi. Tôi mất đầu rồi!”*. Phật nói Diễn-nhã-đạt-đa ôm đầu chạy la mất đầu, có phải điên không? Tại sao anh điên? Vì anh lầm bóng trong gương là đầu thật, nên quên mất đầu thật của mình.

Chúng ta có giống Diễn-nhã-đạt-đa không? Khi nghĩ suy ta thầm cho đó là *“tâm tôi”*, khi không nghĩ suy thì không có tâm. Nghĩ suy là bóng, mình nghĩ về người thì bóng người hiện ra, nghĩ về vật bóng vật hiện ra. Hết nghĩ suy thì tâm lặng, rõ ràng chúng ta có cái thật nhưng lại không thấy, chỉ thấy toàn là bóng. Vì nhận bóng là mình nên quên cái thật, giống như Diễn-nhã-đạt-đa nhớ bóng quên đầu, đó là điên. Tâm thật luôn có mặt trong hiện tại, không bao giờ vắng thiếu mà ta lại không nhận, đi nhận những thứ lăng xăng chợt có chợt không là tâm mình, như vậy không phải điên là gì?

Trong kinh Lăng Nghiêm, đức Phật đưa cánh tay lên hỏi A-nan:

\- Ông thấy không?

Ngài A-nan trả lời:

\- Dạ thấy.

Phật để tay xuống, hỏi:

\- Ông có thấy không?

\- Dạ không thấy.

Phật quở:

\- Ông là người quên mình theo vật.

Tại sao Phật quở ngài A-nan *“quên mình theo vật”*? Vì tay của Phật ở bên ngoài, còn thấy cái tay là cái thấy của ngài A-nan. Khi Phật để tay xuống là thấy không có tay, chớ không phải không thấy. Thấy là cái của mình, nếu nói không thấy tức là mất mình rồi. Vật bên ngoài khi có khi không, chớ cái hay thấy hay biết của mình luôn luôn hiện hữu. Do đó Phật mới quở ngài A-nan *“quên mình theo vật”*.

Chúng ta có quên mình theo vật không? Cứ lo chạy theo vật mà quên mất mình hồi nào không hay. Phật bảo có cảnh thì nói thấy, không cảnh thì nói không thấy, đó là quên mình. Vì thấy là cái của mình, còn cảnh bên ngoài dù có hay không cũng chỉ là cảnh, không phải mình. Nếu cho vật là cái thấy, không phải quên mất mình sao? Nghiệm lại lâu nay chúng ta lầm lẫn vô kể, sống theo cái giả, không biết mình đang có cái thật. Bởi vì Tánh thấy đó không tướng mạo, không sanh diệt nên chúng ta khó thấy khó nhận. Chỉ khéo đừng chạy theo cảnh bên ngoài, xoay trở lại mình mới có thể nhận ra.

Phật bảo La-hầu-la đánh một tiếng chuông *“boong”*, rồi hỏi A-nan:

\- Ông có nghe không?

Ngài trả lời:

\- Dạ nghe.

Một lát sau tiếng chuông lặng, Phật hỏi:

\- Ông có nghe không?

A-nan thưa:

\- Dạ không nghe.

Phật quở thêm một lần nữa:

\- Ông quên mình theo vật.

Tại sao vậy? Vì tiếng chuông có thì nghe có tiếng, tiếng chuông lặng thì nghe không tiếng, tại sao lại nói *“không nghe”*? Tai lúc nào cũng nghe, chỉ tiếng mới khi có khi không. Phật chỉ cho chúng ta thấy nơi mắt, tai, mũi, lưỡi v.v… có cái thấy thường trực, cái nghe thường trực, cái biết thường trực mà không động, không sanh diệt. Nhưng chúng ta quen chạy theo cảnh vật bên ngoài mà quên Tánh biết hiện tiền. Đó là sai lầm lớn nên Phật gọi chúng sanh si mê.

Trong nhà thiền có câu chuyện thế này. Mã Tổ Đạo Nhất là Thiền sư nổi tiếng, sau Lục Tổ hai đời. Một hôm, Ngài đi dạo vườn với thầy Thị giả Hoài Hải. Lúc ấy thấy một bầy vịt trời bay ngang, Mã Tổ hỏi:

\- Cái gì đó?

Ngài Hoài Hải đáp:

\- Bầy vịt trời bay ngang.

Lát sau, Mã Tổ hỏi:

\- Bay đâu rồi?

Ngài Hoài Hải thưa:

\- Bay qua mất rồi.

Mã Tổ liền nắm lỗ mũi ngài Hoài Hải véo một cái thật mạnh, đau điếng Ngài la lên:

\- Chết cái lỗ mũi của con.

Mã Tổ liền nói:

\- Sao không nói bay mất đi?

Ngang đó ngài Hoài Hải đại ngộ.

Ngài ngộ cái gì? Ngộ cái lỗ mũi đau phải không? Trong nhà thiền có rất nhiều chuyện kỳ đặc, người thường đọc không hiểu. Nhìn thấy bầy chim bay qua, Mã Tổ hỏi *“cái gì”*, thầy Thị giả đáp *“bầy chim bay qua”*. Lát sau Tổ lại hỏi: *“Bay đâu rồi?”*. Thị giả trả lời: *“Bay mất rồi”*. Trả lời như vậy là nhớ vật quên mình. Vì vậy Mã Tổ véo cho một cái đau điếng, khiến Hoài Hải phải la lên, Mã Tổ chỉ thẳng: *“Sao không nói bay mất đi?”*. Rõ ràng thường biết mà lại nói qua mất rồi. Cái thấy, cái biết của ông hiện tiền đây thì không nhận, chạy theo bầy vịt trời nên qua mất rồi! Chỗ này hay đáo để.

Như vậy để chứng minh lúc nào chúng ta cũng thấy cũng nghe. Vật bên ngoài tới lui qua lại nhưng ta có mất lúc nào đâu? Tất cả quí vị hiện ở đây có ai không thấy, không nghe đâu. Thấy nghe rõ ràng mà không cần suy nghĩ. Đó là cái chân thật hiện tiền, không động, có sẵn nơi mỗi chúng ta. Chỉ vì lâu nay mình cứ cho nghĩ suy là tâm nên quên mất tâm thật. Chấp thân là mình, chấp suy nghĩ phân biệt làm tâm mình, đó là gốc luân hồi sanh tử. Muốn ra khỏi luân hồi sanh tử phải bỏ hết các thứ chấp ấy đi.

Mỗi ngày chúng ta ngồi thiền là để từng bước từng bước làm công việc ấy. Biết vọng, không theo tức là loại bỏ chúng. Công phu như thế từ từ vọng tưởng lặng. Nhiều người than phiền vọng tưởng mạnh quá, nhiều quá bỏ hoài không hết. Chúng ta nên nhớ mình đã huân sâu vọng tưởng từ bao nhiêu đời rồi, bây giờ muốn sạch liền đâu được. Nhất là những gì ta thích hoặc ghét. Ví dụ ai làm ta đau khổ, mình lặng thinh hay kể cho người này người kia nghe? Kể cho nhiều người nghe. Mỗi lần kể là mỗi lần ôn lại, càng kể càng nhớ sâu thêm. Cũng như khi nhỏ ta học bài, đọc một lần không thuộc, phải đọc hai ba lần, có khi cả chục lần mới thuộc. Và một khi đã thuộc rồi thì bỏ rất khó, muốn quên đi mà vẫn cứ nhớ, tại vì mình huân nhiều quá. Cho nên muốn bỏ cũng phải tập, bỏ hoài bỏ hoài, lâu ngày mới hết.

Cũng vậy, những vui buồn chúng ta đem ra kể cho cha mẹ nghe là khắn vào tâm não một lần, kể cho anh em nghe là khắn thêm hai lần. Cứ thế kể cho bạn bè, bà con láng giềng nghe, ôn đi ôn lại càng nhiều thì thấm càng sâu trong tâm não. Vì vậy khi ngồi yên nó trồi lên, ta *“bỏ”* chẳng bao lâu nó trồi lên nữa, ta than phiền tại sao bỏ hoài không hết! Mình thu vô một trăm lần thì đuổi ra ít nhất cũng phải tám, chín chục lần mới hết chứ. Sao lúc thu vô nhiều không than phiền, khi đuổi lâu hết lại không chịu. Có phải mình vô lý không?

Những buồn đau, giận hờn… xảy đến ta cứ chứa chấp sâu trong kho Tàng thức, bây giờ muốn loại trừ phải từ từ. Năm này một ít, năm kia một ít nó mới sạch, chớ không phải một lần sạch liền. Vì vậy ngồi thiền là cốt loại những bóng dáng của quá khứ còn lưu lại trong tâm, khiến nó tan mất đi. Chúng hết rồi thì cái chân thật hiện tiền, hằng tri hằng giác của mình hiện bày. Tri giác ấy là tánh Phật. Chư Phật ra đời mục đích để chỉ dạy cho chúng ta bấy nhiêu đó thôi.

Nhận ra tánh Phật hằng tri hằng giác, không suy nghĩ, không thương ghét, không hơn thua là dứt tạo nghiệp thiện ác. Không tạo nghiệp thiện ác thì đâu có luân hồi sanh tử. Đó là nhân giải thoát. Như vậy tu là giác ngộ, biết mình có cái thật phải nhận lại, cái giả bỏ đi. Bỏ được những thứ hư dối, sống hoàn toàn với Tâm chân thật là giác ngộ. Giác ngộ là giải thoát sanh tử.

Như vậy, tu là trở về cái thật sẵn có nơi mình, không phải từ đâu đến, cũng không do ai ban cho. Trong kinh thường nhắc chúng ta có hòn ngọc quí, phải thức tỉnh nhận lại để dùng. Đó là tu. Chúng ta tu là từng bước đi trên con đường giác ngộ. Trước là giác ngộ cảnh bên ngoài không thật. Kế đến giác ngộ thân này do duyên hợp tạm có, không thật. Và giác ngộ sau cuối là biết những nghĩ suy hơn thua phải quấy cũng hư dối, không thật. Biết rõ không lầm như thế rồi sẽ nhận ra được cái chân thật của mình. Đó là giác ngộ hoàn toàn.

Chúng ta cứ đúng theo đạo lý Phật dạy mà tu. Tu lâu ngày mọi thứ khổ đau mê lầm sẽ giảm. Khi nào hết mê lầm tức là chúng ta được giác ngộ viên mãn. Như vậy mới xứng đáng là Phật tử tức con của Phật. Tu là để giải thoát sanh tử, chớ không phải cứ đi mãi trong mê lầm. Vì vậy Phật tử gặp Phật pháp, được quí thầy nhắc nhở tu hành là có phước lớn, chớ không phải thường. Nếu không sẽ chìm mãi trong biển khổ sanh tử, đeo đuổi theo những thứ tạm bợ của thế gian, chịu nhiều đau khổ không biết đến bao giờ mới hết!

Vì thế người biết tu thương tất cả mọi người, không thù ghét ai hết, bởi họ cũng mê lầm giống mình, đuổi theo bóng dáng hư ảo rồi gây khổ cho nhau. Nên giác ngộ rồi tự nhiên phát lòng từ bi. Lúc chưa giác ngộ mà khởi lòng từ bi, e đó chưa phải thật là từ bi. Đó là điều chúng ta phải lưu ý, để không bị lầm lẫn trong lúc dụng công tu. Mong tất cả hiểu được mục đích tu hành của mình để đạt được kết quả như sở nguyện.
