# Lòng tin của người con Phật {- #long-tin-cua-nguoi-con-phat}

<div class="align-right">
*Chùa Sùng Ân – Phan Rang, 2002*
</div>

Vì muốn cho tất cả Tăng Ni Phật tử đều hiểu đạo theo đúng tinh thần của đạo Phật, nên hôm nay chúng tôi giảng dạy đề tài Lòng tin của người con Phật.

Con Phật ở đây là hàng xuất gia cũng như các Phật tử cư sĩ tại gia. Chúng ta nghe nhận giáo pháp của Phật khéo hiểu, đó là con đường tu thực tế của bản thân, cũng như hướng dẫn chỉ dạy cho mọi người đồng chí hướng tu hành. Vậy lòng tin của người Phật tử là gì? Là tin Tam bảo, tức tin Phật, tin Pháp, tin Tăng. Lòng tin ấy đối với Phật tử dễ tin hay khó tin?

Trước hết nói về tin Phật. Tin Phật là tin như thế nào? Lâu nay chúng ta cứ ngỡ tin vào đức Phật là tin Ngài có đủ tất cả pháp nhiệm mầu, đủ công đức vô lượng vô biên. Chúng ta tin tưởng ở Ngài thì sẽ ban bố phước lành cho mình, sẽ gia hộ cho ta bình an, hạnh phúc. Nhưng sự thật không phải, chúng ta tin Phật vì Ngài là bậc giác ngộ. Chữ Phật nói đủ là Phật đà có nghĩa là bậc giác ngộ viên mãn. Vì giác ngộ viên mãn nên những gì Ngài chỉ dạy cho chúng ta đều là chân lý không xê dịch, không đổi khác theo thời gian không gian.

Vậy chúng ta tin Phật là tin bậc giác ngộ, một bậc sẽ đưa ta đến chỗ sáng suốt, chớ không phải tin bằng ân huệ Ngài ban cho. Trong kinh Phật thường dạy:

> Ta không có quyền ban phước xuống họa cho ai.

Ngài đã không có quyền ban phước xuống họa thì ta xin được phước, xin khỏi họa được không? Xin như vậy là trái với chủ trương, trái với lẽ thật đức Phật đã dạy.

Ai đọc sử cũng nhớ, đêm thứ bốn mươi chín ngồi dưới cội Bồ-đề, đức Phật thiền định từ canh một tới canh hai chứng được Túc mạng minh, từ canh hai tới canh ba chứng được Thiên nhãn minh, từ canh ba tới canh năm chứng được Lậu tận minh. Từ chỗ tu chứng ấy, những gì thấy biết Ngài nói lại cho chúng ta nghe đều là chân lý, là sự thấu triệt nguồn gốc của con người và muôn vật.           

Chúng ta ai cũng thắc mắc tự nghĩ, không biết mình từ đâu đến đây, chết rồi đi về đâu? Đức Phật sau khi đã chứng Túc mạng minh, Ngài thấu suốt được sanh mạng của bản thân mình từ vô số kiếp trở về trước, chớ không phải năm đời mười đời thôi. Trong các kinh A-hàm còn ghi lại lời Thế Tôn nói:

> Ta nhớ vô số kiếp về trước như người nhớ việc mới xảy ra hôm qua.

Nhớ rõ ràng không có gì sai sót. Do đó Ngài biết được ta từ đâu đến đây.

Chứng được Thiên nhãn minh, Ngài có con mắt sáng thấy thấu suốt từ những vật rất xa cho tới những vật rất nhỏ nhiệm, mà con mắt phàm chúng ta không thể thấy được. Ngài thấy rõ con người khi chết rồi, sẽ theo nghiệp dẫn luân hồi trong lục đạo, chúng sanh bị lôi kéo đi theo nghiệp của mình đã tạo. Trong lục đạo luân hồi có ba đường lành và ba đường dữ. Ba đường lành là người, a-tu-la và trời; ba đường dữ là địa ngục, ngạ quỹ và súc sanh.

Nếu người nghiệp thiện khi nhắm mắt sẽ đi theo ba đường lành. Nếu người nghiệp xấu ác, khi nhắm mắt sẽ đi ba đường dữ, chớ không phải chết là hết. Do thấy như vậy nên đức Phật nói:

> Ta thấy chúng sanh đi trong luân hồi lục đạo như người đứng trên lầu cao nhìn xuống ngã tư đường thấy kẻ qua, người lại rõ ràng không lầm lẫn.

Đức Phật thấy rõ dòng luân hồi của chúng sanh từ đời này tới đời kia không dừng, không hết nên Ngài mới dạy chúng ta cách tu để thoát khỏi dòng luân hồi ấy.

Đến canh năm khi sao mai vừa mọc, Phật chứng Lậu tận minh. Lậu tận minh là thấu tột được nguyên nhân nào khiến cho chúng sanh trầm luân trong sanh tử và phương pháp nào đưa chúng sanh ra khỏi vòng luân hồi ấy, không còn buộc ràng trong lục đạo nữa. Biết rõ nhân biết quả như vậy nên Ngài dạy chúng ta cách tu hành thoát ly sanh tử.

Phật không bắt chúng ta nhất quyết phải tin, mà mình có quyền kiểm nghiệm lại xem điều nào đáng tin thì tin, điều nào không đáng tin thì thôi. Thứ nhất, đức Phật thấy được con người từ vô số kiếp về trước đã từng sanh nơi này, nơi kia rồi mới đến đây. Chúng ta tự kiểm lại, xem mình có mang tính cách gì của quá khứ dẫn đến hiện tại không? Như trong một gia đình cùng cha cùng mẹ sanh ra, nhưng những người con có đứa sáng suốt thông minh, có đứa lại khù khờ u tối. Hoặc có đứa đẹp, có đứa xấu v.v… không giống nhau. Tại sao lại có sự sai biệt như thế?

Nói theo khoa học hiện nay, tất cả mầm sanh ra con người đều từ gien của cha mẹ. Gien cha mẹ thế nào thì người con cũng giống như thế ấy. Nếu do gien cha mẹ sanh ra, tại sao mỗi người lại mang hình dáng khác nhau, tâm tư khác nhau, trí tuệ khác nhau. Đó là từ đâu? Nhà Phật dạy rằng chúng ta có mặt ở đây là do tích lũy nghiệp của đời trước. Đời trước ta đã từng làm gì thì đời này sanh ra ảnh hưởng nghiệp của đời trước.

Như hiện giờ chúng ta nghe những vị thần đồng trên thế giới, có vị giỏi về âm nhạc từ lúc năm bảy tuổi, có vị giỏi toán từ lúc chín mười tuổi, có vị giỏi văn chương v.v… Đó là do ai dạy? Điều này chứng tỏ thuyết nhân quả của nhà Phật không sai. Đời trước chúng ta đã từng làm việc lành dữ nào, đời này sanh ra chủng tử nghiệp của quá khứ còn nên ảnh hưởng tới đời này. Vì vậy mỗi người ra đời mang theo những tâm tư, ý niệm, thói quen khác nhau. Bởi thế không thể giống hệt cha mẹ, chỉ giống phần nào do tính di truyền của gien thôi. Đó là một lẽ thật không nghi ngờ gì cả.

Đức Phật thấy biết rõ, nhưng nói ra quá tầm hiểu biết của chúng ta, có khi mình chưa dám tin. Nhưng kiểm nghiệm lại thật kỹ, rõ ràng đó là một lẽ thật, không nghi ngờ. Như tất cả người thế gian lớn lên đều nghĩ tới chuyện đôi bạn hoặc tạo dựng sự nghiệp cho khá giả… Nhưng có người lớn lên đòi đi tu. Điều này ai dạy? Cha mẹ không dạy, thầy cô giáo không dạy. Như vậy chủng tử tu trước đã có nên bây giờ không ai xúi giục, không ai bắt buộc mà tự phát nguyện đi tu. Chúng ta hiểu rồi thì biết những việc này không phải mới có, mà nó đã có từ thuở nào.

Sau khi thấy tột lý đó rồi, Phật mới dạy chúng ta làm sao trong đời này tu tạo những nghiệp lành, để khi nhắm mắt sanh vào cõi lành. Không phải chết rồi hết, đừng nghĩ lầm như vậy. Người thế gian cứ ngỡ chết là hết, nên nhiều vị còn trẻ tuổi khi gặp điều gì bức bách, không chịu nổi đòi tự tử. Vì họ ngỡ rằng tự tử là giải quyết xong việc đời này, không ngờ tự tử rồi lại càng khổ sở dai dẳng hơn đời này nữa.

Quí vị vô chùa thấy tượng Phật, tượng Tổ có hào quang phía sau đỉnh đầu. Hào quang là ánh sáng, đó là biểu hiện cho nghiệp lành tỏa ra. Những người hung ác nghiệp dữ cũng tỏa ra. Nhưng với con mắt chúng ta, khả năng giới hạn quá nên không thể thấy được. Lạ một điều, đôi khi con mèo, con chó lại có thể nhận được năng lượng tỏa ra từ những người hung ác. Chúng ta để ý sẽ thấy mấy người làm hàng thịt, khi vào xóm dù họ  không đem theo dụng cụ bắt heo bắt chó, mà chó thấy là sủa rùm hết. Chúng sủa một cách oán ghét, giận dữ, chớ không phải sủa như sủa khách bình thường. Đó là do ác nghiệp của họ tỏa ra khiến những loài cũng có nghiệp xấu nhìn thấy được.

Đức Phật thấy ngoài vũ trụ có vô số thế giới. Ngài nói nhưng không bắt buộc chúng ta tin hay không tin. Phật thấy sao thì nói vậy thôi. Ngày nay chúng ta thấy rõ ràng trong bầu hư không này không phải chỉ có một thế giới của mình, mà có vô số thế giới. Đã là vô số thế giới thì có thế giới nhỏ, có thế giới lớn, có thế giới tốt, có thế giới xấu. Con người sanh trong những thế giới đó nhất định phải có sai biệt, tốt xấu đủ thứ. Suy gẫm như thế, chúng ta không còn gì để ngờ vực về trí tuệ của Như Lai nữa.

Lời Phật dạy do Ngài tu mà thấy, đó là một lẽ thật chớ không phải lời huyễn hoặc. Ngày xưa trình độ khoa học còn thấp kém, người ta không hiểu nổi những gì Thế Tôn thấy biết và nói ra. Ngày nay khoa học từ từ có nhiều phát minh, chúng ta mới tin lời Phật nói là có thật. Sở dĩ đức Phật nói ra những điều đó là để cho chúng ta biết mà tu, chớ không phải nói ra để khoe sự thấy biết sâu rộng của Ngài.

Phật thấy chúng sanh theo nghiệp luân hồi chịu quả báo khổ vui, nên nói những bài kinh dạy về nhân quả nghiệp báo luân hồi. Nếu dứt sạch những nghiệp duyên này sẽ thoát khỏi sanh tử. Người tu phải biết không có gì xảy ra ngoài nhân quả hết. Biết được quả khổ thì truy nguyên ra nhân để phá dẹp nó. Phá dẹp được nhân rồi thì quả khổ theo đó hết.

Như vậy chúng ta tin Phật là tin qua những lẽ thật Ngài đã trình bày, tin ở sự tu hành giác ngộ viên mãn của Ngài, nên những gì đức Phật nói ra không sai lệch. Đó là niềm tin thứ nhất, tin Phật.

Thứ hai là tin pháp của Phật. Pháp của Phật dạy chúng ta tu về lý nhân quả, lý luân hồi, lý nhân duyên rất rõ ràng, rất khoa học. Như nói gieo nhân thì gặt quả. Người làm nghề nông lựa giống tốt, sửa soạn đất sạch, nước phân đầy đủ rồi gieo giống xuống. Giống tốt nên cây lúa tốt, bông lúa nặng trĩu, nhiều hạt v.v… Từ hạt giống tốt đem lại quả tốt là điều tất nhiên, không ai chối cãi được. Chúng ta không thể nói rằng, muốn trúng mùa không cần lựa giống tốt, không chăm sóc kỹ, không làm cỏ bón phân, cứ mỗi ngày ra ngoài bờ ruộng chắp tay nguyện Phật trời cho con mùa lúa trúng! Không chịu gieo giống, không chịu tạo nhân mà đòi có quả thì không bao giờ có được. Đó là lẽ thật.

Muốn được quả tốt, chúng ta phải tạo nhân tốt và những duyên phụ thuộc cũng phải tốt mới được. Từ lý nhân quả này, chúng ta xét thấy mọi việc trên thế gian không có gì xảy ra một cách bỗng dưng. Phải đi từ nhân tới quả. Nhân mình làm tốt thì quả tốt, nhân mình làm xấu thì quả xấu. Biết được nhân quả rồi, chúng ta nên ngừa đón từ nhân. Không tạo nhân xấu mà tạo nhân tốt, không tạo nhân dữ mà tạo nhân hiền. Đó là người biết tu.

Người sáng suốt chọn nhân tốt để gầy dựng cho cuộc đời mình được kết quả tốt. Chẳng những tốt trong đời này mà tốt ở đời sau nữa. Ngược lại, người không biết tu, chẳng những không chọn nhân tốt, mà còn tạo nhân xấu ác, thì quả xấu ác sẽ đến không nghi ngờ. Tất cả Phật tử hiểu rồi, y cứ theo lời Phật dạy về nhân quả mà sống cho mình, cho mọi người. Làm việc gì chúng ta cũng lấy nhân quả làm chuẩn thì lợi ích vô cùng.

Thế gian nhiều người gây nhân mà không dám lãnh quả. Ví dụ đứa bé lỡ làm bể cái chén đẹp của cha mẹ. Nó không dám nhận lỗi nên đem giấu, khi cha mẹ hỏi nó không dám chịu, nên đổ thừa người này người kia, làm rối rắm nhiều người. Chúng ta đã lỡ tạo nhân thì phải chịu quả, phải can đảm nhận lỗi của mình: Đây là lỗi của con, con lỡ như vậy, xin cha mẹ thương tha thứ cho. Biết nhận lỗi như vậy, cha mẹ nào chẳng thương yêu tha thứ, khỏi phiền hà anh em, khỏi nghi ngờ người này người nọ, có phải tốt không.

Thế nên người tin được nhân quả là người can đảm, còn người không tin nhân quả là người khiếp nhược, yếu đuối. Người hiểu được lý nhân quả cuộc sống rất an lành, rất tự tại, vì dám làm dám chịu, không bao giờ trốn tránh. Như vậy xã hội tốt đẹp biết mấy. Đó là nói về tin nhân quả.

Kế nữa, nếu tin được lý luân hồi chúng ta lại càng dè dặt hơn. Như muốn đời sau bằng và tốt hơn đời này, chúng ta phải giữ tròn năm giới: không sát sanh, không trộm cướp, không tà dâm, không nói dối, không uống rượu say, không hút á phiện xì ke ma túy. Giữ được năm điều đó bảo đảm đời sau trở lại làm người bằng hoặc tốt hơn đời này. Chúng ta tu là để tròn tư cách một con người tốt trong đời này và cả đời sau. Vì vậy nói tu là nói đến chuyện thực tế, chớ không phải nói chuyện viễn vong, huyền ảo. Nhiều người không hiểu cho rằng tu là tiêu cực, huyền bí. Đó là một sai lầm.

Người không sát sanh đời sau tuổi thọ dài. Không trộm cướp đời sau có của nhiều. Không tà dâm đời sau đẹp đẽ trang nghiêm. Không nói dối đời sau nói năng lưu loát, nói ra mọi người đều tin quí. Không uống rượu say, không hút á phiện xì ke ma túy đời sau sanh ra trí tuệ đầy đủ. Như vậy bảo đảm một tương lai tốt đẹp cho mình quá. Còn những kẻ không biết thì đâu có tu, nên đời sau họ sẽ khổ. Vì vậy tu nhân là điều thiết yếu.

Gia đình nào người chồng hoặc vợ không giữ tròn năm giới, gia đình đó có vui không? Trong nhà có kẻ trộm cướp hoặc say sưa, hút á phiện xì ke ma túy… Đó là họa lớn. Cho nên biết tu là đem lại hạnh phúc cho mình và an ninh trật tự cho xã hội. Nếu xóm làng nào mọi gia đình đều biết giữ năm giới thì xóm làng đó chắc chắn bình yên vô cùng, nhà khỏi đóng cửa cũng không sợ mất đồ. Cho nên tu Phật là vấn đề cần thiết cho con người mà ít ai để ý tới.

Chúng ta nhờ tin được lời Phật dạy, tức tin pháp nên ứng dụng tu, đạt kết quả thiết thực trong cuộc sống. Qua đó ta mới thấy lời Phật dạy là một lẽ thật, ứng dụng tu có kết quả tốt cho bản thân và mọi người, cho đời này và cả đời sau. Đó là nói về tin pháp.

Thứ ba là tin Tăng. Chỗ này chúng ta nên dè dặt một chút. Phật dạy đối với Tam bảo Phật, Pháp, Tăng ta phải tin trọn vẹn. Nhưng với tôi, Tăng bảo chúng ta nên tin một cách có chọn lọc. Tại sao? Bởi vì thời đức Phật còn tại thế, Ngài biết căn cơ, tâm tánh của mọi người, nên khi đi giáo hóa gặp ai có cơ duyên, Ngài dạy xong họ nhận hiểu và ứng dụng rất mau ngộ đạo. Vì vậy thời Phật trực tiếp giáo hóa Tăng Ni cũng như Phật tử được gọi là thời chánh pháp, một trăm người tu thì một trăm người ngộ đạo.

Sau khi Phật nhập Niết-bàn rồi, hàng đệ tử của Ngài, có vị chứng A-la-hán nhưng có vị chưa chứng, nên sự dạy dỗ không đúng như chỗ thấy của Phật. Do các Ngài không biết rõ căn cơ, nên pháp dành cho người này lại dạy lệch qua người khác. Điển hình như lúc Phật còn tại thế, Tôn giả A-nan đi giáo hóa có một người thợ rèn qui y với ngài. Tôn giả dạy ông pháp tu quán bất tịnh. Đến nơi khác lại có một người giữ nghĩa địa qui y với ngài, Tôn giả dạy pháp tu quán hơi thở. Hai ông tu hoài không tiến, mới than: Sao thầy dạy con tu không tiến chút nào hết! Ngài liền kể lại tự sự cho Phật nghe và xin thỉnh giáo.

Phật bảo: Tại ông dạy sai, chớ không phải tại họ tu sai. Ông phải dạy lại. Người thợ rèn nên dạy quán hơi thở, vì họ thổi ống bể phì phịch hoài, quán hơi thở sẽ nhịp nhàng với công việc, tu như thế mau tiến hơn. Người giữ nghĩa địa thường thấy thây chết, nên dạy quán bất tịnh mới có kết quả. Ngài nghe lời dạy của Thế Tôn, đem dạy lại hai vị đệ tử của mình. Quả nhiên, chẳng bao lâu cả hai đều tu có kết quả.

Như vậy mới thấy việc dạy người tu mà ta không nắm vững trình độ, căn cơ, nghề nghiệp của họ, đôi khi dạy không có kết quả. Đã không kết quả tất nhiên người tu khó đạt được đạo quả mà họ mong đợi.

Năm trăm năm sau khi Phật nhập diệt là thời Tượng pháp. Tượng là tương tợ. Hồi Phật tại thế thì trăm người tu trăm người ngộ, đến thời Tượng pháp, trăm người tu chỉ có năm chục người ngộ thôi. Rồi một ngàn năm sau khi Phật nhập Niết bàn là thời Mạt pháp. Thời này người tu chứng đạo quá ít, nên làm sao dạy đệ tử chứng được. Vì vậy một muôn người tu, may ra chỉ có một người ngộ thôi.

Từ chánh pháp một trăm người tu một trăm người ngộ, đến tượng pháp một trăm người tu năm mươi người ngộ, đến mạt pháp một muôn người tu chỉ có một người ngộ. Như vậy số người tu đông mà ngộ ít, bắt buộc chúng ta phải lựa chọn thôi. Vì vậy đối với Tăng bảo trong thời này cần chọn lọc kỹ một chút. Nhiều khi có vị truyền giới cho đệ tử, không được uống rượu mà bản thân mình lại uống hết chai này đến chai khác. Như vậy ai tin được? Buộc lòng chúng ta phải chọn lọc, không thể thấy hình thức người tu rồi nói sao tin vậy. Cho nên chúng ta phải cẩn thận. Được vậy giá trị Tăng mới còn. Nếu chúng ta dễ tin, tin bừa quá vô tình làm cho giá trị Tăng bảo ngày càng suy sụp đi. Đó là tin về Tăng.

Như vậy đối với Phật, Pháp, Tăng là ba ngôi quí báu. Phật bảo thì chúng ta không nghi ngờ, thật là quí báu tuyệt vời. Pháp bảo chúng ta cũng tin trăm phần trăm. Nhưng Tăng bảo cần phải chọn lọc. Đó là tôi nói rõ để tất cả chúng ta hiểu và tin Tam bảo.

Kế đến, ngoài tin Tam bảo Phật dạy chúng ta phải tự tin nơi mình. Dù người xuất gia hay tại gia đều phải có sức mạnh tin ở nơi mình. Tin mình là tin cái gì? Tin ta có đủ khả năng thay đổi hay là chuyển hóa những nghiệp xấu dở trở thành nghiệp hay tốt. Như trên tôi đã nói, Phật dạy chúng ta phải bỏ nhân xấu, tạo nhân tốt. Mình tin rằng mình có khả năng bỏ được những nhân xấu và cố gắng tạo được nhân tốt.

Ví dụ Phật tử lúc trước rượu chè say sưa, bây giờ qui y thọ giới rồi biết đó là nhân xấu, quyết tâm bỏ rượu để hết nghiệp nhân xấu. Tự mình quyết tâm bỏ thì bỏ được, chớ đâu ai bỏ thế cho mình được. Nếu chúng ta tin ở khả năng có thể chuyển của mình thì bỏ được các nghiệp xấu, chắc chắn như vậy. Nhờ thế Phật tử sẽ tiến bộ nhiều, sẽ tăng trưởng nhiều, nhất là tăng trưởng phần đạo đức. Ngược lại nếu không tin mình, nói đã lỡ ghiền làm sao bỏ được. Thầm nghĩ như vậy thì phải chịu ghiền suốt đời thôi. Cho nên niềm tin nơi chính mình rất quan trọng, có tính quyết định nhiều nhất trên con đường tu tập của chúng ta.

Song tự tin như vậy cũng chưa đủ, còn phải tin đặc biệt hơn nữa. Tin như thế nào? Lịch sử ghi rõ ràng đức Phật Thích-ca Mâu-ni khi đi tu, Ngài học hỏi với các tiên nhân nhưng tu không có kết quả như ý. Cuối cùng từ bỏ hết, Ngài đến ngồi dưới gốc Bồ-đề thệ rằng: *“Nếu nơi này ta không thành đạo, dù xương tan thịt nát quyết không rời cội cây này”*. Thệ nguyện như vậy rồi, suốt bốn mươi chín ngày đêm thiền định, tâm lóng lặng trong sạch, tự Ngài sáng ra những điều trước kia chưa từng biết.

Như vậy trí tuệ của Phật từ đâu mà có? Không ai dạy, không học gì thêm tại sao lại biết, biết quá tầm hiểu biết của thế gian. Điều đó minh chứng rằng khi tâm mình hoàn toàn thanh tịnh thì trí tuệ sáng suốt sẵn có phát ra. Trí tuệ ấy vượt ngoài tất cả trí sáng suốt thường, nên Phật gọi là vô sư trí, tự nhiên trí hay căn bản trí. Chúng ta có trí vô sư, có trí căn bản, có trí tự nhiên, nhưng không chịu khai thác nên không dùng được.

Đức Phật đã giác ngộ viên mãn nên trí tuệ của Ngài cũng viên mãn. Vì vậy những gì Phật dạy chúng ta đến bây giờ hơn hai ngàn năm vẫn không lạc hậu, không sai sót. Đức Phật là một con người, chúng ta cũng là con người, đức Phật có sẵn trí vô sư, trí tự nhiên, trí căn bản, chúng ta cũng có đầy đủ như Ngài. Quí vị có tin không? Lòng tin của chúng ta còn yếu quá. Bởi thế Phật tu giác ngộ, còn mình tu hoài không thấy giác ngộ. Nếu chúng ta vững tin, khẳng định mình cũng sẽ giác ngộ như Phật, mới mong thực hiện được nguyện vọng ấy.

Ở thế gian, các nhà khoa học hoặc bác học, khi muốn nghiên cứu một đề tài gì, họ phải dồn cả tâm lực, có khi quên cả vợ con, quên cả tắm rửa, dồn sức đi sâu trong vấn đề đang nghiên cứu. Nhờ dồn sức như vậy, qua một thời gian bỗng dưng họ sáng lên gọi là phát minh. Như vậy ai dạy họ phát minh? Tự họ sáng ra do tâm chuyên nhất, không tạp loạn. Đó là trí vô sư đã sẵn, nhưng trước kia họ lo học, lo tìm kiếm bên ngoài, lượm lặt bên ngoài nên trí ấy không thể phát ra được. Bây giờ họ trở lại chuyên tâm dồn sức để phát huy trí tuệ của mình, do đó nó phát ra. Điều này chứng tỏ chúng ta ai cũng có sẵn trí vô sư, mà bỏ quên nên không dùng được rồi tự cho mình khờ dại…

Trong kinh Phật có nói rõ: *“Nhất thiết chúng sanh giai hữu Phật tánh”*, nghĩa là tất cả chúng sanh đều có tánh Phật. Chữ tánh là sẵn, ai cũng có sẵn tánh giác, không riêng gì Phật. Nhưng chúng ta có mà không biết tìm cách khơi dậy, không biết tìm cách phát sáng, nên nó cứ im lìm chìm lặng. Nếu chúng ta tu đúng cũng sẽ thành Phật. Vì vậy thành Phật hay không là chuyện của mình, chớ không phải của ai. Chúng ta dám xưng là Phật tử mà không dám tin mình sẽ thành Phật thì vô lý quá. Nếu là con Phật, Ngài tu thành Phật, ta tu cũng thành Phật.

Thế mà Như Lai ngại chúng ta yếu đuối không dám nhận, nên Ngài nói thêm: *“Ta là Phật đã thành, các ngươi là Phật sẽ thành”*. Như vậy tất cả chúng ta đều có chủng tử, có nhân duyên sẽ thành Phật. Người tu quyết chí đi tới giác ngộ viên mãn, chớ không phải tu để mà tu, thì nhất định sẽ thành Phật. Ngoài ra, có chỗ Phật còn nói: “*Tất cả chúng sanh đã thành Phật”*. Nghe câu này đa số không hiểu nổi. Nói sẽ thành Phật thì chịu, còn đã thành Phật thì lắc đầu, không chịu. Phật nói như vậy có quá đáng không? Thật ra vì y cứ trên tánh giác sẵn có từ thuở nào của chúng sanh nên Ngài nói như thế. Bây giờ chúng ta làm sao cho tánh giác hiện đủ thì thành Phật ngay thôi. Song, nếu tánh giác chưa hiện thì nó cũng đã có sẵn nơi chúng ta rồi. Vì vậy đức Phật mới nói *“tất cả chúng sanh đều đã thành Phật”*, tức đều đã có Phật nhân.

Ví như có người có hòn ngọc quí vô giá. Nếu lấy ra dùng thì họ sẽ thành người giàu có sang trọng. Nếu không lấy ra dùng, tuy họ mang thân nghèo khó trong hiện tại, nhưng hòn ngọc quí vẫn nằm sẵn trong túi áo, nghĩa là họ vẫn có hòn ngọc như thường. Đã có hòn ngọc thì lúc nào chẳng giàu. Tuy nhiên, dùng được thì sự giàu sang ấy hiện rõ, còn chưa dùng được thì sự giàu sang ấy tiềm ẩn, chớ không phải không giàu.

Cũng vậy Phật đã khơi dậy được tánh giác nên Ngài thành Phật, còn chúng ta có tánh giác mà chưa khơi dậy nên ông Phật của mình còn ngủ quên, chớ không phải không có. Ta cũng là Phật mà Phật ngủ. Bây giờ nếu khéo tu, khéo chuyển chúng ta sẽ thành Phật như Ngài, giác ngộ như Ngài. Đừng nghĩ mình không có khả năng, rồi tự lui sụt. Cứ ôm mặc cảm thành Phật là chuyện của Phật, còn mình là chúng sanh phàm phu xấu tệ, thì phải chịu trôi lăn trong sanh tử, không biết bao giờ mới ra khỏi.

Vấn đề là làm sao để khơi dậy tánh Phật đây? Thật ra không có gì khó hết. Như mùa mưa nước đục ngầu, ta cần nước nên xuống hồ múc nước đục đổ vô khạp. Nước này đục mãi hay sẽ trong? Tuy nước đục mới đổ vô khạp còn nhiều cáu bợn, không thể dùng được. Nhưng nếu chúng ta khéo gạn lọc, nước đục từ từ lắng xuống, nó sẽ trở thành nước trong. Nếu không lắng mà cứ quậy hoài thì nước đục sẽ không bao giờ trong. Khi nước trong rồi, ta nhìn vô thấy rõ mặt mũi mình, phải không? Chẳng những thấy mặt mình mà còn thấy những cảnh trời mây bên ngoài nữa.

Như vậy nước trong từ đâu lại? Từ nước đục chớ gì. Nước trong đã sẵn, nhưng vì hoà tan với đất bùn nên biến thành đục, nếu chúng ta khéo lóng nó sẽ trở thành trong. Tánh nước vốn trong, tại bụi đất hòa tan thành đục. Cũng vậy, tâm chúng ta sẵn có tánh giác chân thật, nhưng vì ta vọng tưởng điên đảo quá thành ra mờ tối. Bây giờ muốn hết mờ tối thì dừng hết những vọng tưởng điên đảo ấy đi, đừng quậy nó lên nữa. Đức Phật nói: “Ta là Phật đã thành, các ngươi là Phật sẽ thành”, đó là một cách an ủi thúc đẩy chúng ta tiến lên.

Có nhiều người cứ nghĩ mình đủ thứ mê muội, đủ thứ xấu xa trông gì thành Phật. Cũng như thấy nước đục quá, không biết làm sao cho nó trong nên đổ bỏ, thật đáng tiếc! Chỉ cần lắng hết cặn bả thì nước đục thành trong. Bởi tánh nó trong sẵn nên lắng nó mới trong, nếu tánh nó là đục thì lắng gì lắng, vẫn đục như thường. Hiểu như vậy mới thấy lời Phật là chân thật, mở ra một con đường cho chúng ta tu hành. Bởi vì chư Phật luôn muốn chúng sanh được giác ngộ, chớ các Ngài không muốn chúng ta chìm mãi trong luân hồi sanh tử.

Chư Tăng Ni hay Phật tử tập tu thiền, ngồi ngó xuống im lìm một hai giờ, không làm gì hết. Người ngoài thấy tu như vậy là ích kỷ, tiêu cực. Đối với thế gian một hai giờ làm ra tiền khá lắm chứ, còn ngồi ngó xuống hoài mất thì giờ, có lợi ích gì đâu? Vì vậy họ cho rằng việc tọa thiền không thích hợp. Đó là vì họ không hiểu, thật ra việc làm này rất phi thường. Tại sao? Bởi vì nơi tâm chúng ta đã sẵn có tánh giác, nhưng vì vọng tưởng điên đảo che phủ hoài. Bây giờ ta ngồi yên nhìn xem thực tướng nó là gì. Khi biết vọng tưởng chỉ là bóng dáng hư ảo, không thật ta không đắm mê chạy theo nó nữa, chúng tự lui tan. Đó là ta đang vén những áng mây mờ phủ che tánh giác xưa nay của mình. Một việc làm để giải quyết tận căn để số phận con người trong ba cõi sáu đường như vậy mà cho là vô ích, tiêu cực được sao?

Quí vị khi nào được năm ba phút không nghĩ việc này, việc nọ sẽ thấy trong đầu thảnh thơi sáng suốt vô cùng. Càng suy nghĩ càng rối rắm, càng suy nghĩ càng mờ tối, chớ không thể sáng được. Cũng như nước đục mà cứ quậy mãi thì đục hoài, không bao giờ trong được. Cũng vậy, tâm chúng ta điên đảo rối nuồi, cuồng loạn. Bây giờ phải ngồi lại nhìn nó, thấy được nó rồi tự nhiên hạn chế bớt sự cuồng loạn, bớt loạn lần lần sẽ đi đến yên định. Định rồi phát trí tuệ, nên trong nhà Phật dạy ba môn giải thoát là Giới, Định, Tuệ.

Giới để ngăn ngừa, kềm chế tiếp xúc các duyên, thì trong tâm sẽ bớt vọng tưởng. Tâm bớt vọng thì dễ yên. Cho nên người giữ giới được rồi, ngồi tu tâm dễ yên định. Tâm đã yên định thì trí tuệ chân thật hiện tiền, chớ không có gì lạ hết. Hiểu rõ như thế mới thấy việc tọa thiền rất quan trọng. Ta ngồi im lặng nhưng thật ra đang làm một việc, chuyển con người mê muội trở thành con người sáng suốt giác ngộ. Đó là chuyện phi thường chớ đâu phải thường.

Nếu chúng ta không muốn trầm luân muôn đời muôn kiếp thì phải vượt thoát vòng sanh tử. Muốn vượt ra ngoài vòng sanh tử chúng ta phải giác ngộ tròn đầy. Ngồi thiền là cố gắng nỗ lực dẹp bỏ tâm điên đảo, để được giác ngộ tròn đầy. Đây là việc làm của những con người sáng suốt lạc quan, yêu đời yêu đạo, chớ đâu phải như một số người đã hiểu sai lầm.

Tôi xin hỏi quí vị một câu: Hiện giờ trong tâm quí vị nhớ cái gì nhiều nhất? Chắc chắn là nhớ người mình thương hoặc nhớ người mình ghét nhiều nhất, phải không? Có nhiều người nói tôi thù kẻ đó nguyện không đội trời chung, tức là nhớ tới muôn kiếp. Như vậy trong lòng mình chất chứa cái thương cái ghét, cái buồn cái giận, đủ thứ hết. Những thứ đó là nhân sẽ đưa chúng ta đi trong luân hồi sanh tử, gặp lại nhau để đền trả mãi không thôi. Nếu ta cứ mặc tình cho những nhân ấy lồng lộn, làm rối rắm mình mãi thì chừng nào mới ra khỏi luân hồi sanh tử. Cho nên phải chận, phải dừng hết không cho nó phát triển nữa.

Nhà Phật gọi thương nhiều là ái, từ ái dẫn tới đời sau gặp lại nhau. Ghét nhiều là tắng, cũng là nhân dẫn tới đời sau gặp lại nhau. Muốn không gặp khổ đau bởi người thương kẻ ghét ở mai sau nữa, chúng ta phải làm sao? Thôi, đừng thèm thương ghét ai hết, bỏ hết, quên hết đi thì đời sau không gặp lại. Người đã làm khổ mình, nếu ta cứ giận hoài là nuôi lớn thêm nỗi khổ, chớ có được gì đâu. Như vậy bỏ hết lợi hơn hay ôm ấp lợi hơn? Biết bỏ là lợi, nhưng đa số chịu ôm chớ không chịu bỏ. Giữ hoài không nỡ bỏ, biết nó khổ nhưng vẫn ôm giữ nên Phật nói chúng sanh đáng thương.

Do không tỉnh giác, cứ ôm ấp những nhân đau khổ, vì vậy đời này khổ, đời sau càng khổ hơn. Thế nên Phật dạy chúng ta phải luyện lọc, chừa bỏ những niệm xấu ác để đời sau có mặt trên thế gian không gặp đau khổ, xấu ác nữa. Đó là tu. Nên nhớ chủ tạo thành nghiệp là tâm. Chúng ta ngừa đón được tâm, làm chủ được tâm rồi thì sẽ không tạo nghiệp xấu ác. Không làm chủ được tâm, gặp duyên tới sanh đủ thứ chuyện không dừng được. Bây giờ ngồi lại tu cho tâm yên tịnh là ta giành quyền làm chủ, không để tâm rối loạn, muốn nghĩ gì thì nghĩ. Người dụng công như thế, sức làm chủ không phải thường.

Thế gian chịu làm chủ người này người kia, can thiệp dạy bảo thiên hạ. Còn chính mình làm chủ mình không được. Gặp việc bất như ý giận la như điên, gặp việc thích thú thì mê man tàn tịch. Người tu Phật không thể như thế được, phải tập làm chủ ý niệm. Một niệm vừa khởi lên ta bắt nó phải dừng, được như vậy mai kia mới làm chủ được nghiệp. Làm chủ được nghiệp mới tránh khỏi những con đường luân hồi đau khổ.

Người tu ngồi yên tỉnh mới thấy coi như không làm gì hết, nhưng họ đang tranh đấu quyết liệt để chiến thắng chính mình. Có thắng được mình rồi chừng đó mới nói chuyện người khác. Mình không thắng mình mà muốn thắng người, đó là chuyện viển vông vô nghĩa. Ý chí quyết liệt thắng mình là ý chí rất dũng cãm. Người có ý chí dũng cãm như vậy tu mới thành công.

Hơn nữa việc chuyển từ một phàm phu thành Thánh nhân là chuyện lớn hay nhỏ, tầm thường hay phi thường? Chuyện rất lớn, rất phi thường. Người thế gian không phân biệt được phàm phu với Thánh nhân. Họ cứ ngỡ bay lên trời hay chui dưới đất mới là phi thường. Còn ngồi yên lặng để chiến thắng mình là tầm thường. Song người biết đạo thấy chiến thắng được mình mới là phi thường. Đức Phật có dạy:

> Chiến thắng vạn quân không bằng thắng mình. Thắng mình mới là chiến công oanh liệt nhất.

Cho nên việc tu tập này hết sức quan trọng, hết sức cần thiết. Chúng ta tiến lên từng bước, làm sao đời này là phàm phu, nhưng những đời sau tiến lên thành bậc phần giác tức Bồ-tát, lần lần đến viên mãn. Nên nhớ ta không được dừng ở một chỗ. Đó là ý nghĩ quan trọng đối với người tu Phật.

Người tu phải nỗ lực, phải quyết tâm cố gắng chuyển hóa tâm tư, chuyển hóa hành động, chuyển hóa nghiệp thức của mình, xấu trở thành tốt. Để rồi chúng ta chuyển từ một phàm phu trở thành Thánh nhân. Đó là quyền của mình, ta có thể làm được, phải tin chắc như vậy. Gốc của sự tu hành chính là tin nơi khả năng giác ngộ của mình, tin nơi trí tuệ sẵn có của mình.

Tôi nhắc lại, chúng ta là Phật tử nên có lòng tin đúng đắn về đạo Phật. Có lòng tin đúng đắn rồi, trên đường tu chúng ta mới xứng đáng là đệ tử Phật, đang tập tiến lên trên con đường giác ngộ. Quí vị nhớ hiểu ứng dụng cho đúng thì cuộc đời tu hành không tiến nhanh cũng tiến chậm, chớ không bao giờ dừng ở một chỗ. Ngược lại nếu cứ đi sai hoài, chẳng những không được tiến mà có thể còn bị lạc lối nữa.

Tôi mong tất cả Tăng Ni là người lãnh đạo Phật tử, quí vị đi và dẫn dắt Phật tử cùng đi đúng theo con đường đức Phật đã đi. Đừng đi sai, đừng đi lệch uổng một đời tu, không biết mai kia có gặp lại Phật pháp không? Làm sao chúng ta đứng vững và luôn luôn không bị những luồng gió nhơ nhớp của thế gian làm lem luốc, phải trong sạch vững vàng trên con đường đạo. Đó là chỗ tha thiết mong mõi của tôi.
