# (PART\*) Tập 10 {-}
# Đạo Phật thực tế không huyễn hoặc {- #dao-phat-thuc-te-khong-huyen-hoac}

<div class="align-right">
*Paris, 1994*
</div>

Phật giáo tồn tại trong lòng nhân loại đến nay đã trên 2000 năm. Do đâu được như thế? Chính là nhờ Phật giáo nói đúng lẽ thật, đưa con người trở về với sự thật muôn đời, vì vậy có thể nói Phật giáo rất thực tế, không phải huyền hoặc. Đó là đề tài chúng tôi muốn nói với quí vị hôm nay.

Tại sao chúng tôi nói đề tài này? Bởi vì đa số người theo đạo Phật, nhất là các vị lớn tuổi không tìm hiểu đúng chánh pháp. Trái lại cứ tin tưởng theo tập quán cổ truyền, do đó đạo Phật không còn thực tế lại trở thành huyền hoặc. Đó là một trong những điều khiến cho Phật pháp đi đến suy tàn. Nếu để cái đà này như thế mãi, các thế hệ Phật tử về sau chắc sẽ tránh xa đạo Phật, vì thấy đạo Phật không còn thích hợp với thời đại mới, với nền khoa học hiện đại. Vì vậy chúng tôi muốn nói rõ đạo Phật không phải huyền hoặc, mà rất thực tế.

Nghe vậy, quí vị sẽ đặt câu hỏi: Lấy đâu làm bằng chứng? Tôi xin dẫn bài kinh đầu tiên, đức Phật dạy năm vị Tỳ-kheo trước kia đã từng theo Ngài tu khổ hạnh. Đó là bài Tứ Diệu Đế. Đây là bài kinh hết sức cụ thể, thực tế, không có gì khó hiểu hay huyền hoặc. Tứ Diệu Đế là bốn chân lý chắc thật. Trong đó đế đầu tiên là Khổ đế. Nghe từ Khổ đế, thiên hạ vội kết luận đạo Phật bi quan.

Khổ đế, chữ *“đế”* nghĩa là chắc thực, không sai chạy. Như vậy cái khổ Phật đưa ra là một lẽ thực, không ai chối cãi được. Khổ có mấy thứ? Đầu tiên là khổ về thân. Thân này có sanh, già, bệnh, chết, bốn thứ đó Phật nói là khổ. Có người chưa chịu sanh là khổ, vì lúc mới lọt lòng mẹ có biết gì đâu mà khổ. Nói không biết gì hơi quá đáng, không biết vậy chớ ai khóc? Biết khóc tức là có cảm giác khổ. Trăm đứa bé lọt lòng mẹ đều khóc, chứng tỏ chúng có thọ khổ. Đó là khổ khi sanh.

Ngoài ra còn có những nỗi khổ trong cuộc sống. Ở đời nếu được những việc như ý thì người ta vui, không như ý thì buồn, buồn tức là khổ. Mỗi vị nhìn lại cuộc đời mình xem được nhiều điều như ý hay nhiều điều bất như ý? Ai cũng bảo mình gặp những điều bất như ý. Người có diễm phúc thì điều bất như ý ít hơn, nhưng tất cả đều có gặp việc bất như ý. Đã bất như ý thì khổ hay vui? Khổ. Như vậy đời sống của chúng ta thường gặp khổ nhiều hơn vui. Khi lọt lòng mẹ đã có cảm giác khổ, rồi trong cuộc sống kéo dài mấy mươi năm cũng khổ. Vì vậy Phật nói sanh khổ, chúng ta chối cãi được không? Thế nhưng nhiều người lại cứ tưởng như vui, đó là vui trong tưởng tượng thôi chớ không có thật. Vậy mà thiên hạ cứ bảo cuộc đời hạnh phúc, cuộc đời có nhiều thú vui, nói lung tung nhưng rốt cuộc ai cũng vỡ mộng hết. Hạnh phúc đâu không thấy, chỉ nghe đau khổ ê chề. Đó là khổ thứ nhất, sanh khổ.

Thứ hai là già khổ. Xưa nay có ai vỗ ngực nói già vui quá không? Hay ai cũng than già khổ đủ thứ. Khổ vì thân yếu đuối, ăn uống không ngon, trí nhớ kém cỏi, đi đứng mất tự do v.v… Những đang già, đã già biết rất rõ điều này, không nghi ngờ gì nữa. Đó là khổ thứ hai, già khổ.

Thứ ba là bệnh khổ. Từ bé cho tới lớn, ai cũng đều biết bệnh là khổ hết. Có người nào bệnh không rên không khóc đâu. Bệnh ít ít khả dĩ cắn răng chịu nổi, chớ bệnh nhiều rên la là điều không chối cãi được rồi. Đó là khổ thứ ba, bệnh khổ.

Thứ tư là chết khổ. Như chúng ta thấy người thân khi sắp lâm chung đau đớn quằn quại rất thống khổ. Đó là chưa kể thần thức hôn mê, người sắp chết thấy những cảnh giới gì đó hiện ra, lòng họ hoảng sợ, kêu gào than khóc, thật là thảm thương. Đó là khổ thứ tư, chết khổ.

Phật nói thân hiện tại của chúng ta đây, mang tính chất đau khổ từ lúc mới sanh, trưởng thành cho tới già, bệnh, chết đều khổ hết. Đó là một lẽ thực. Mới nghe người ta thấy đạo Phật như bi quan, nhưng không phải vậy. Nếu nói thẳng thì đạo Phật rất lạc quan, chớ không bi quan. Tại vì đạo Phật nói rõ lẽ thật của cuộc đời, để con người không lầm lẫn, sống bình thản trên những khổ vui đó. Như vậy không phải lạc quan là gì?

Ví dụ như ta đang gánh một gánh nặng lâu quá mỏi mệt, nếu để được gánh nặng ấy xuống, lúc đó vui hay khổ? Vui. Gánh nặng trên vai thì khổ, để xuống hết nặng là vui. Sau khi biết khổ rồi mới thấy vui, chớ vui không ngoài khổ. Như ở nhà buồn đi xem hát thấy vui, chớ nếu ở nhà vui cần gì đi xem hát? Như vậy chúng ta tìm cái vui sau khi bị khổ. Cũng thế, đạo Phật nói khổ để chúng ta phăng tìm nguồn gốc của nó mà dẹp trừ, khổ hết thì vui đến. Đó là bốn cái khổ về thân.

Kế đến còn bốn thứ khổ về tâm nữa, tổng cộng vừa thân tâm là tám thứ. Nếu kể tiếp theo thì thứ năm là ái biệt ly khổ. Khổ do thương mến mà xa lìa. Người mình thương mến mà phải xa lìa, có hai trường hợp: xa lìa trong lúc đang sống và xa lìa vì kẻ âm người dương, tức kẻ chết người sống. Lúc đó vui hay khổ? Khổ. Nên nói ái biệt ly khổ. Ái nhiều thì khổ nhiều, nếu không có ái thì khổ không thành. Bởi vì đâu phải ai đi xa mình cũng khổ, chỉ người mình thương đi xa ta mới khổ thôi. Khổ này gốc từ tham mà ra. Do khao khát, tham muốn sống gần người mình thương mến mà phải xa, không được toại ý nên khổ.

Thứ sáu là oán tắng hội khổ. Ngược lại với mến thương là oán ghét. Người mình ghét mà cứ hiện diện trước mặt hoài, ta rất bực bội khó chịu, muốn họ đi đâu cho khuất mắt. Nhưng ngặt nỗi, trên đời này người mình thương thì cứ phải chịu xa lìa, còn kẻ mình ghét thường hay gặp gỡ. Khổ này gốc từ sân mà ra. Do sân hận nên người mình oán ghét mà phải sống chung thì khổ.

Thứ bảy là cầu bất đắc khổ. Những gì mình muốn mà không được thì khổ. Ví dụ đi thi mong muốn được đậu, mà lỡ rớt thì sao? Khổ. Ngoài việc thi cử ra, còn bao nhiêu thứ cầu mong khác nữa. Như trong công việc làm ăn, trong tình cảm… Nhiều người muốn tự vận vì cầu mong mà không được như ý.

Thứ tám là ngũ ấm xí thạnh khổ. Khổ do thân năm ấm này chung hợp lại. Vì sự chung hợp này được kết nối bởi các thứ duyên có khuynh hướng nghịch nhau, bên trong luôn mâu thuẫn, chống trái nhau. Vì vậy mà khổ. Nhiều người còn trẻ nghe nói thân này khổ không tin. Vì họ nghĩ đến tương lai hạnh phúc, làm sao khổ được? Có người nói rằng khi nào xúc chạm phải những điều trái ý mới khổ. Nếu xúc chạm những điều như ý thì đâu có khổ. Ví dụ lỗ tai nghe những âm nhạc hay, lỗ mũi ngửi mùi thơm, lưỡi nếm vị ngon… những lúc ấy là vui chớ đâu có khổ? Do đó Phật nói khổ là Ngài hơi nghiêng về một bên, nghĩa là chỉ thấy toàn khổ mà không thấy vui.

Sự thực không phải vậy. Phật nói thân này là gốc của khổ. Tại sao? Vì vô thường nên khổ. Ngày nay trẻ ngày mai lớn lên, rồi già, bệnh và cuối cùng là chết, không dừng ở một chỗ. Nói chung những gì luôn biến đổi, không dừng ở một chỗ thì làm cho người ta khổ. Quí vị khi bốn mươi tuổi ít ai nhớ mình sẽ già tới, mà cứ nhớ hồi còn hai mươi, mười tám. Tới chừng năm mươi tuổi cũng không nhớ mình năm mươi tuổi nữa, cứ nhớ hồi ba mươi bốn mươi. Tại sao lại cứ nhớ lúc trẻ hoài? Mấy ông già bảy tám mươi tuổi ngồi lại kể chuyện, toàn chuyện thời đó trai trẻ oai hùng nhất làng. Ít khi nào kể bây giờ ba già lẩm cẩm, run rẩy, chậm lụt… Luôn luôn nhớ về thuở còn sung sức vui tươi, không chịu nhận lúc mình đang đuối sức, gầy mòn.

Phật nói thân này vô thường nên khổ, chớ không vui. Giả sử có những cảm giác vui thì cũng vui trong tạm bợ vô thường. Qua rồi khổ lại, chớ không có vui thật. Vui của vô thường, Phật nói vui trong đau khổ, không phải vui thật nên nói chung tất cả đều là khổ. Phật dạy cốt để chúng ta nhận định kỹ về cuộc đời này, luôn khổ không vui. Như vậy chúng ta phải có thái độ thế nào? Buồn, nhăn mặt nhíu mày cả ngày phải không? Nếu vui cười thì e trái lời Phật dạy. Quí vị nghĩ sao cho đúng?

Thật ra Phật dạy khổ không có nghĩa để chúng ta ôm ấp nỗi khổ đó suốt đời. Phật nói khổ để mình diệt khổ, hết khổ. Cũng như bác sĩ xem mạch biết bệnh nhân bị bệnh nguy hiểm, nhưng bệnh trạng chưa xuất phát nên người bệnh không biết. Bác sĩ vì muốn cho người đó sớm trị hết bệnh nên buộc lòng phải nói cái nguy hiểm của căn bệnh kia. Nó bắt đầu khởi mầm như thế nào, phát triển như thế nào v.v… Nói cho họ hiểu để lo trị sớm, trị sớm thì sẽ lành bệnh. Nếu bác sĩ thấy mầm bệnh rõ ràng nguy hiểm mà không chịu nói thì chừng nào bệnh nhân mới trị hết bệnh được?

Cũng vậy, Phật thấy được nỗi khổ của chúng sinh, đó là quả xuất phát từ nhân họ đang gây tạo hoặc đã gây tạo. Nên khi nói Khổ đế Phật liền nói qua Tập đế. Khổ không phải tự có mà do nhân duyên gom góp lại tạo thành. Nhân ấy nhà Phật gọi là Tập đế. Như vậy Phật đi từ quả phăng tới nhân. Bởi vì không biết nhân làm sao trị tận gốc khổ được?

Tập đế là những cội gốc của phiền não, là tập nhân tạo thành quả khổ. Cội gốc phiền não còn được gọi là căn bản phiền não. Có sáu thứ: Tham, sân, si, mạn, nghi, ác kiến. Sáu thứ này là nhân tạo thành quả khổ. Nếu ai diệt hết sáu thứ đó sẽ hết quả khổ. Ví dụ người biết tu bỏ sạch lòng tham, thì có khổ vì cầu bất đắc không? Không. Người diệt bỏ nóng giận thì có khổ vì oán tắng hội không? Không. Các thứ khác cũng thế.

Đến ngã mạn tức thấy ta cao, ta quan trọng. Do thấy như thế nên khi sắp mất rất khổ. Bây giờ nếu thấy ta là hư giả, tạm bợ thì có phách lối với ai không, thân này sắp hoại có khổ không? Sở dĩ chúng ta khinh người là vì thấy mình cao quí quá, quan trọng quá. Bây giờ thấy mình là tạm bợ, giả dối thì đâu có gì quan trọng. Không trọng mình nên đâu có khinh người. Rõ ràng chỉ cần chúng ta có một chút trí tuệ thấy đúng như thật, thì khổ về sanh già bệnh chết hết liền.

Nếu lý giải bằng trí tuệ thì thật thân này không có gì quan trọng hết. Chẳng qua chỉ là một nhóm nhân duyên tụ hội lại chớ có gì đâu. Nhiều người thường vỗ ngực xưng tôi, nhưng hỏi cái gì là tôi thì trả lời không chạy. Nếu da thịt là tôi thì khi nó bệnh bác sĩ mổ bỏ đi, cái tôi đó thành gì? Chỉ cần da thịt có vết thương hôi thối, lúc đó mình quí hay muốn bỏ? Khi còn lành lặn ta thấy quí, khi nó hư hoại xem không ra gì, bỏ đi không chút thương tiếc. Rõ ràng cái ta không phải những gì mình đang mang đây.

Phật nói ví dụ thế này. Như người đi qua khu rừng vắng vào ban đêm, chỉ một mình không có bạn bè. Lúc mệt mỏi quá anh thấy một túp lều người ta cất để làm rẫy, liền vào đó trú đỡ qua đêm. Ở trong đó chưa bao lâu, anh thấy một con quỉ to vác thây người đem vào quăng dưới đất. Sợ quá anh đứng núp sát kẹt vách. Kế đó một con quỉ khác xông tới, hai đứa giành nhau cái thây chết. Con quỉ thứ hai nói xác này của nó, con quỉ thứ nhất cũng nói của nó. Giành giật với nhau một hồi, chúng phát hiện ra anh đang núp trong kẹt vách. Thế là anh được lôi ra cử làm trọng tài.

Do chứng kiến từ đầu tới cuối, nên khi bọn chúng hỏi xác này của ai, anh trả lời của con quỉ thứ nhất. Giận quá con quỉ thứ hai giựt cánh tay của anh quăng ra ngoài. Con quỉ thứ nhất liền xé cánh tay của xác chết ráp lại cho anh. Con thứ hai giựt tiếp cánh tay còn lại của anh quăng ra ngoài. Con thứ nhất lại ráp cánh tay của xác chết vào. Cứ thế, một con giựt một con ráp từng thân phần của xác chết vào người anh. Rốt cuộc tay chân của xác chết đã được ráp vào cho anh. Hai con quỉ bấy giờ mỏi mệt quá, thấy hai tay hai chân quăng ra ngoài đó, liền lấy chia nhau ăn. Ăn xong chúng bỏ đi.

Bấy giờ anh chàng tội nghiệp kia nhìn lại thấy rõ ràng thân mình bị quăng ra rồi, bây giờ tay chân này của ai? Nghĩ vậy, anh mới đi tìm một vị A-la-hán hỏi: *“Thưa Thầy, tôi có phải là tôi không?”* Vị A-la-hán nói rằng: *“Nếu anh biết anh không phải là anh thì gần với đạo rồi”*. Ngay đó anh phát tâm tu, chẳng bao lâu sau chứng được A-la-hán.

Phật kể câu chuyện này để làm gì? Bởi chúng ta thấy thân này quá thật nên tu hoài vẫn không tới đâu. Lúc nào mình cũng thấy cái ngã là quí là thật nên khổ vì nó. Nếu chúng ta biết cái ngã không thật, không quí thì bỏ nó một cách dễ dàng, không đau khổ tí nào hết. Còn ngã mạn vì thân là còn đau khổ, hết ngã mạn mới hết đau khổ. Đó là ngũ ấm xí thạnh khổ.

Tám cái khổ đó không phải tự có mà do các thứ bệnh sanh ra. Bệnh tham, bệnh sân, bệnh si, bệnh mạn, bệnh nghi, bệnh ác kiến. Riêng nghi có chia ra hai thứ: Một, nghi do phân vân không quyết đoán điều hay lẽ thật, cái nghi này làm chướng ngại việc tu. Hai, trong nhà thiền thường dùng câu: *“Đa nghi đa ngộ”*, nghĩa là nghi nhiều ngộ nhiều. Tại sao? Vì cái nghi của nhà thiền là nghi để phăng tìm. Do phăng tìm mới sáng lên, còn cứ một bề nghe sao hay vậy, không thắc mắc gì cả thì không bao giờ hiểu thấu đáo được. Cho nên nói đa nghi đa ngộ. Cái nghi này là nghi tốt, giúp cho chúng ta tiến trên con đường tu.

Cuối cùng là bệnh ác kiến. Đây là bệnh rất trầm trọng. Chữ kiến là nhận định, chữ ác là sai lầm. Khi nhận định sai lầm, lại cố chấp nhận định của mình là đúng thì trở thành ác, gây ra tội lỗi. Vì nhận định sai lầm mà cố chấp vào đó sẽ dẫn đến dám làm những điều tai họa cho nhân loại. Do đó ác kiến là cái nguy hiểm nhất. Song ở thế gian lại có nhiều ác kiến.

Ví dụ chúng ta nghĩ tu là được vui, được sanh về các cõi lành hoặc được giải thoát. Vì thế cứ tu cho mình mà không nghĩ tới những người chung quanh như cha mẹ,  anh em v.v... Không cần biết tới mọi chuyện trong sinh hoạt hằng ngày. Ai sao mặc, miễn ta yên ổn tu là được. Nếu có người khuyên bảo, nhắc nhở trách nhiệm, liền đổ quạo bảo ma vương phá không cho tu. Nghĩ vì mình nhiều quá nên càng tu mọi người chung quanh càng chán mình. Bởi họ thấy ta ích kỷ. Tu mà để cho người ta phiền hà khó chịu cũng là cố chấp. Cho nên ác kiến cũng là một trở ngại trên đường tu của chúng ta.

Phật gọi sáu thứ bệnh đó là sáu thứ phiền não căn bản. Nếu dẹp sạch sáu thứ này mới được an vui thật sự. Như vậy Phật nói khổ không phải để chúng ta chịu khổ, mà nói khổ để chúng ta dẹp hết gốc khổ, được vui. Cho nên mới có đế thứ ba là Diệt đế, nghĩa là diệt sạch hết nhân khổ. Khi hết khổ, Phật nói hết khổ chớ không nói vui. Tại sao? Thường thường chúng ta cứ mắc kẹt trên đối đãi khổ vui, muốn hết khổ để được vui. Nhưng sự thực hết khổ là vui rồi. Hết khóc tức hết buồn, còn buồn thì còn khóc. Không nói vui mà vẫn tự vui.

Phật nói cứu kính Niết-bàn tức là Diệt đế. Sao nói diệt mà không nói được cái gì hết? Không nói được ta cảm thấy buồn. Phật biết chúng sanh nặng về bệnh tham cầu nên trong kinh Bát-nhã, Ngài dạy: *“dĩ vô sở đắc cố Bồ-đề-tát-đỏa y Bát-nhã ba-la-mật-đa cố, tâm vô quái ngại, vô quái ngại cố, vô hữu khủng bố, viễn ly điên đảo mộng tưởng, cứu kính Niết-bàn. Tam thế chư Phật y Bát-nhã-ba-la-mật-đa...”* nghĩa là vì không có sở đắc nên Bồ-tát mới xa lìa điên đảo mộng tưởng, cứu kính Niết-bàn. Ba đời chư Phật cũng y Bát-nhã mà thành Phật. Rõ ràng Phật nói cứu kính của công phu tu hành không có sở đắc.

Nhưng tu mà không được gì, thiên hạ không chịu, đòi phải được. Hết khổ phải được vui. Sự thực hết khổ là vui rồi. Vui mà nói *“được”* thì không phải thật vui. Tại sao? Vì khi nói *“được”* là cái đó không phải tự mình có. Như khi ta đi đường lượm được một tấm giấy bạc thì nói tôi lượm được giấy bạc này. Nếu giấy bạc ấy sẵn trong túi, ra chợ ta lấy ra xài thì không nói *“được”*, vì nó là của mình mà. Nói được thì cái đó không phải của mình.

Lâu nay chúng ta có bệnh đòi *“được”* mà không biết cái được đó không phải của mình. Biết rõ chỗ này mới tu hạnh Bồ-tát và đi tới quả Phật được, còn đòi được sẽ không bao giờ được. Đa số người tu lầm lẫn điều này nên dễ bị người ta đánh lừa. Nghe nói tu theo tôi ba tháng, bảy tháng được cái này cái kia, thích quá theo liền. Tu phải được cái này cái kia mới vui chứ. Tu như quí thầy dạy không được gì hết, buồn quá.

Khổ vốn không tự có mà do nhân tham, sân, si, mạn, nghi, ác kiến mới có. Nếu những nhân này diệt hết thì vui tự đến. Sạch hết nhân khổ thì quả vui hiện ra, chớ đâu có ai đem cho chúng ta cái vui mà nói được. Nên biết vui này không phải từ ngoài mà được. Nói như thế nghe hơi khó hiểu, nhưng nếu quí vị chịu khó nghiền ngẫm kỹ sẽ thấy. Đức Phật không muốn nói tu để được cái này được cái kia gì hết. Tại sao? Vì trong chúng ta có hai thứ: Một là tánh sáng suốt thanh tịnh, hai là tâm ô nhiễm loạn động. Bây giờ muốn tánh sáng suốt thanh tịnh hiển bày thì phải dẹp bỏ tâm ô nhiễm. Phật không thể cho chúng ta sự giác ngộ, mà chính mình dẹp sạch các nhân phiền não thì tự sáng lên, đó là giác ngộ.

Như khi đọc kinh sách chúng ta hiểu, cái hiểu đó nhờ đức Phật hướng dẫn, nương nơi Phật mà hiểu. Còn nếu chúng ta ngồi thiền, tâm yên trí sáng hiểu biết thấu đáo, đúng đắn mọi việc. Đó là do đâu? Do chính ông Phật của mình hiện ra nên trí tuệ sáng suốt viên mãn, thấy biết tất cả. Khi đức Phật Thích-ca giác ngộ dưới cội Bồ-đề là do Ngài thiền định, chớ đâu phải suy gẫm hay nghiên cứu vấn đề gì, chỉ là tâm định. Tâm định thì trí sáng mới thấy tất cả, gọi là giác ngộ. Phật thường tuyên bố *“ta học đạo không có thầy”*, tức không có ai dạy mà tự giác ngộ.

Như vậy giác ngộ này là trí tuệ sẵn của mình, chớ không phải ai đem đến. Cho nên người nào tu Phật mà phóng tâm ước mơ gặp những hiện tượng lạ bên ngoài đều gọi là ngoại đạo. Tìm đạo ở ngoài mình là ngoại đạo. Hiểu thế mới thấy sự thâm trầm của đạo Phật. Đức Phật chỉ dạy chúng ta dẹp sạch hết những nhân đau khổ mình hằng chứa chấp thì hết đau khổ. Khi hết khổ chúng ta tự an vui. Đó là lẽ thực.

Như vậy công phu tu hành là công phu của ai? Chính mình phải tự gạn lọc những nhân xấu nhân khổ loại ra. Loại hết nhân xấu khổ thì tự nhiên được vui. Diệt hết các nhân khổ gọi là Diệt đế tức hết khổ. Nhưng diệt bằng cách nào? Vì vậy Phật đưa ra Đạo đế, tức con đường diệt khổ. Đây là đế thứ tư trong Tứ đế.

Đạo đế là những phương tiện, những cách thức để chúng ta ứng dụng tiêu diệt các nhân khổ. Đạo đế theo giáo lý Nguyên thủy có ba mươi bảy phẩm trợ đạo. Ở đây không có thì giờ nói hết, chỉ nêu tên cho tất cả có khái niệm thôi. Đủ duyên quí vị nên nghiên cứu thêm.

Như vậy bài thuyết pháp đầu tiên của đức Phật rất cụ thể, rất thực tế, không có gì huyền hoặc. Nhưng bây giờ chúng ta tu có giống lời Phật dạy chưa? Đó là vấn đề cần được nêu lên để chúng ta thấy rõ cái gì thực, cái gì hư. Các ngôi chùa cổ ở Việt Nam cũng như nước ngoài đến nay vẫn còn ứng dụng theo nếp cũ, đa số chú trọng về nghi thức. Mà nghi thức nhị thời khóa tụng phát xuất từ đời nhà Thanh của Trung Quốc.

Đời này Phật giáo suy vi, nguyên quán vua chúa nhà Thanh ở gần Hy Mã Lạp Sơn nên đa số nặng về Mật giáo. Do đó họ yêu cầu các Thiền sư soạn nghi Nhị thời khóa tụng, phần nhiều đều của Mật giáo. Đầu hôm tụng kinh Di-đà, sau đó tụng chú. Trọn một buổi khuya tụng Lăng Nghiêm, Thập chú đều thuộc về Mật tông hết. Thế là phần giáo lý uyên thâm của đức Phật không thấy nhắc đến, không được đem ra ứng dụng.

Phật giáo Việt Nam chúng ta lại ảnh hưởng Trung Hoa, nên cũng tu theo nghi thức của người Trung Hoa soạn vào thời kỳ Phật giáo tại nước họ suy đồi. Nghi của người Trung Hoa soạn thì không phải là của Phật thời xưa, mà chúng ta lấy đó làm nếp tu hành suốt đời thì thật là đáng buồn! Thí dụ như bây giờ Phật sự của Tăng Ni là gì? Phật tử có cha mẹ mất thì đi hộ niệm. Như vậy cũng tốt, nhưng hộ niệm xong rồi tới gì nữa? Cầu siêu trong mấy tuần thất. Mấy tuần thất xong rồi gì nữa? Tới ba tháng, bốn mươi chín ngày, rồi giáp năm, sau đó lâu lâu là giỗ. Như vậy cứ liên miên Phật tử này đến Phật tử khác, ai đòi cũng phải đi. Thành ra Tăng Ni đi tối ngày, không rảnh chút nào hết lấy chi mà công phu.

Song tôi đặt câu hỏi lại, thầy cô tụng kinh cầu siêu cho Phật tử, nhưng có bảo đảm rằng họ siêu hay không? Có ai dám ký giấy giao kèo *“tôi cầu nhất định người đó siêu”* không? Không dám ký. Ta làm một việc không bảo đảm, không chắc chắn mà cứ làm như vậy có hợp lý, có thực tế không?

Trong kinh A-hàm có kể lại thế này. Một hôm sau khi đức Phật thọ trai xong, có năm bảy vị Bà-la-môn tới hỏi:

\- Thưa ngài Cồ-đàm, đệ tử Ngài khi chết, Ngài cầu cho họ sanh về cõi trời được không?

Phật không trả lời mà hỏi lại:

\- Nếu đệ tử các ông chết, các ông có cầu cho họ sanh về cõi trời được không?

Các vị Bà-la-môn đáp:

\- Được.

Phật liền dùng ví dụ thế này để hỏi các thầy Bà-la-môn:

\- Như có người lăn một cục đá to xuống giếng, sau đó họ yêu cầu các thầy chấp tay cầu nguyện cho cục đá đừng chìm, các thầy làm được không?

Các thầy Bà-la-môn đáp:

\- Không được.

\- Tại sao?

\- Vì đá nặng quá, rớt xuống giếng nhất định chìm, cầu cách chi cũng không thể nào nổi được.

Phật lại nói:

\- Giả sử có người đem dầu đổ lên mặt nước, sau đó yêu cầu các thầy chấp tay cầu nguyện cho dầu chìm tận đáy giếng được không?

\- Không được.

\- Tại sao?

\- Vì dầu nhẹ nhất định phải nổi lên trên mặt nước, có cầu mấy cũng không chìm được.

Phật nói:

\- Cũng vậy, người làm nghiệp ác phải đọa, các ông cầu sao cho khỏi đọa. Còn người làm nghiệp thiện dù các ông có ác ý muốn cầu họ đọa, họ cũng sanh lên cõi trời như thường.

Qua ví dụ này chúng ta nghĩ sao? Nghiệp thiện nghiệp ác là nhân chủ yếu để sanh lên hay đọa xuống, chớ không phải do cầu mà được. Sở dĩ Phật giáo Việt Nam gần đây theo nếp cúng kính nhiều, chẳng qua là ảnh hưởng Phật giáo Trung Quốc. Ở Trung Quốc, Nho giáo là gốc. Bởi thế nên họ nặng về hình thức nghi lễ. Cha mẹ chết phải để tang, phải ra nằm giữ mộ ba tháng, phải để râu tóc… đủ thứ nghi lễ rườm rà. Khi Phật giáo sang Trung Hoa so với Nho giáo nghi lễ rất nghiêm trang, nếu người theo đạo Phật không lễ mễ như vậy, họ buồn không chịu theo, buộc lòng các thầy cũng chế ra nghi lễ. Thế là Phật tử có cha mẹ chết cũng rước quí thầy lại để hiến tửu, hiến trà, hiến phạn đàng hoàng. Đó là phương tiện độ người Trung Hoa thời đó, cho họ thấy đạo Phật cũng có nghi lễ nghiêm chỉnh, không thua sút nhà Nho. Người sau không hiểu phương tiện tùy thời của các bậc tiền bối, lại đem phương tiện biến thành chỗ cứu kính, làm cho giáo lý nhà Phật bị sai lạc. Thật là đáng tiếc!

Chúng ta phải hiểu đạo Phật từ gốc, không nên theo ngọn. Do đó tôi phải nhắc để quí vị nhớ, thật ra đạo Phật rất cụ thể, rất thực tế, chớ không huyền hoặc như nhiều người lầm tưởng. Trong những bài thuyết pháp đầu tiên của Phật cũng như những bài pháp sau này, Phật đều không chấp nhận cúng kính cầu nguyện là việc chính của các Tỳ-kheo. Thế mà bây giờ mình lại lấy cúng kính cầu nguyện làm Phật sự chính, rồi cả đời tu cứ dồn vào đó, có phải đáng tiếc không?

Người tu là người tìm ra con đường sáng suốt giác ngộ cho mình và mọi người. Tăng bảo là những vị tăng thanh tịnh cao cả, truyền trì mạng mạch của Phật pháp, chớ không phải thầy cúng đi đám cho Phật tử vui. Chúng ta thăm viếng khi hữu sự cho có đạo tình một chút với Phật tử, tạo niềm an ủi để hướng dẫn họ đi theo con đường chánh thì được. Còn cứ mải miết theo cái thường tình thế gian, rồi mắc kẹt ra không được gọi là sa lầy trong phương tiện.

Người học Phật phải thấy rõ chủ yếu của đạo Phật là cứu khổ. Đã là cứu khổ thì phải chỉ cái khổ cho người ta thấy. Biết khổ rồi không nghi ngờ nữa, kế đó ta chỉ nhân gây ra đau khổ để tiêu diệt nó. Nhân đau khổ hết thì quả đau khổ cũng hết. Muốn thế phải có phương pháp cụ thể, ứng dụng một cách thiết thực, chớ không phải cầu nguyện suông. Đó là việc làm chính của người tu sĩ Phật giáo.

Phật không tu thế cho chúng ta được, mà tự mình tu tập để được giải thoát. Lâu nay tôi hơi khổ một chút là vì bị Phật tử bắt tôi vuốt đầu. Cứ nói *“thầy vuốt đầu cho con tu tinh tấn”*. Tôi khổ ghê mà không có cơ hội để giải thích. Thật ra quí vị phải tự tinh tấn lấy, chớ không phải do tôi vuốt đầu mà siêng được. Phật tử cứ mơ ước người khác làm thế mình, không chịu tự làm. Đó là một lối ỷ lại không tốt. Hiểu như vậy rồi thì khỏi hỏi ai tôi tu được không, học hành đỗ đạt không, cúng kính cầu nguyện được không? Tự chúng ta quyết định lấy, không cần phải hỏi ai, vì không ai có thể trả lời được ngoài mình.

Tôi nghĩ rằng muốn cho người sau thấy được cái hay của đạo Phật, bây giờ Tăng Ni phải khai sáng, giảng trạch những gì đúng những gì sai cho Phật tử hiểu. Không nên che lấp những khiếm khuyết, sai trái còn tồn đọng trong lòng Phật giáo. Bởi vì nếu che lấp như vậy mãi thì thế hệ con cháu của chúng ta sau này sẽ bỏ đạo. Vì chúng thấy đạo Phật chẳng có gì hay, chỉ mang màu sắc mê tín thần bí đâu đâu, không giải quyết được những vấn đề hiện thực trong đời sống con người. Như thế vô tình chúng ta đã phá đạo rồi.

Đức Phật thường tuyên bố Ngài là một vị đạo sư, tức vị thầy dẫn đường, chớ không phải người đưa chúng sanh lên cõi Cực Lạc. Nếu Phật đưa được thì bây giờ chúng ta không còn ngồi đây nữa. Hiện giờ ta còn lang thang đây thì biết rằng Phật không dùng phép thần thông đưa ta được. Ngài hướng dẫn chỉ đường cho mình đi, ta không chịu đi Phật cũng bó tay. Hiểu như vậy chúng ta mới thấy đạo Phật rất cụ thể, rất thực tế.

Trong kinh Tiễn Dụ, có một vị Tỳ-kheo tới hỏi Phật: Thế giới là hữu biên hay vô biên, chúng sanh là hữu biên hay vô biên? v.v... Phật im lặng không trả lời. Vị Tỳ-kheo kia nói Phật không trả lời tức là Ngài không biết nên không hỏi nữa, cũng không thèm tu. Bấy giờ Phật nói ví dụ, như có người bị trúng tên độc. Khi ấy thân nhân anh ta rước thầy thuốc đến mổ khử độc. Ông thầy định nhổ mũi tên ra, anh ta ngăn lại: Khoan đã, đừng nhổ gấp, để tôi hỏi xem mũi tên này từ đâu bắn lại, người bắn là ai ở đâu, cao hay thấp, trắng hay đen. Trả lời xong những thắc mắc này rồi sẽ nhổ.

Thầy nghĩ sao? Chưa trả lời hết những câu hỏi kia thì anh đã thấm thuốc độc chết mất rồi. Cũng vậy, đợi ta nói chuyện thế giới hữu biên hay vô biên, chúng sanh hữu biên hay vô biên thì kiếp sống thầy đã qua mất rồi. Mạng người có mấy chục năm quá ngắn ngủi, không lo tu hành cứ tìm hiểu thế giới hữu biên vô biên v.v... Thực tế hỏi mình có đau khổ hay không, tại sao đau khổ, làm cách nào để hết khổ, đó mới là chuyện cần làm ngay. Thế mà chúng ta không chịu làm việc ấy trước, hỏi chi chuyện xa xôi?

Đức Phật rất thực tế, cụ thể, không viển vông mơ hồ. Chúng ta tu theo Ngài cũng phải như vậy, không chấp nhận việc gì không biết kết quả ra sao mà vẫn cứ làm. Khi nào xét thấy rõ ràng, nhân quả tương ưng như thế ta mới làm. Ví dụ Phật dạy tám cái khổ trên là do sáu nhân phiền não căn bản mà có. Bây giờ bớt tham thì không có khổ cầu bất đắc, bớt ái thì không có khổ ái biệt ly, bớt chấp ngã thì không có khổ về thân ngũ ấm. Làm được cái nào kết quả ngay cái đó, không nghi ngờ.

Thời đại của chúng ta hiện nay khoa học ngày càng phát triển. Nếu đạo Phật mang màu sắc huyền bí thì dần dần sẽ không đủ sức thuyết phục những thế hệ sau. Truyền giáo như thế thì đạo Phật sớm đi đến ngày cáo chung. Do đó chúng ta, hàng xuất gia cũng như cư sĩ tại gia phải ý thức được bổn phận, trọng trách của mình ở ngày mai. Đừng nuôi lớn những tư tưởng sai lầm cho người để cuộc sống của mình được an nhàn. Đó là chúng ta có tội với Phật pháp, có tội với chúng sanh.

Để kết thúc, chúng tôi xin nhắc tất cả Tăng Ni cũng như Phật tử nỗ lực tu tập để chuyển nghiệp của mình. Vì chỉ khi nào dứt nghiệp, sạch nghiệp chúng ta mới thấy được chân giá trị của đạo Phật, là đưa con người thoát khỏi đau khổ một cách triệt để. Lợi ích ấy vô cùng lớn lao và thiết thực.
