# Ông thiện ông ác {- #ong-thien-ong-ac}

<div class="align-right">
*Làng Hồng – Pháp, 1994*
</div>

Hôm nay chúng tôi xin giới thiệu sơ lược với quí vị một vài lối nhìn của Phật giáo Việt Nam qua kinh điển Phật dạy. Nếu nhận định chín chắn chúng ta sẽ thấy Phật giáo Việt Nam có những ưu điểm đáng cho mình học tập và ứng dụng theo.

Những ngôi chùa cổ ở Việt Nam, từ ngoài cổng đi vào chúng ta nhìn bên phải thấy tượng một vị rất hiền hòa, dân gian gọi đó là ông thiện, bên trái tượng một vị rất dữ dằn, dân gian gọi đó là ông ác. Nhiều người thắc mắc chùa là nơi hướng dẫn Phật tử trở về con đường lành, thờ ông thiện đủ rồi, tại sao lại thờ ông ác?

Nhưng với cái nhìn của chúng tôi, bản ý của chư Tổ qua hai hình tượng ông thiện ông ác, mang một ý nghĩa thâm trầm, cao siêu hơn. Bởi vì lòng từ bi trong nhà Phật lúc nào cũng muốn đem lại sự an vui lợi lạc cho tất cả chúng sanh. Nhưng vì trình độ chúng sanh không giống nhau, nên các phương tiện hóa độ của chư Phật, Bồ-tát cũng khác nhau. Có người dùng lời hiền hòa, cử chỉ thương yêu chỉ dạy họ liền cảm mến nghe theo. Có người ngang bướng dùng lời hiền hòa nói họ không chịu nghe, buộc lòng phải có thái độ dường như ác dữ mới chuyển họ được.

Người dùng lời hiền hòa chỉ bảo dạy dỗ chúng ta, nhà Phật gọi là thiện hữu tri thức. Ngược lại những người rầy rà mắng chửi chúng ta, nhà Phật gọi là ác tri thức. Nghe nói ác là mình không ưa, điều này hầu hết Phật tử đều nhìn nhận như vậy. Nhưng nhà Phật không nghĩ thế. Bởi vì với người tu nhất là tu Phật, chúng ta không nên nhìn một mặt, mà phải nhìn thấu suốt toàn diện. Khi gặp khó khăn, những lúc thối chí, chúng ta phải nhờ thiện hữu tri thức hiền lành an ủi nhắc nhở, mới cố gắng vươn lên được. Nhưng khi tu hành an ổn, tự thấy như mình đạt đạo tới nơi thì tâm sanh kiêu mạn, tự hào. Trong trường hợp này nếu không có cơ hội cảnh tỉnh thì chúng ta rất khó thức tỉnh, cho nên phải có ác tri thức thử thách để hỗ trợ.

Ví dụ như chúng ta nguyện tu hạnh nhẫn nhục. Nếu ai cũng quí kính, tán thưởng thì mình thấy như thành công tới nơi rồi. Nhưng thật tình không có gì để làm bằng chứng rằng ta đã thực hành hạnh nhẫn nhục. Hôm nào bất thần có người đến chửi mắng, lúc đó mình ra sao? Chắc ta nghĩ người chửi mắng kia là kẻ ác muốn phá hoại sự tu hành của mình. Nghĩ như vậy là nhìn có một mặt. Chính cơ hội bị chửi mắng chúng ta mới thấy mình còn nóng giận, bực tức không? Bị chửi mắng mà còn nóng giận, bực tức thì hạnh nhẫn nhục chưa thực hành được.

Nếu người yếu hèn nhút nhát bị chửi mắng dễ thối lui. Còn người thấy rõ kẻ chửi mắng là ác tri thức, là người cảnh tỉnh để ta đừng mắc bệnh tự mãn. Nhờ chửi mắng nên mình thấy được mình. Nếu còn dở thì cố gắng tu thêm, nếu an nhẫn được trước sự chửi mắng, lòng vẫn thản nhiên tự tại thì mừng hạnh nhẫn nhục đã thành công. Như vậy người chửi mắng là ông giám khảo của chúng ta. Nhờ ông mà ta biết mình đậu hay rớt. Thế thì đó là người ân hay là kẻ oán? Người chửi mắng cho mình tiến lên, đạt được sở nguyện tu hành là người ân, chớ đâu phải kẻ oán.

Một bên an ủi vỗ về khích lệ chúng ta tiến tu. Một bên chửi mắng làm nhục mình mà ta vẫn tự tại. Hai người đó khác nhau không? Tuy hai hành động khác nhau nhưng kết quả đều đưa chúng ta đi lên chớ không phải dìm xuống. Trừ người chưa biết tu hoặc tu dối dối thì gặp cơ hội đó nổi sân lên oán hờn người ta. Chớ thật ra cả hai đều là ân nhân thành tựu đạo nghiệp cho mình cả. Chúng ta tu phải có đủ hai mặt. Có khi được người khuyên lơn vỗ về để khích lệ mình tiến lên trong lúc yếu đuối, nhưng cũng có khi nhờ người mạnh bạo dám chửi mắng, dám dùng những thủ đoạn ác để khử trừ bệnh ngã mạn, giúp chúng ta tiến lên. Cho nên cả hai người đều là bạn thân của chúng ta. Nhìn như thế mới hợp với đạo lý Phật dạy.

Chúng ta thường có bệnh phân biệt đây là người thân, kia là kẻ thù. Đã có thân có thù tức có thương có ghét, phiền não từ đó mà phát sanh. Bây giờ phải sửa lại, người giúp mình thân đành rồi, người phá hoại cũng thấy là người thân luôn. Được vậy đâu có thù ghét ai, đâu có phiền não dấy khởi. Thế nên ông thiện là biểu trưng cho hạnh từ bi thuận, phù hợp với việc lành; còn ông ác là biểu trưng cho hạnh từ bi nghịch, phù hợp với hạnh dữ. Nếu hiểu được vậy, quí Phật tử tu hành sẽ tiến nhanh, không thấy gì trở ngại hết. Còn không hiểu thế, tu một lúc dễ thối tâm. Bởi vì trên đường tu không phải lúc nào cũng gặp việc như ý.

Nhiều người không hiểu cứ than với chúng tôi, tại sao tu mà vẫn bị phá phách. Vì cho rằng phá phách là làm trở ngại sự tu hành của mình. Phật tử cứ nghĩ một bề, tu là ai cũng thương cũng quí kính mình hết, đó là sai lầm. Chúng ta tu trong nhà Phật dùng từ chuyên môn là khai chiến với ma quân. Do khai chiến nên bao nhiêu hiểm nguy dồn tới mình, để làm gì? Để thấy ta là chiến sĩ thắng trận hay bại trận. Nếu không có những thử thách đó, chắc rằng trên đường tu không ai là người xứng đáng hết. Vô chùa gặp việc gì cũng hay cũng tốt, lâu ngày mình mắc bệnh tự cao ngã mạn không hay. Cho nên những cái khó, những trở ngại là cơ hội tốt để chúng ta tiến tu

Như ở ngoài xã hội có cơ quan từ thiện, cũng có cơ quan cảnh sát. Thường thường nghe cơ quan từ thiện chúng ta có cảm tình, nhưng nghe cơ quan cảnh sát chúng ta hơi khó chịu. Song thử hỏi lại từ thiện và cảnh sát, cứu kính thế nào? Một bên giúp người khổ nạn để họ được an vui, một bên gìn giữ trật tự an ninh cho dân chúng sống bình yên. Cả hai đều có chung một mục đích là giúp cho mọi người sống an ổn. Thế thì ta đều phải quí phải thương hết hai bên mới phải, tại sao một bên thương, một bên không thích. Rõ ràng đó là quan niệm sai lầm.

Trong kinh Phật thường dạy, người tu phải bỏ hai bên, đừng oán đừng thân. Tức kẻ oán đừng chứa chấp trong lòng, người thân đừng trói buộc thêm. Muốn bỏ hai bên phải có lối nhìn như chúng tôi đã nói, người thân là ông thiện, người oán là ông ác. Ông thiện ông ác đều là người giúp cho mình tiến lên, nên cả hai đều bình đẳng đối với sự tu tiến của chúng ta. Bên nào cũng đưa mình lên chớ không bên nào muốn hạ mình xuống. Nếu có xuống là tại vì chúng ta còn yếu đuối thôi. Nói người ta làm khó tôi tu không được, điều đó sai lầm. Chỉ nên nói vì tôi yếu đuối nên gặp cảnh khó tôi thối lui. Lỗi ở mình chớ không phải lỗi ở cảnh.

Đa số chúng ta hay đổ thừa ngoại cảnh mà ít nhận lỗi nơi mình. Bây giờ nên tập nhìn khó và dễ, thiện và ác đối với chúng ta đều là cơ hội tốt. Nhìn tường tận như vậy thì trên đường tu không có gì cản trở mình được, chắc chắn chúng ta sẽ tiến và tiến mãi. Tinh thần này trong kinh Pháp Hoa, Phật đã nói rõ qua phẩm Đề-bà-đạt-đa. Đức Phật tuyên bố Đề-bà-đạt-đa đã từng hại Ngài nhiều đời nhiều kiếp, nhờ thế nên Ngài mới chóng thành Phật quả. Cho nên Đề-bà-đạt-đa chính là người ân, là nghịch hạnh tri thức bậc nhất tác thành đạo nghiệp cho Thế Tôn.

Do hiểu đạo lý chúng ta nhìn người ngăn trở gây khó khăn cho mình là ân nhân cở lớn, chớ không phải ân nhân thường. Vì người hiền lành không dám chửi ai, sợ mang tội. Chỉ có người dám chịu tội chửi ta để thử xem mình vươn lên được không, đó mới là tri thức cở lớn, là bậc Bồ-tát hy sinh vì chúng sanh. Người an ủi khuyến khích chúng ta tiến lên thì dễ quá, có phước chớ đâu sợ tội. Còn vì lợi cho người mà dám gánh tội về mình mới có công đức lớn, chúng ta phải bái phục họ chớ không nên giận hờn. Đó là Phật tử nhìn đủ cả hai mặt, không nhìn phiến diện. Đây là điểm thứ nhất.

Điểm thứ hai, Phật giáo luôn luôn dạy chúng ta phải biết tất cả chúng sanh đều có tánh Phật. Ai cũng có tánh Phật nên ai cũng có khả năng thành Phật. Kinh Pháp Hoa đã nói rất rõ về điều này. Trong phẩm Bồ-tát Thường Bất Khinh, Phật bảo Bồ-tát Thường Bất Khinh đi đâu, gặp ai cũng chấp tay lễ bái nói: *“Tôi không dám khinh các ngài, vì các ngài đều sẽ thành Phật”*. Như vậy Ngài có tu, có làm lợi ích gì cho ai chưa?

Chúng ta có bệnh khi nói đến Phật thì nghĩ Ngài là bậc cao cả tuyệt vời, mình không bao giờ với tới. Do tự ti mặc cảm như thế nên chỉ mơ ước mình tu mai kia được làm tôi tớ của Phật là phước lắm rồi, chớ mong chi làm Phật. Bồ-tát Thường Bất Khinh muốn phá tâm tự ti mặc cảm đó, nên Ngài luôn chấp tay bái chúng ta *“tôi không dám khinh các ngài, vì các ngài đều sẽ thành Phật”*. Đó là Ngài trao cho chúng ta một niềm tin rằng mình có khả năng làm Phật.

Tại sao chúng ta tin như vậy? Bởi vì đức Phật Thích-ca cũng là một con người, Ngài sống trong hoàng cung cũng có vợ có con, chớ đâu phải là ông thánh từ trên trời rơi xuống. Nhờ nỗ lực tu Ngài thành Phật. Chúng ta cũng là con người, nếu nỗ lực tu chúng ta cũng sẽ thành Phật, không nghi. Tất cả chúng ta đều có khả năng như Ngài, nhưng tại ta mặc cảm nên cứ thấy Ngài ở trên mây xanh, còn mình ở dưới đất. Giờ đây chúng ta thấy rõ mình có khả năng thành Phật nên cố gắng tu để đạt kết quả như nhau. Chỉ khi không cố gắng, không chịu tu chúng ta mới xa Phật thôi.

Một khi nhìn ra ai cũng có khả năng thành Phật, thì không chỉ giới xuất gia mới có khả năng thành Phật, mà kể cả hàng cư sĩ tại gia cũng có khả năng thành Phật. Không chỉ trong phạm vi người tu theo Phật mới có khả năng thành Phật mà người không tu theo Phật cũng có khả năng thành Phật. Nên nói cái nhìn của đạo Phật không phân biệt tôn giáo, không phân biệt màu da, chủng tộc, tất cả mọi người ai cũng có thể thành Phật, nếu biết tu.

Nhìn thấy ai cũng có khả năng thành Phật là Phật nhân. Tu hành tới cứu kính viên mãn là thành Phật quả. Ví dụ chúng ta đã sẵn có trong túi hạt bắp tốt. Giờ đây muốn có cây bắp, quả bắp thì chịu khó gieo hột trồng. Nếu có trồng có chăm sóc thì cây bắp sẽ vươn lên cho hoa cho trái. Chỉ người lười biếng không chịu trồng, có hạt giống mà để đó thì không bao giờ đạt được kết quả. Cũng thế, Phật tánh sẵn có trong mọi người, nhưng nếu ai chịu khó vén những lớp vô minh phiền não, phá hết các bệnh tự cao ngã mạn, mới có thể thành tựu Phật quả. Còn người biết mình có khả năng thành Phật, nhưng không phá trừ phiền não, tự cao tự đại thì có Phật nhân mà không được Phật quả nên vẫn khổ như bao nhiêu chúng sanh khác. Lẽ thật như thế, chớ không ai cao hơn ai cả.

Tôi thường ví dụ như cha mẹ giàu, có nhiều hòn ngọc quí như nhau. Trong gia đình năm ba anh em, khi cha mẹ gần mất mới đem ngọc quí đó chia mỗi đứa một viên. Người anh cả biết đem bán ra xài thì sẽ giàu có sang trọng. Nhưng mấy người em mải lo việc học hành hay việc này việc nọ, họ cất kỹ viên ngọc và quên luôn. Người anh cả nhà cửa sang trọng thấy mấy đứa em nhà cửa xấu xí nhưng có dám khinh không? Tuy hình thức hiện tại thấy mình hơn các em, nhưng thật ra của báu bên trong chúng nó cũng như mình. Do đó đâu dám khinh.

Hiểu như vậy tất cả chúng ta dù tu trước hay tu sau đều biết ai cũng có thể thành Phật. Cho nên không bao giờ nghĩ ta tu cao người kia tu thấp. Hoặc ta biết tu, người kia không biết tu… Người có của quí mà biết dùng thì được sang trọng. Người có của quí nhưng quên lãng, không biết dùng thì tạm thời nghèo khổ, chớ thật sự không phải nghèo. Trách nhiệm của chúng ta là nhắc nhở, đánh thức nhau lấy của báu ra dùng. Tình thương cứu giúp như vậy nhà Phật gọi là lòng từ bi. Cho nên từ bi trong đạo Phật là làm sao mọi người có của quí đều biết dùng, để cùng được sung sướng như nhau. Vì có tình thương đó nên đạo Phật không cho phép chúng ta ngồi ngó lơ, ai khổ mặc họ, không thèm biết tới, sống như vậy thì ích kỷ quá.

Các chùa Việt Nam đa số đều khuyên Phật tử nên tụng kinh Pháp Hoa, có khi tụng cả tuần lễ. Đó là vì kinh Pháp Hoa rất quan trọng, rất cần thiết, quí thầy cô muốn tất cả Phật tử ai cũng đều hiểu, đều sống đúng với tinh thần ấy. Song rất tiếc có những người tụng mà không ứng dụng. Nếu biết học theo gương của Bồ-tát Thường Bất Khinh, chúng ta sẽ tiến được nhiều ít? Bệnh lớn của con người là tự cao ngã mạn, thấy ai hơn mình thì đâm ra bực tức đố kỵ, thấy ai thua mình thì khinh rẻ. Ai ở cho vừa lòng mình? Cứ nghĩ ai hơn là lấn lướt mình, ai thua là hèn hạ hơn mình, mà không ngờ mình và mọi người đều có khả năng thành Phật như nhau. Hơn thua chẳng qua là nghiệp tập thôi.

Ví dụ người có phương tiện đi học có cấp bằng này cấp bằng nọ, còn người không có phương tiện không được đi học nên quê dốt. Người quê dốt và người học cao có khác ở sự huân tập. Huân tập hay thì trở thành hay, huân tập dở thì trở thành dở. Huân tập là cái mới chớ không phải cái sẵn, cái sẵn thì ai cũng như nhau cho nên không có cao thấp. Chúng ta nhìn trên mặt huân tập sai biệt, mà không nhìn ngay cội nguồn căn bản, để thấy ai cũng có khả năng giác ngộ. Nhìn như thế mới không dám khinh miệt ai hết.

Người có tâm đố kỵ là do nhìn trên nghiệp tướng sai biệt, mà không nhận ra bản tánh bình đẳng của muôn loài. Hiểu thế rồi chúng ta phải làm sao có cái nhìn thấu suốt rõ ràng rằng ai cũng có tánh Phật. Đã có tánh Phật thì mọi người đều có khả năng thành Phật, quả vị Phật không chỉ dành riêng cho mình, còn người khác không có. Ai cũng có quyền làm Phật hết. Người hiểu đạo đi trước nhắc người đi sau, để cùng nhau nhận ra tánh Phật bình đẳng ấy, không ai khinh khi ai. Được vậy đức khiêm tốn sẽ đến với mình, chấp ngã dần dần tiêu mất.

Chỉ cần hai cái nhìn, thứ nhất là không có thân và thù. Kẻ thân người thù chẳng qua là phương tiện giúp chúng ta tiến tu thôi. Ai cũng được xem như ân nhân của mình hết. Đã là ân nhân thì không có chuyện thương người này ghét người kia, ta đều thương mến mọi người như nhau. Tình thương đó mới bình đẳng, mới gọi là từ bi chứ. Cái nhìn thứ hai là ai cũng có khả năng thành Phật, do đó ta không dám khi người này, đố kỵ người kia. Chúng ta sống trong tinh thần bao dung hòa hợp, khiêm tốn, cung kính mọi người. Cho nên Bồ-tát Thường Bất Khinh suốt đời chỉ làm một việc, gặp ai Ngài cũng bái nói: *“Tôi không dám khinh các ngài, vì các ngài đều sẽ thành Phật”*. Mới nghe qua chúng ta thấy như Ngài không đem lợi lạc gì cho ai, nhưng đức Phật Thích-ca đã nói: Bồ-tát Thường Bất Khinh ngày xưa là tiền thân của Ngài. Do tu hạnh ban rải niềm tin đến cho mọi người, giúp họ nhận ra mình có khả năng thành Phật, mà Ngài được thành Phật hiệu Thích-ca. Chúng ta thấy nhân dường như quá đơn giản mà quả to lớn vô cùng. Đó là hai cái nhìn tốt đẹp trong tinh thần Phật giáo Việt Nam nói riêng cũng như tinh thần Phật giáo nói chung.

Đến cái nhìn thứ ba là cái nhìn của Thiền sư. Ở Việt Nam có phái thiền Trúc Lâm Yên Tử, Sơ tổ là một ông vua đi tu tức vua Trần Nhân Tông. Ngài xuất gia tu hành ngộ đạo, sau đó lập ra hệ phái thiền Trúc Lâm Yên Tử. Sau này Ngài được tôn là Sơ tổ Trúc Lâm. Chúng tôi thành lập Thiền viện cũng để tên Thiền viện Trúc Lâm là muốn nói lên tinh thần của Thiền tông Việt Nam.

Thế thì Thiền tông Việt Nam có những điểm gì đáng cho chúng ta phải lưu tâm? Ở đây tôi nói qua một nét nhỏ thôi, vì không đủ thời gian nói nhiều. Quí vị nào có đọc bài phú Cư Trần Lạc Đạo bằng văn Nôm của vua Trần Nhân Tông, sẽ nhớ phần kết thúc Ngài viết bốn câu kệ bằng chữ Hán thế này:

<div class="align-center">
> Cư trần lạc đạo thả tùy duyên  
> Cơ tắc xan hề khốn tắc miên  
> Gia trung hữu bảo hưu tầm mích  
> Đối cảnh vô tâm mạc vấn thiền  
</div>

Dịch:

<div class="align-center">
> Ở đời vui đạo hãy tùy duyên  
> Đói đến thì ăn mệt ngủ liền  
> Trong nhà có báu thôi tìm kiếm  
> Đối cảnh không tâm chớ hỏi thiền  
</div>

Chỉ bốn câu thôi mà ý nghĩa thật tuyệt diệu. Ở đời vui đạo hãy tùy duyên là sống giữa cõi trần tục, tức ngay giữa lòng đời, chúng ta vẫn vui với đạo. Làm sao để được vui? Ngài dạy phải khéo tùy duyên. Tùy duyên thế nào? Đói đến thì ăn mệt ngủ liền, dễ quá phải không? Ai cũng bằng lòng như thế. Nhưng thưa đừng hiểu lầm chỗ này. Ai không đói ăn mệt ngủ. Nhưng bốn chữ đói ăn mệt ngủ này mang tính chất cụ thể của ý nghĩa tùy duyên. Cụ thể thế nào?

Bởi vì tùy duyên là khi nhu cầu đến chúng ta giải quyết ngay nhu cầu đó, đừng băn khoăn, đừng lo liệu, đừng sợ hãi. Đói ăn, mệt ngủ tức là những nhu cầu trong sinh hoạt bình thường của chúng ta. Tùy theo hoàn cảnh mà mình giải quyết, đừng tính toán băn khoăn hay trông đợi gì cả, đó là tùy duyên. Nếu chúng ta băn khoăn, tính toan, lo sợ v.v… trước hoàn cảnh hiện tại, cứ do dự mãi nên không giải quyết được gì cả, đó là chưa biết tùy duyên. Nghĩa là khi nào có sự việc xảy đến, chúng ta cứ ngay đó giải quyết, không nghĩ đây là việc to rồi hồi hộp sợ hãi; không nói đây là lợi tâm sanh vui mừng, hoặc đây là hại nên bực bội tức tối. Tùy duyên giải quyết, việc gì đến thì làm một cách an nhàn tự tại, đó là sống tùy duyên. Còn giải quyết bằng cách cau có bực bội là chưa biết tùy duyên.

Muốn sống giữa cõi đời mà vẫn vui với đạo thì phải biết ý nghĩa tùy duyên ấy. Nếu gặp việc thuận thì mừng, việc nghịch thì giận là chưa tùy duyên. Người như thế không thể tìm nguồn vui của đạo ở trong lòng cuộc đời. Hai câu này đã nói lên một pháp tu rồi. Tu cả đời cũng chưa xong nữa. Làm sao trong cuộc sống này mọi việc xảy ra đều được như ý chúng ta hết. Phần nhiều sự việc như ý ít mà việc bất như ý thì nhiều. Nếu mình không biết tùy duyên, gặp việc bất như ý buồn khổ năm bảy ngày, như vậy một đời người chúng ta lăn lộn trong cõi trần chịu khổ đến bao nhiêu? Làm sao vui với đạo được!

Nhờ biết tùy duyên, sự việc đến chúng ta bình thản giải quyết, không lo lắng sợ sệt. Cũng như khi đói gặp cơm thì ăn. Có gì ăn nấy không đòi hỏi món này món nọ, không chê khen ngon dở. Khi mệt nằm xuống liền ngủ, không nghĩ xa nghĩ gần, không toan tính việc gì cả. Người sống như vậy là tùy duyên. Chớ đừng nghĩ tùy duyên đói ăn mệt ngủ, rồi đói lúc nào lôi cơm ăn lúc ấy, mệt lúc nào nằm ì ra ngủ lúc đó, không biết giờ khắc tu hành gì hết, thì không được. Hiểu như thế chúng ta mới thấy tinh thần tu của Sơ tổ Trúc Lâm.

Trong nhà có báu thôi tìm kiếm, Ngài thấy rõ nơi con người chúng ta có hòn ngọc quí sẵn bên  trong, nên bảo mình đừng chạy tìm kiếm ở đâu cho nhọc. Chúng ta đã có ngọc, ngọc đó là tánh giác, là Phật. Như vậy muốn tìm Phật đâu cần phải leo lên non hay lặn xuống biển, chỉ ngay nơi mình xoay đầu nhìn lại là có Phật thôi. Chúng ta khéo đừng để những phiền não ô nhiễm che lấp tánh giác sẵn có. Lặng hết phiền não ô nhiễm thì ông Phật của mình hiện tiền. Cho nên nhiều người tới chùa thấy thờ các vị A-la-hán, có vị phạch ngực ra, bên trong có hình Phật ngồi. Đó là để chỉ ông Phật sẵn đây rồi, chỉ cần vạch hết phiền não nhớp nhúa sang một bên, thì Phật hiện ra ngay, không khó khăn gì hết.

Đến câu chót là câu rất chí thiết trong nhà thiền. Đối cảnh không tâm chớ hỏi thiền. Đối cảnh tức là mắt thấy sắc, tai nghe tiếng, mũi ngửi mùi v.v… Khi sắc đẹp đến, mắt vẫn thấy mà không có tâm muốn được, không dính mắc ở sắc đẹp. Tai nghe tiếng, biết rõ mà không có tâm khen chê. Mũi ngửi mùi phân biệt rõ ràng thơm hôi, nhưng không vì hôi mà bực, không vì thơm mà nhiễm. Lưỡi nếm vị có ngon dở, nhưng không vì ngon mà đòi thêm, không vì dở mà chán bực. Tóm lại, đối với sáu trần chúng ta không có niệm đuổi theo, không có niệm dính mắc. Ngay đó là thiền rồi, khỏi cần hỏi ai hết. Rất đơn giản.

Thiền rất đơn giản nhưng tại chúng ta không chịu giản đơn thành ra cứ nắm, cứ dính hoài. Đừng thèm dính thì đơn giản vô cùng. Nên biết thiền không phải cái gì huyền bí xa xôi, chỉ cần đừng đuổi theo, đừng dính mắc với năm trần bên ngoài. Người không dính mắc với năm trần  có tự tại, có an lạc không? Tự nhiên là tự tại, là an lạc. Còn người đuổi theo, dính mắc với năm trần thì dĩ nhiên là bị nó trói buộc lôi đi. Điều đó quá rõ ràng, chúng ta đã biết hết rồi, chỉ không ứng dụng tu nên chưa được an lạc, chưa được tự tại thôi.

Như vậy thiền của đạo Phật dạy cho chúng ta đừng dính mắc với năm trần bên ngoài và pháp trần bên trong, nói chung là sáu trần. Đừng dính với sáu thứ đó thì tự tại an nhàn. Quí vị kiểm nghiệm lại xem, những sai lầm của mình từ trước đến giờ có phải do ta không sống đúng với tinh thần Phật dạy không? Nếu chúng ta ứng dụng hai câu trên, tùy duyên sống trong cõi đời mà vui với đạo, thì cuộc sống rất thong dong, tự tại. Thấy rõ nơi mình có của báu rồi, khỏi đi hỏi ai, khỏi tìm cầu nơi nào khác. Ta tự an ổn bằng cách làm cho hòn ngọc quí của mình hiện ra.

Người đời khổ vì mắt thấy sắc cho là đẹp, muốn được về mình, không được thì buồn. Tai nghe tiếng hay muốn tiếng đó tiếp tục mãi, không được cũng buồn. Lưỡi thích vị ngon nên đưa vị dở vô cũng buồn. Chúng ta cứ đuổi theo, đòi hỏi năm trần thành ra khổ. Nếu mình không dính mắc gì hết, không có niệm đuổi theo nó thì cứ đói ăn, mệt ngủ, không ngại chi cả. Tu tức là tìm nguồn an lạc trong tâm, chớ không phải có nhiều tiền nhiều của. Chỉ không dính mắc bên ngoài là tâm an lạc.

Cho nên đối với cái nhìn của Phật giáo Việt Nam, việc tu rất đơn giản. Nếu chúng ta khéo ứng dụng, chỉ bốn câu kệ của Sơ tổ Trúc Lâm đời mình cũng đã thảnh thơi rồi. Tôi xin nhấn mạnh phải khéo ứng dụng, chớ không phải học thuộc lòng bốn câu kệ đó mà thong dong tự tại. Việc ngừng đuổi theo năm trần là việc làm của chúng ta, không phải của Phật, Tổ hay thầy mình. Dính cũng mình, không dính cũng mình. Ai cũng có quyền làm việc đó hết. Chỉ chịu làm hay không chịu làm thôi.

Hiểu vậy mới thấy đạo Phật rất gần với chúng ta, nhưng vì mình không thức tỉnh nên thấy như cách xa. Ai cũng có khả năng thành Phật, dù ngày nay người đó chưa tu còn nhiều nghiệp ác, nhưng ngày mai thức tỉnh họ tu thì cũng tốt. Còn chúng ta đang tu, nhưng nếu ngày mai thối tâm thì cũng thành người xấu như thường.

Bởi vậy trong nhà thiền có kể câu chuyện: Ngày xưa anh chàng làm hàng thịt nọ buôn bán mấy chục năm ngoài chợ, bất thần hôm đó anh thức tỉnh bỏ nghề hàng thịt, xuất gia tu hành. Khi xuất gia rồi, sáng sờ đầu bỗng có tỉnh, anh làm bài kệ:

<div class="align-center">
> Tạc nhật dạ-xoa tâm  
> Kim triêu Bồ-tát diện  
> Dạ-xoa dữ Bồ-tát  
> Bất cách nhất điều tuyến  
</div>

Dịch:
<div class="align-center">
> Hôm qua tâm dạ-xoa  
> Ngày nay mặt Bồ-tát  
> Dạ-xoa cùng Bồ-tát  
> Không cách nhau đường tơ  
</div>

Mới hôm qua làm người hàng thịt là tâm quỉ dạ-xoa, nhưng khi thức tỉnh, cạo đầu tu thì bữa nay nhìn ra mặt Bồ-tát. Như vậy Bồ-tát và quỉ dạ-xoa cách nhau bao xa? Không cách một đường tơ, gần bên nhau chớ không xa chút nào hết.

Hiểu như vậy chúng ta thấy trên đường tu ai cũng có phần, dù người đó đang lao đao lận đận trong cảnh tội lỗi. Nhưng khi họ thức tỉnh rồi cũng sẽ thành Bồ-tát. Do đó ta không dám khinh khi ai, phải học theo hạnh Bồ-tát Thường Bất Khinh, gặp mọi người đều lễ bái nói: *“tôi không dám khinh các ngài, vì các ngài đều sẽ thành Phật”*. Nếu chúng ta biết tu và ứng dụng đúng theo lối của Phật Tổ dạy, chắc rằng con đường giải thoát không xa. Chỉ không khéo ứng dụng tu mới thấy con đường giải thoát cách xa trời vực.

Hôm nay tôi chỉ giới thiệu đơn giản một vài nét của Phật giáo Việt Nam cho quí vị nhớ ứng dụng tu, để Phật tử đừng hiểu lầm Phật giáo Việt Nam chuyên đi cúng đi lễ bái hoài. Phật giáo Việt Nam có những ưu điểm hay lắm nhưng tại chúng ta ứng dụng, thực hành chưa đúng. Mong tất cả hiểu và ứng dụng tu theo những gì Tổ tiên mình đã chỉ dạy. Được vậy lợi ích thiết thực nhất định sẽ đến với chúng ta.
s
